Repository matrix-org/matrix-js-sdk, pull requests merged in 2020-04, with the labels that each got.

#1307 Use the correct request body for the /keys/query endpoint.
  spec/TestClient.js
  spec/integ/matrix-client-crypto.spec.js
  spec/integ/matrix-client-methods.spec.js
  src/base-apis.js
Labels: Community PR

#1333 Fix: don't do extra /filter request when enabling lazy loading of members
  src/filter.js
  src/sync.js
Labels: release-blocker

#1354 Add crypto.willUpdateDevices event and make getStoredDevices/getStoredDevicesForUser synchronous
  CHANGELOG.md
  src/client.js
  src/crypto/DeviceList.js
  src/crypto/SecretStorage.js
  src/crypto/index.js
  src/crypto/verification/Base.js
  src/crypto/verification/QRCode.js
  src/models/room.js
Labels: breaking-change

#1359 Fix race between sending .request and receiving .ready over to_device
  src/crypto/index.js
Labels: phase:3, story:1
