Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-07, with the labels that each got.

#1784 Expose MatrixEvent's internal clearEvent as a function
  src/models/event.ts
Labels: Sponsored

#1789 Switch callEventHandler from listening on `event` to `Room.timeline`
  src/webrtc/callEventHandler.ts
Labels: T-Enhancement

#1791 Switch from `url` to URL constructor
  src/client.ts
  src/interactive-auth.js
  src/utils.ts
Labels: T-Task

#1778 Add minimal types for "notification settings" UI
  src/@types/PushRules.ts
  src/@types/requests.ts
  src/@types/threepids.ts
  src/client.ts
Labels: Sponsored, T-Task

#1796 Update eslint-plugin-matrix-org
  yarn.lock
Labels: T-Task

#1799 Actually print IndexedDB command error if there is one
  src/store/indexeddb-remote-backend.ts
Labels: T-Task

#1802 yarn upgrade
  yarn.lock
Labels: T-Task

#1808 Convert crypto/store/* to Typescript
  package.json
  src/@types/partials.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/DeviceList.ts
  src/crypto/OlmDevice.js
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/RoomList.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
  src/indexeddb-helpers.ts
  src/logger.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb.ts
  yarn.lock
Labels: T-Task, X-Blocked
