Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-11, with the labels that each got.

#2009 Fetch thread root event if it's missing from the sync
  src/models/room.ts
Labels: T-Task

#2010 Update allchange to 1.0.5
  package.json
  yarn.lock
Labels: T-Task

#2011 Make events pagination responses parse threads
  src/client.ts
  src/sync.ts
Labels: T-Defect

#2012 Copy relations to thread root in the thread timeline
  src/client.ts
  src/models/event.ts
  src/models/room.ts
Labels: T-Task

#2013 Fix edit history being broken after editing an unencrypted event with an encrypted event
  src/client.ts
Labels: T-Defect

#2017 Fix check supportExperimentalThreads
  src/client.ts
Labels: T-Task

#2020 Add registration token UIA type
  src/interactive-auth.ts
Labels: T-Task

#2025 Update sync state to error when aborting due to invalid auth token
  src/sync.ts
Labels: T-Task

#2027 Add optional force parameter when ensuring Olm sessions
  src/crypto/index.ts
Labels: T-Enhancement

#2029 Iterate type definitions
  src/@types/PushRules.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/api.ts
  src/crypto/index.ts
Labels: T-Task

#2033 Add KeyVerificationRequest msgType
  src/@types/event.ts
Labels: T-Task

#2024 Fix call upgrades
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
Labels: T-Defect

#2032 getStateEvent should return any
  src/client.ts
Labels: T-Task

#2021 Implementation of passphrase deriveKey() for Node.js
  src/crypto/key_passphrase.ts
Labels: T-Enhancement

#2014 Standardise content type handling in MSC3089 createFile() and createNewVersion()
  spec/MockBlob.ts
  spec/unit/models/MSC3089Branch.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
Labels: T-Enhancement

#2042 Upgrade allchange to 1.0.6
  package.json
  yarn.lock
Labels: T-Task
