Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-10, with the labels that each got.

#1963 Prepend events to thread when fetching the reply chain
  src/models/thread.ts
Labels: T-Task

#1962 Prevent redactions to be sent as pending events
  src/models/event.ts
  src/models/room.ts
Labels: T-Task

#1964 Use `ICallFeedOpts` in the `CallFeed` constructor
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
Labels: T-Enhancement, X-Breaking-Change

#1966 Enable TypeScript declaration maps
  tsconfig-build.json
Labels: T-Enhancement

#1968 Tweak Room Hierarchy root visibility and add loading getter
  src/room-hierarchy.ts
Labels: T-Task
