Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-06, with the labels that each got.

#1732 Unstable implementation of MSC3089: File Trees
  spec/MockBlob.ts
  spec/unit/NamespacedValue.spec.ts
  spec/unit/matrix-client.spec.js
  spec/unit/models/MSC3089Branch.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/utils.spec.js
  spec/unit/utils.spec.ts
  src/@types/event.ts
  src/@types/requests.ts
  src/NamespacedValue.ts
  src/client.ts
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
  src/utils.ts
Labels: X-Release-Blocker

#1740 Add invite retries to file trees
  package.json
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/utils.spec.ts
  src/models/MSC3089TreeSpace.ts
  src/utils.ts
  yarn.lock
Labels: Sponsored

#1738 Add functions to assist in immutability of Event objects
  spec/unit/models/event.spec.ts
  spec/unit/utils.spec.ts
  src/models/event.ts
  src/utils.ts
Labels: Sponsored

#1744 Add keysharing on invites to File Tree Spaces
  spec/unit/models/MSC3089TreeSpace.spec.ts
  src/crypto/algorithms/megolm.js
  src/models/MSC3089TreeSpace.ts
Labels: Sponsored

#1508 Typescriptify some crypto stuffs
  package.json
  spec/unit/crypto/outgoing-room-key-requests.spec.js
  src/@types/global.d.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/DeviceList.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/aes.ts
  src/crypto/algorithms/base.ts
  src/crypto/algorithms/index.ts
  src/crypto/algorithms/megolm.js
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.js
  src/crypto/algorithms/olm.ts
  src/crypto/api.ts
  src/crypto/backup.ts
  src/crypto/dehydration.ts
  src/crypto/deviceinfo.ts
  src/crypto/index.ts
  src/crypto/keybackup.ts
  src/crypto/olmlib.ts
  src/crypto/recoverykey.ts
  src/crypto/store/base.ts
  src/models/event.ts
  src/utils.ts
  yarn.lock
Labels: X-Blocked
