Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-08, with the labels that each got.

#1812 Support for MSC3291: Muting in VoIP calls
  spec/unit/utils.spec.ts
  spec/unit/webrtc/call.spec.ts
  src/@types/event.ts
  src/utils.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callEventTypes.ts
  src/webrtc/callFeed.ts
Labels: T-Enhancement

#1821 Clean-up some VoIP code
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callEventTypes.ts
Labels: T-Task

#1824 Switch to new changelog generator
  package.json
  release.sh
  yarn.lock
Labels: T-Task

#1825 Add CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#1820 Send `user_hangup` reason if the opponent supports it
  src/webrtc/call.ts
Labels: T-Defect

#1831 Expose a getFileEvent() function off a MSC3089Branch
  src/models/MSC3089Branch.ts
Labels: X-Release-Blocker, T-Task, Sponsored

#1832 Add changelog preview action
  .github/workflows/preview_changelog.yaml
Labels: T-Task

#1835 Add support for reading permissions from tree spaces
  src/models/MSC3089TreeSpace.ts
Labels: X-Release-Blocker, T-Task, Sponsored

#1837 Fix blank profile in join events
  src/models/event-timeline.ts
Labels: T-Defect

#1841 Fix conditional on returning file tree spaces
  spec/unit/matrix-client.spec.js
  src/client.ts
Labels: T-Defect, Sponsored

#1842 Fix the types in shipped package
  package.json
  tsconfig-build.json
  tsconfig.json
Labels: T-Defect

#1834 Fix temporary call messages being handled without call
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#1792 Deprecate groups APIs
  src/client.ts
  src/models/group.js
  src/store/index.ts
  src/store/memory.ts
  src/store/stub.ts
Labels: T-Task, X-Deprecates

#1772 Convert SearchResult, InteractiveAuth, PushProcessor and Scheduler to TS
  src/@types/PushRules.ts
  src/client.ts
  src/interactive-auth.ts
  src/models/event.ts
  src/models/search-result.ts
  src/pushprocessor.ts
  src/scheduler.js
  src/scheduler.ts
  src/sync.ts
  src/utils.ts
Labels: T-Task

#1852 Clarify usages of event's toJSON
  src/models/event.ts
Labels: T-Task

#1851 Fix glare related regressions
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#1854 [Release] Fix glare related regressions
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#1855 Update changelog generator
  package.json
  yarn.lock
Labels: T-Task

#1856 Fix release script to handle no signing ID
  release.sh
Labels: T-Task

#1857 Revert "Fix glare related regressions"
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#1858 Fix broken voice calls, no ringing and broken call notifications
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#1860 Fix multiple VoIP regressions
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#1862 Fix release script to handle no signing ID
  release.sh
Labels: T-Task

#1853 Expose IMyDevice interface
  src/client.ts
Labels: T-Task

#1849 Make delegateCryptoCallbacks an optional parameter of EncryptionSetupBuilder and SSSSCryptoCallbacks
  src/crypto/EncryptionSetup.ts
Labels: T-Task

#1850 Add method for including extra fields when uploading to a tree space
  src/models/MSC3089TreeSpace.ts
Labels: T-Enhancement, Sponsored

#1859 Revert quick VoIP fix
  src/webrtc/callEventHandler.ts
Labels: T-Task

#1864 Add necessary changes for PasswordReset migration
  src/client.ts
Labels: T-Task

#1847 SSSSCryptoCallbacks.getSecretStorageKey: Test if delegateCryptoCallbacks has getSecretStorageKey
  src/crypto/EncryptionSetup.ts
Labels: T-Task

#1865 Give `CallFeed` the capability to emit on volume changes
  src/@types/global.d.ts
  src/webrtc/callFeed.ts
Labels: T-Enhancement

#1875 Improve browser example
  examples/browser/browserTest.js
  examples/browser/index.html
Labels: T-Enhancement

#1874 Improve TypeScript in `MatrixCall`
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callEventTypes.ts
Labels: T-Task
