Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-09, with the labels that each got.

#1877 Improve typing around join rules
  src/@types/partials.ts
  src/models/room-state.ts
  src/models/room.ts
Labels: T-Task

#1876 Add reply events rendering hint
  src/@types/event.ts
  src/models/event.ts
  src/sync.ts
Labels: T-Task

#1873 Give `MatrixCall` the capability to emit `LengthChanged` events
  src/webrtc/call.ts
Labels: T-Enhancement

#1882 Fix replyInThread getter to match event m.in_reply_to structure
  src/models/event.ts
Labels: T-Task

#1885 Improve thread deduplication thread process
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync.ts
Labels: T-Task

#1872 Count notifications in encrypted rooms client-side
  src/client.ts
  src/models/event.ts
  src/sync.ts
Labels: T-Enhancement

#1884 Convert OlmDevice to Typescript
  spec/unit/crypto/algorithms/olm.spec.js
  spec/unit/crypto/backup.spec.js
  src/@types/partials.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/OlmDevice.js
  src/crypto/OlmDevice.ts
  src/crypto/aes.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
Labels: T-Task

#1888 Convert crypto/verification/* to Typescript
  spec/unit/crypto/verification/request.spec.js
  spec/unit/crypto/verification/secret_request.spec.js
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/deviceinfo.ts
  src/crypto/index.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/Error.ts
  src/crypto/verification/IllegalMethod.ts
  src/crypto/verification/QRCode.ts
  src/crypto/verification/SAS.ts
  src/crypto/verification/request/Channel.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/crypto/verification/request/ToDeviceChannel.ts
  src/crypto/verification/request/VerificationRequest.ts
Labels: T-Task

#1897 Exclude opt-in Element performance metrics from encryption
  src/crypto/index.ts
Labels: T-Enhancement, X-Release-Blocker, Sponsored

#1900 Disable pending events for threads temporarily
  src/client.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Task

#1901 [Release] Exclude opt-in Element performance metrics from encryption
  src/crypto/index.ts
Labels: T-Enhancement, X-Release-Blocker, Sponsored

#1878 Remove Element-specifc screen-sharing code out of the js-sdk
  src/@types/global.d.ts
  src/webrtc/call.ts
Labels: X-Breaking-Change, T-Task

#1904 Properly dispose of CallFeeds
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
Labels: T-Task

#1908 Add `ISasEvent`
  src/crypto/verification/SAS.ts
Labels: T-Enhancement

#1906 Move all relations event in thread timeline
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync.ts
Labels: T-Task

#1914 Types adjustment for TS migration
  src/models/room-member.ts
Labels: T-Task

#1915 Add `hasBeenCancelled` to `VerificationBase`
  src/crypto/verification/Base.ts
Labels: T-Enhancement

#1917 Tests for key sharing security fix
  spec/unit/crypto/algorithms/megolm.spec.js
Labels: T-Task

#1903 Add types for the MatrixClient register method
  src/client.ts
Labels: T-Task

#1910 Add missing tests for MSC3089 implementation
  spec/unit/models/MSC3089Branch.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
Labels: T-Task, Sponsored

#1909 Add file locking to MSC3089 branches
  spec/unit/models/MSC3089Branch.spec.ts
  src/models/MSC3089Branch.ts
Labels: T-Enhancement, Sponsored

#1911 Improve `MatrixCall` media handling and internally remove `CallType`s
  src/client.ts
  src/matrix.ts
  src/webrtc/call.ts
  src/webrtc/mediaHandler.ts
Labels: X-Breaking-Change, T-Task

#1913 Type fixes for security dialogs TS migration
  src/client.ts
  src/crypto/api.ts
  src/crypto/index.ts
Labels: T-Task

#1907 TypeScript migration for js-sdk
  src/autodiscovery.ts
  src/client.ts
  src/errors.ts
  src/realtime-callbacks.ts
Labels: T-Task

#1919 yarn upgrade
  yarn.lock
Labels: T-Task

#1920 Fix types
  src/autodiscovery.ts
Labels: T-Task

#1922 Revert "Migrate errors to TypeScript"
  src/errors.js
Labels: T-Task

#1923 Remove RTX codec hack
  src/webrtc/call.ts
Labels: X-Blocked, T-Task

#1924 Revert "Remove RTX codec hack "
  src/webrtc/call.ts
Labels: T-Task

#1925 Add `setCodecPreferences()` to `global.d.ts`
  src/@types/global.d.ts
Labels: T-Task

#1927 Add `getBuffer()` to `QRCodeData`
  src/crypto/verification/QRCode.ts
Labels: T-Enhancement

#1928 Clone and stop local media streams from mediaHandler
  src/webrtc/call.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#1929 Add WebRTC DataChannels to MatrixCall
  src/webrtc/call.ts
Labels: T-Enhancement

#1880 Palid/fix/dont persist log level
  src/logger.ts
Labels: T-Task

#1930 Typescriptify thread events a bit
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Task

#1932 Fix improperly named enum
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Task

#1936 Fix race on automatic backup restore
  src/crypto/CrossSigning.ts
Labels: T-Defect

#1933 Update PR guidelines for easier review
  CONTRIBUTING.md
Labels: T-Task

#1937 Fix `getUserMediaStream()` not being able to handle streams of different track combinations
  src/webrtc/mediaHandler.ts
Labels: T-Defect, X-Release-Blocker

#1939 Fix stream stopping and improve logging
  src/webrtc/mediaHandler.ts
Labels: T-Defect, X-Release-Blocker

#1940 Add `getHistoryVisibility()` and `getGuestAccess()`
  src/models/room-state.ts
  src/models/room.ts
Labels: T-Enhancement

#1942 Add `trusted_locally` to `TrustInfo`
  src/crypto/backup.ts
Labels: T-Enhancement

#1941 Add `bound` to `IThreepid`
  src/@types/threepids.ts
Labels: T-Enhancement

#1938 Ensure unencrypted fields get exposed by getEffectiveEvent()
  src/models/event.ts
Labels: T-Defect

#1934 Switch to /kick API
  src/client.ts
Labels: T-Task

#1944 Share room state events with thread's timelines
  spec/unit/room.spec.js
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Task

#1947 Add tests requirements to CONTRIBUTING
  CONTRIBUTING.md
Labels: T-Task

#1945 Add thread serialisation helper
  src/models/thread.ts
Labels: T-Task

#1948 Fix event partitioning from non threading ready clients
  src/sync.ts
Labels: T-Defect

#1949 Fix not returning new mic mute state
  src/webrtc/call.ts
Labels: T-Defect

#1950 Allow answering calls without audio/video
  src/webrtc/call.ts
Labels: T-Enhancement

#1953 Pass correct params to `upgradeCall()` to upgrade audio
  src/webrtc/call.ts
Labels: T-Defect

#1935 Make RoomState::hasSufficientPowerLevelFor public
  src/models/room-state.ts
Labels: T-Task

#1952 Implement file versioning for tree spaces
  spec/unit/models/MSC3089Branch.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
Labels: T-Enhancement, Sponsored

#1954 Changes for TS migration
  src/client.ts
Labels: T-Task

#1958 Make sure to set `callLengthInterval` only once
  src/webrtc/call.ts
Labels: T-Defect

#1959 Fix incorrect return value type in getJoinedRooms()
  src/client.ts
Labels: T-Defect
