Repository matrix-org/matrix-js-sdk, pull requests merged in 2021-12, with the labels that each got.

#2046 Add method to fetch /account/whoami
  src/client.ts
Labels: T-Enhancement

#2047 FIX exports type
  src/index.ts
  src/matrix.ts
Labels: T-Task

#2049 Fix incorrect MSC3089 typings and add null checks
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
Labels: T-Defect

#2051 Add new room event filter fields
  src/filter.ts
Labels: T-Enhancement

#2048 Finish adding registration token UIA type
  src/interactive-auth.ts
Labels: T-Task

#2055 Improve typing
  package.json
  spec/integ/matrix-client-retrying.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/utils.spec.ts
  spec/unit/webrtc/call.spec.ts
  src/ReEmitter.ts
  src/client.ts
  src/content-repo.ts
  src/crypto/DeviceList.ts
  src/crypto/SecretStorage.ts
  src/crypto/algorithms/base.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/index.ts
  src/crypto/keybackup.ts
  src/crypto/olmlib.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/http-api.js
  src/interactive-auth.ts
  src/logger.ts
  src/matrix.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/room.ts
  src/scheduler.ts
  src/store/index.ts
  src/store/indexeddb-local-backend.ts
  src/utils.ts
Labels: T-Task

#2054 Fix paginateEventTimeline resolve to boolean
  src/client.ts
Labels: T-Defect

#2003 Fix imports to work with new lint rules
  package.json
  spec/TestClient.js
  spec/browserify/sync-browserify.spec.js
  spec/integ/matrix-client-opts.spec.js
  spec/integ/megolm-integ.spec.js
  spec/unit/ReEmitter.spec.ts
  spec/unit/autodiscovery.spec.js
  spec/unit/crypto.spec.js
  spec/unit/crypto/cross-signing.spec.js
  spec/unit/crypto/outgoing-room-key-requests.spec.js
  spec/unit/crypto/secrets.spec.js
  spec/unit/crypto/verification/InRoomChannel.spec.js
  spec/unit/crypto/verification/util.js
  src/autodiscovery.ts
  src/browser-index.js
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/OlmDevice.ts
  src/crypto/SecretStorage.ts
  src/crypto/aes.ts
  src/crypto/dehydration.ts
  src/crypto/olmlib.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/SAS.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/http-api.js
  src/index.ts
  src/models/MSC3089TreeSpace.ts
  src/models/group.js
  src/utils.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
  yarn.lock
Labels: T-Task

#2037 Improve fallback key behaviour
  package.json
  src/crypto/OlmDevice.ts
  src/crypto/index.ts
  src/sync.ts
Labels: T-Enhancement

#2060 Update Typescript to 4.5
  package.json
  yarn.lock
Labels: T-Task

#2062 Update olm to 3.2.8
  package.json
  yarn.lock
Labels: T-Task

#2059 Filter out falsey opts in /relations API hits
  spec/unit/utils.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/utils.ts
Labels: T-Defect

#2061 Iterate typing to work towards noImplicitAny
  spec/unit/models/MSC3089Branch.spec.ts
  src/@types/global.d.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/DeviceList.ts
  src/crypto/backup.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/verification/request/Channel.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/crypto/verification/request/ToDeviceChannel.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/models/MSC3089TreeSpace.ts
Labels: X-Blocked, T-Task

#2063 Convert http-api to Typescript
  package.json
  spec/integ/matrix-client-event-timeline.spec.js
  src/client.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/backup.ts
  src/crypto/dehydration.ts
  src/http-api.ts
  src/interactive-auth.ts
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
  src/models/room.ts
  src/scheduler.ts
  src/store/session/webstorage.js
  src/sync.ts
  yarn.lock
Labels: T-Task

#2069 Add git archive learnings to release script comment
  release.sh
Labels: T-Task

#2070 Fix sending `undefined` query args to Synapse
  src/client.ts
Labels: T-Task

#2067 Move Room properties JSDoc into more usable comments on actual props
  src/models/room.ts
Labels: T-Task

#2022 Use v1 prefix for /hierarchy API, falling back to both previous variants
  src/@types/spaces.ts
  src/client.ts
  src/http-api.ts
  src/room-hierarchy.ts
Labels: T-Task

#2073 Copy the polls constants to matrix-js-sdk from matrix-react-sdk
  src/@types/polls.ts
Labels: T-Task

#2074 Add consts for location and extensible events types
  src/@types/extensible_events.ts
  src/@types/location.ts
  src/@types/polls.ts
Labels: T-Task

#2076 Provide a makeLocationContent to create a location content event
  src/@types/location.ts
  src/content-helpers.ts
Labels: T-Task

#2078 Remove now-unused makePollContent from its old location
  src/@types/polls.ts
Labels: T-Task

#2077 Iterate typing around sync, usage limits and errors
  src/@types/partials.ts
  src/client.ts
  src/http-api.ts
  src/sync.api.ts
  src/sync.ts
Labels: T-Task

#2066 Load room history if necessary when searching for MSC3089 getFileEvent()
  src/models/MSC3089Branch.ts
Labels: T-Enhancement

#2080 Stop using v1-prefixed /hierarchy API due to Synapse bugs
  src/client.ts
Labels: X-Release-Blocker, T-Task

#2082 Fix incorrect TS return type for secret storage and key backup functions
  src/client.ts
  src/crypto/SecretStorage.ts
  src/crypto/index.ts
Labels: T-Defect

#2090 Set a `deviceId` for VoIP example and use `const`/`let`
  examples/voip/browserTest.js
Labels: T-Defect

#2085 Fix timeline search in MSC3089 getFileEvent()
  src/models/MSC3089Branch.ts
Labels: T-Defect

#2086 Fix more function typings relating to key backup
  src/client.ts
Labels: T-Defect
