Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-01, with the labels that each got.

#2096 Fix spacing errors
  package.json
  src/crypto/algorithms/megolm.ts
  src/store/indexeddb-local-backend.ts
  yarn.lock
Labels: T-Task

#2098 Stop encrypting redactions as it isn't spec compliant
  spec/unit/matrix-client.spec.js
  src/client.ts
  src/models/event.ts
Labels: T-Defect

#2094 Don't consider alt_aliases when calculating room name
  spec/unit/room.spec.js
  src/models/room.ts
Labels: T-Enhancement

#2095 Support cancelling events whilst they are in status = ENCRYPTING
  spec/test-utils.js
  spec/unit/matrix-client.spec.js
  src/client.ts
  src/crypto/index.ts
  src/models/room.ts
Labels: T-Enhancement

#2101 Yarn upgrade
  yarn.lock
Labels: T-Task

#2091 Send extensible events structure and support on-demand parsing
  package.json
  spec/integ/matrix-client-crypto.spec.js
  spec/unit/room-state.spec.js
  src/client.ts
  src/models/event.ts
  yarn.lock
Labels: T-Enhancement

#2105 Keep unknown fields when adding extensible formats
  src/client.ts
Labels: T-Task

#2104 Don't remove streams that still have tracks
  src/webrtc/call.ts
Labels: T-Defect

#2102 Move polls to events-sdk, and invent a RelatedRelations type
  package.json
  src/@types/polls.ts
  src/content-helpers.ts
  src/models/related-relations.ts
  yarn.lock
Labels: T-Task

#2107 Revert "Remove getCapabilities call for guest users (#2100)"
  spec/unit/matrix-client.spec.js
  src/client.ts
Labels: T-Defect

#2109 Support m.asset in m.location event content
  spec/unit/location.spec.ts
  src/@types/location.ts
  src/content-helpers.ts
Labels: T-Enhancement

#2110 Add eslint camelcase ignores & remove unnecessary casts
  src/client.ts
Labels: T-Task

#2131 Improve typing for Room.timeline data parameter
  src/models/event-timeline-set.ts
Labels: T-Task

#2134 Fix http-api butchering idServer requests
  src/http-api.ts
Labels: T-Defect, X-Release-Blocker

#2143 Don't decrypt redacted messages
  src/models/event.ts
Labels: T-Defect

#2145 Bump node-fetch from 2.6.6 to 2.6.7 (#2140)
  yarn.lock
Labels: T-Task

#2146 Yarn upgrade
  yarn.lock
Labels: T-Task
