Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-04, with the labels that each got.

#2270 Fix getSessionsNeedingBackup() limit support
  src/crypto/store/localStorage-crypto-store.ts
Labels: T-Defect

#2269 Live location sharing - handle redacted beacons
  spec/unit/models/beacon.spec.ts
  spec/unit/room-state.spec.js
  src/models/beacon.ts
  src/models/room-state.ts
  src/sync.ts
Labels: T-Enhancement

#2281 Live location sharing - update beacon_info implementation to latest MSC
  spec/test-utils/beacon.ts
  spec/unit/content-helpers.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/beacon.spec.ts
  spec/unit/room-state.spec.js
  src/@types/beacon.ts
  src/client.ts
  src/content-helpers.ts
  src/models/beacon.ts
  src/models/room-state.ts
Labels: T-Task

#2268 Live location sharing - Aggregate beacon locations on beacons
  spec/unit/matrix-client.spec.ts
  spec/unit/models/beacon.spec.ts
  spec/unit/room-state.spec.js
  spec/unit/utils.spec.ts
  src/client.ts
  src/content-helpers.ts
  src/models/beacon.ts
  src/models/room-state.ts
  src/sync.ts
  src/utils.ts
Labels: T-Enhancement

#2181 Stabilise token authenticated registration support
  src/interactive-auth.ts
Labels: T-Enhancement

#2287 Ignore `eslint --fix` formatting changes in git blame
  .git-blame-ignore-revs
Labels: T-Task

#2285 Support for MSC2457 logout_devices param for setPassword()
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement

#2271 Change `_unstable_getSharedRooms` to `_unstable_getMutualRooms`
  src/client.ts
Labels: T-Task

#2294 Fix coverage diffs for PRs that aren't up to date, take 3
  .github/workflows/test_coverage.yml
Labels: T-Task

#2296 Live location sharing - expose room liveBeaconIds
  spec/unit/room-state.spec.js
  src/models/room-state.ts
Labels: T-Enhancement

#2297 Add MatrixClient.doesServerSupportLogoutDevices() for MSC2457
  src/client.ts
Labels: T-Enhancement

#2305 Update threads handling for replies-to-thread-responses as per MSC update
  spec/integ/matrix-client-methods.spec.js
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Defect

#2304 Upgrade dependencies
  src/crypto/verification/SAS.ts
  yarn.lock
Labels: T-Task

#2307 Move more stuff from BK to GHA
  .editorconfig
  .github/workflows/notify-downstream.yaml
  .github/workflows/pr_static_analysis.yml
  .github/workflows/preview_changelog.yaml
  .github/workflows/test_coverage.yml
Labels: T-Task

#2308 Prevent attempt to create thread with id "undefined"
  src/models/room.ts
Labels: T-Defect

#2311 Add PTT call mode & mute by default in PTT calls
  src/client.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Enhancement

#2316 Make the tests pass again
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2315 fix example in readme
  README.md
Labels: T-Defect

#2312 Add maximum trasmit time for PTT
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2313 Don't allow user to unmute if another user is speaking
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2319 De-duplicate code and fix types
  spec/unit/room.spec.ts
  src/client.ts
  src/models/room.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb.ts
  src/store/memory.ts
  src/store/stub.ts
Labels: T-Task

#2306 Ignore m.replace relations on state events, they're invalid
  spec/unit/relations.spec.ts
  src/models/event.ts
Labels: T-Defect, X-Blocked

#2325 Fix createGroupCall arguments
  src/client.ts
Labels: T-Defect

#2327 Live location sharing: handle encrypted messages in processBeaconEvents
  spec/unit/matrix-client.spec.ts
  spec/unit/room-state.spec.js
  src/client.ts
  src/models/room-state.ts
Labels: T-Enhancement

#2324 Correctly specify minimum Node version
  README.md
  package.json
Labels: T-Task

#2330 Try SonarCloud
  .github/workflows/static_analysis.yml
  sonar-project.properties
Labels: T-Task
