Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-02, with the labels that each got.

#2036 Type annotation: MatrixEvent.getRoomId can return undefined
  src/models/event.ts
Labels: T-Task

#2150 Fix initial sync fail when event fetching unsuccessful
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2151 Avoid re-doing as much work when processing m.receipt event
  src/models/room.ts
Labels: T-Task

#2156 Send references to thread root to threads, even out of order
  spec/integ/matrix-client-methods.spec.js
  src/client.ts
Labels: T-Defect

#2159 Account for encryption in `maySendMessage()`
  spec/unit/room.spec.js
  src/models/room.ts
Labels: T-Defect

#2160 Fix edge cases around RR calculations
  src/models/room.ts
Labels: T-Defect

#2157 Don't store streams that are only used once
  src/webrtc/call.ts
  src/webrtc/mediaHandler.ts
Labels: T-Defect, X-Release-Blocker

#2163 Fix issue with rooms not getting marked as unread
  src/models/room.ts
Labels: T-Defect, X-Release-Blocker

#2164 Yarn upgrade
  yarn.lock
Labels: T-Task

#2158 Back up keys before logging out
  src/client.ts
  src/crypto/backup.ts
Labels: T-Defect

#2167 Check the backup info against the stored private key when determining trust.
  src/crypto/backup.ts
Labels: T-Defect

#2169 Log when member event membership is undefined
  src/models/room-member.ts
Labels: T-Task

#2155 Fix error in uploadContent() when file is empty under Node.js
  src/http-api.ts
Labels: T-Defect

#2170 Sign backup with cross-signing key when we reset it.
  src/crypto/index.ts
Labels: T-Defect

#2175 Revert "Sign backup with cross-signing key when we reset it."
  src/crypto/index.ts
Labels: T-Defect

#2174 Fix synthetic read receipt handling
  spec/unit/room.spec.js
  src/models/room.ts
Labels: T-Defect

#2178 Add functions to support refresh tokens
  src/@types/auth.ts
  src/client.ts
  src/http-api.ts
Labels: T-Enhancement

#2182 Enable max-bundle
  src/webrtc/call.ts
Labels: T-Task

#2183 Fix synthetic read receipt handling
  spec/unit/room.spec.js
  src/models/room.ts
Labels: T-Defect

#2185 Fix incorrect type referenced in receiptCacheByEventId.
  src/models/room.ts
Labels: T-Task

#2187 Null-guard for undefined rootEvent when creating a thread
  src/models/room.ts
Labels: T-Task

#2186 Return send event response from MSC3089Branch.createNewVersion()
  src/models/MSC3089Branch.ts
Labels: T-Enhancement

#2188 Fix camera stuck on after call transfer
  src/webrtc/call.ts
Labels: T-Defect

#2189 Fix bug where calls could break if rejected from somewhere else
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#2184 Bump matrix-events-sdk to 0.0.1-beta.7
  package.json
  yarn.lock
Labels: T-Task

#2193 Fix bug with one-way audio after a transfer
  src/webrtc/call.ts
Labels: T-Defect

#2196 fix relation sender filter
  spec/test-utils.js
  spec/unit/filter-component.spec.js
  src/filter-component.ts
Labels: T-Defect

#2199 Generate a JSON coverage file when requested to generate coverage
  package.json
Labels: T-Task

#2192 Add new room state emit RoomStateEvent.Update for lower-frequency hits
  src/client.ts
  src/models/room-state.ts
  src/sync.ts
Labels: T-Enhancement

#2201 Fix bug with the /hierarchy API sending invalid requests
  src/client.ts
Labels: T-Defect

#2202 [Release] Fix bug with the /hierarchy API sending invalid requests
  src/client.ts
Labels: T-Defect, X-Release-Blocker

#2204 Stop using development /spaces API in favour of v1 /hierarchy API
  src/@types/spaces.ts
  src/client.ts
Labels: T-Task

#2206 Provide settings to control the comments codecov adds to PRs
  codecov.yml
Labels: T-Task

#2154 Support for mid-call devices changes
  spec/unit/webrtc/call.spec.ts
  src/client.ts
  src/webrtc/call.ts
  src/webrtc/mediaHandler.ts
Labels: T-Enhancement
