Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-08, with the labels that each got.

#2554 Delint group calls
  spec/unit/crypto/algorithms/megolm.spec.ts
Labels: T-Task

#2557 Use EventType enum values instead of hardcoded strings
  src/models/room.ts
Labels: T-Task

#2549 Retry to-device messages
  package.json
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/queueToDevice.spec.ts
  src/ToDeviceMessageQueue.ts
  src/client.ts
  src/crypto/algorithms/megolm.ts
  src/models/ToDeviceMessage.ts
  src/scheduler.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb-store-worker.ts
  src/store/indexeddb.ts
  src/store/memory.ts
  src/store/stub.ts
  yarn.lock
Labels: T-Enhancement

#2528 Add support for sending user-defined encrypted to-device messages
  package.json
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  yarn.lock
Labels: T-Enhancement

#2551 Remove stream-replacement
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
Labels: T-Enhancement

#2562 Always block sending keys to unverified devices of verified users
  spec/unit/crypto/algorithms/megolm.spec.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Enhancement

#2564 Fix output after test finished
  spec/unit/queueToDevice.spec.ts
Labels: T-Task

#2563 Merge changes from develop
  CHANGELOG.md
  package.json
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/queueToDevice.spec.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  src/ToDeviceMessageQueue.ts
  src/client.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  src/models/ToDeviceMessage.ts
  src/models/room.ts
  src/scheduler.ts
  src/sliding-sync.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb-store-worker.ts
  src/store/indexeddb.ts
  src/store/memory.ts
  src/store/stub.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
  yarn.lock
Labels: T-Task

#2565 Increase timeout to try & avoid flakiness in queueToDevice test
  spec/unit/queueToDevice.spec.ts
Labels: T-Task

#2566 Simplify encryptAndSendToDevices
  src/client.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
Labels: T-Task

#2524 Add support for stable prefixes for MSC2285
  spec/unit/room.spec.ts
  spec/unit/sync-accumulator.spec.ts
  spec/unit/utils.spec.ts
  src/@types/read_receipts.ts
  src/client.ts
  src/models/room.ts
  src/sync-accumulator.ts
  src/utils.ts
Labels: T-Enhancement

#2569 Don't load the sync accumulator if there's already a sync persist in flight
  src/store/indexeddb-local-backend.ts
Labels: T-Defect

#2571 Revert "Always block sending keys to unverified devices of verified users (#2562)"
  spec/unit/crypto/algorithms/megolm.spec.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Task

#2573 Document where new linting rules go
  .eslintrc.js
Labels: Z-Community-PR, T-Task

#2576 Fix return types of event sending functions
  src/webrtc/call.ts
Labels: T-Task

#2575 Add basic creation / entering tests for group calls
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2473 Support nested Matrix clients via the widget API
  package.json
  spec/unit/embedded.spec.ts
  src/ToDeviceMessageQueue.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/SecretStorage.ts
  src/crypto/index.ts
  src/embedded.ts
  src/matrix.ts
  src/models/beacon.ts
  src/models/thread.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
  src/utils.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/groupCallEventHandler.ts
  yarn.lock
Labels: T-Enhancement

#2577 Make jsdoc generation gha regex more strict
  .github/workflows/jsdoc.yml
Labels: T-Task

#2580 Set up basic Backporting action
  .github/workflows/backport.yml
Labels: T-Task

#2582 Tweak backport
  .github/workflows/backport.yml
Labels: T-Task

#2567 Add txn_id support to sliding sync
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Enhancement

#2584 Tidy up imports
  src/webrtc/groupCall.ts
Labels: T-Task

#2583 sliding sync bugfix: ensure history is treated as history and not live events
  spec/integ/sliding-sync-sdk.spec.ts
  src/sliding-sync-sdk.ts
Labels: T-Defect

#2585 Fix finding event read up to if stable private read receipts is missing
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#2574 Improve test coverage and modernize style for interactive-auth
  spec/unit/autodiscovery.spec.ts
  spec/unit/interactive-auth.spec.ts
  src/autodiscovery.ts
  src/interactive-auth.ts
  src/pushprocessor.ts
  src/utils.ts
  src/webrtc/call.ts
Labels: Z-Community-PR, T-Task

#2591 Fix: Handle parsing of a beacon info event without asset
  spec/unit/models/beacon.spec.ts
  src/content-helpers.ts
  src/models/beacon.ts
Labels: T-Defect, backport staging

#2590 Add group call tests for muting
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#2595 Remove duplicate log of answering a call
  src/webrtc/call.ts
Labels: T-Task

#2596 Add test for updateLocalUsermediaStream
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2597 Add tests for incoming calls in group calls
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2599 Test muting in PTT mode
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2598 Add screensharing tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#2603 Update lockfile
  yarn.lock
Labels: T-Task

#2606 Add unit tests for hangup / reject
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  src/webrtc/call.ts
Labels: T-Task

#2609 Add ability to override built in room name generator for an i18n'able one
  spec/unit/room.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Enhancement

#2607 Re-emit room state events on rooms
  .eslintrc.js
  src/ReEmitter.ts
  src/models/room.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Enhancement

#2611 Test call timeouts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2612 Add tags and not_tags to the list of valid sliding sync filters
  src/sliding-sync.ts
Labels: T-Task

#2610 sliding sync: handle lone DELETE and INSERT operations
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Defect

#2615 Add static analysis for tsc --strict
  .github/workflows/static_analysis.yml
  src/utils.ts
  tsconfig.json
Labels: T-Task

#2613 Fix room membership race with PREPARED event
  src/sliding-sync-sdk.ts
Labels: T-Defect, Z-Community-PR

#2587 Refactor Sync and fix `initialSyncLimit`
  spec/integ/matrix-client-syncing.spec.ts
  spec/test-utils/test-utils.ts
  src/client.ts
  src/sync.ts
Labels: T-Defect

#2617 1:1 screenshare tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  src/webrtc/call.ts
Labels: T-Task

#2620 Tweak tsc-strict config
  .github/workflows/static_analysis.yml
Labels: T-Task

#2623 Use deep equality comparisons when searching for outgoing key requests by target
  spec/unit/crypto/outgoing-room-key-requests.spec.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/memory-crypto-store.ts
Labels: T-Defect

#2627 Add types to the call unit test suites
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2629 Add logging to diagnose connection issue
  src/webrtc/groupCall.ts
Labels: T-Task
