Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-06, with the labels that each got.

#2373 Try to load keys from key backup when a message fails to decrypt
  spec/TestClient.js
  spec/TestClient.ts
  spec/integ/matrix-client-crypto.spec.js
  spec/integ/matrix-client-retrying.spec.ts
  spec/integ/megolm-backup.spec.ts
  spec/unit/webrtc/callEventHandler.spec.ts
  src/client.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/backup.ts
  src/crypto/keybackup.ts
Labels: T-Enhancement

#2426 Fix test suite regression due to TestClient refactoring
  spec/integ/devicelist-integ.spec.js
Labels: T-Task

#2299 Timeline needs to refresh when we see a MSC2716 marker event
  spec/integ/matrix-client-event-timeline.spec.js
  spec/integ/matrix-client-room-timeline.spec.js
  spec/integ/matrix-client-syncing.spec.js
  spec/unit/event-timeline-set.spec.ts
  spec/unit/event-timeline.spec.js
  spec/unit/room-state.spec.js
  spec/unit/room.spec.ts
  spec/unit/timeline-window.spec.js
  src/@types/event.ts
  src/client.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/room-state.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync.ts
Labels: T-Enhancement

#2429 Update MSC3786 implementation: Check the `state_key`
  spec/unit/pushprocessor.spec.js
  src/pushprocessor.ts
Labels: T-Enhancement

#2416 matrix-mock-request to 2.0.1
  package.json
  spec/TestClient.ts
  spec/unit/crypto/secrets.spec.js
  spec/unit/crypto/verification/request.spec.js
  spec/unit/crypto/verification/sas.spec.js
  spec/unit/crypto/verification/util.js
  src/client.ts
  yarn.lock
Labels: T-Task

#2431 The request callback provided by bootstrapCrossSigning is async
  src/crypto/index.ts
Labels: T-Task

#2425 Move pr_details and sonarqube to released composite actions
  .github/workflows/pr_details.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
Labels: T-Task

#2436 Document how to inhibit code coverage requirement
  CONTRIBUTING.md
Labels: T-Task

#2136 Assume per-user deviceID uniqueness in encryptAndSendKeysToDevices
  src/crypto/algorithms/megolm.ts
Labels: T-Defect, Z-Community-PR

#2435 Add tests for sendEvent threadId handling
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/content-helpers.ts
Labels: T-Defect

#2412 Refactor Relations to not be per-EventTimelineSet
  spec/unit/event-timeline-set.spec.ts
  spec/unit/relations.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/relations-container.ts
  src/models/relations.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync.ts
Labels: T-Defect

#2440 Test typescriptification - crypto unit tests pt 1
  spec/unit/crypto/DeviceList.spec.ts
  spec/unit/crypto/outgoing-room-key-requests.spec.ts
  spec/unit/crypto/secrets.spec.ts
Labels: T-Task

#2439 Add CI to improve experience for community
  .github/workflows/pull_request.yaml
Labels: T-Task

#2442 Pass missing ci secret
  .github/workflows/pull_request.yaml
Labels: T-Task

#2445 Set PTT mode on call correctly
  src/webrtc/groupCall.ts
Labels: T-Defect

#2447 Emit unknown device errors for group call participants without e2e
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2450 Only clone streams on Safari
  src/webrtc/groupCall.ts
Labels: T-Defect

#2452 Update sonarcloud-workflow-action to fix projectVersion not being passed properly
  .github/workflows/sonarcloud.yml
Labels: T-Task

#2137 Various changes to `src/crypto` files for correctness
  spec/unit/crypto.spec.js
  spec/unit/crypto/algorithms/megolm.spec.js
  src/crypto/algorithms/base.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
Labels: T-Enhancement, Z-Community-PR

#2462 Clearly indicate that `lastReply` on a Thread can return falsy
  src/models/thread.ts
Labels: T-Defect

#2463 Add missing `type` property on `IAuthData`
  src/interactive-auth.ts
Labels: T-Defect

#2464 Log real errors and not just their messages, traces are useful
  src/crypto/index.ts
  src/store/indexeddb-store-worker.ts
Labels: T-Enhancement

#2454 Fix issue with `getEventTimeline` returning undefined for thread roots in main timeline
  spec/integ/matrix-client-event-timeline.spec.js
  spec/test-utils/test-utils.ts
  spec/unit/event-timeline-set.spec.ts
  spec/unit/filter-component.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
Labels: T-Defect, X-Release-Blocker

#2465 Live location share - add start time leniency (PSF-1081)
  spec/test-utils/beacon.ts
  spec/unit/models/beacon.spec.ts
  src/models/beacon.ts
Labels: T-Enhancement

#2446 Expire call member state events after 1 hour
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2466 Don't ignore call member events with a distant future expiration date
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2461 Don't block muting on determining whether the device exists
  src/webrtc/groupCall.ts
Labels: T-Defect

#2467 expose latestLocationEvent on beacon model (PSF-1044)
  spec/unit/models/beacon.spec.ts
  src/models/beacon.ts
Labels: T-Enhancement

#2469 Implement MSC3827: Filtering of `/publicRooms` by room type
  src/@types/requests.ts
Labels: T-Enhancement

#2471 Send call version `1` as a string
  src/webrtc/call.ts
Labels: T-Defect

#2480 Fix call.collectCallStats()
  src/webrtc/call.ts
Labels: T-Defect

#2481 Go back to forEach in collectcallstats
  src/webrtc/call.ts
Labels: T-Task

#2479 Remove the feature to disable audio from muted members
  src/webrtc/call.ts
Labels: T-Task

#2482 Enable DTX on audio tracks in calls
  package.json
  src/webrtc/call.ts
  yarn.lock
Labels: T-Enhancement

#2474 Export KNOWN_SAFE_ROOM_VERSION
  src/models/room.ts
Labels: T-Enhancement
