Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-05, with the labels that each got.

#2336 Apply corrections identified by SonarQube
  src/autodiscovery.ts
  src/client.ts
  src/crypto/DeviceList.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/http-api.ts
  src/store/indexeddb-local-backend.ts
  src/utils.ts
Labels: T-Task

#2334 Switch coverage to SonarQube
  .github/codecov.yml
  .github/workflows/sonarqube.yml
  .github/workflows/static_analysis.yml
  .github/workflows/tests.yml
  package.json
  sonar-project.properties
  yarn.lock
Labels: T-Task

#2337 Add CI to require labels on PRs for better changelog management
  .github/workflows/preview_changelog.yaml
  .github/workflows/pull_request.yaml
Labels: T-Task

#2338 Support for PTT group call mode
  spec/unit/webrtc/call.spec.ts
  src/client.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Enhancement

#2331 Fix race conditions around threads
  spec/unit/matrix-client.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2335 Add README badges
  README.md
Labels: T-Task

#2341 Create manual action for upgrading dependencies after rc cut
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#2340 Apply suggestions from SonarQube
  spec/browserify/sync-browserify.spec.js
  src/autodiscovery.ts
  src/client.ts
  src/crypto/OlmDevice.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/SecretStorage.ts
  src/crypto/aes.ts
  src/crypto/algorithms/olm.ts
  src/crypto/backup.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/crypto/key_passphrase.ts
  src/crypto/verification/SAS.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/http-api.ts
  src/matrix.ts
  src/pushprocessor.ts
  src/utils.ts
  src/webrtc/call.ts
Labels: T-Task

#2343 Update upgrade_dependencies.yml
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#2348 Tweak sonar-project.properties
  sonar-project.properties
Labels: T-Task

#2347 Another SonarQube happiness pass
  src/client.ts
  src/crypto/DeviceList.ts
  src/crypto/verification/SAS.ts
  src/matrix.ts
  src/models/event-timeline-set.ts
  src/models/room-state.ts
  src/models/room.ts
  src/store/index.ts
  src/store/stub.ts
Labels: T-Task

#2346 Prune both clear & wire content on redaction
  spec/unit/models/event.spec.ts
  src/models/event.ts
Labels: T-Defect

#2350 Remove hacky custom status feature
  src/client.ts
  src/models/user.ts
  src/sync.ts
Labels: T-Enhancement

#2221 Implement changes to MSC2285 (private read receipts)
  spec/unit/matrix-client.spec.ts
  spec/unit/room.spec.ts
  spec/unit/sync-accumulator.spec.js
  src/@types/read_receipts.ts
  src/client.ts
  src/models/room.ts
  src/sync-accumulator.ts
Labels: T-Enhancement, X-Breaking-Change

#2352 Improve typing
  src/@types/global.d.ts
  src/client.ts
  src/crypto/DeviceList.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/index.ts
  src/crypto/recoverykey.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/index.ts
  src/models/beacon.ts
  src/store/index.ts
  src/sync.ts
  src/utils.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
Labels: T-Task

#2354 Remove spec v1.3 check for threads
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Task

#2356 Pass more args to Sonar
  .github/workflows/sonarqube.yml
  sonar-project.properties
Labels: T-Task

#2358 Pass more args to Sonar
  .github/workflows/sonarqube.yml
Labels: T-Task

#2360 Remove unused checkKey param on isSecretStored
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/SecretStorage.ts
  src/crypto/index.ts
Labels: T-Task

#2357 registration: add function to re-request email token
  spec/unit/interactive-auth.spec.js
  src/interactive-auth.ts
Labels: T-Enhancement

#2359 Tweaks for sonar to correctly report on forked PRs
  .github/workflows/sonarqube.yml
Labels: T-Task

#2363 Fix up more types & Sonar warnings
  spec/integ/matrix-client-event-timeline.spec.js
  spec/unit/webrtc/callEventHandler.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/crypto/DeviceList.ts
  src/crypto/index.ts
  src/models/event.ts
  src/sync-accumulator.ts
  src/sync.ts
  src/webrtc/callEventHandler.ts
Labels: T-Task

#2368 Make pull_request.yaml between the layers consistent and fix enforce labels
  .github/workflows/pull_request.yaml
Labels: T-Task

#2367 Add stopClient parameter to MatrixClient::logout
  src/client.ts
Labels: T-Enhancement

#2366 More sonar tweaks and typing improvements
  spec/integ/matrix-client-methods.spec.js
  spec/unit/webrtc/call.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/crypto/backup.ts
  src/http-api.ts
  src/store/memory.ts
  src/webrtc/call.ts
Labels: T-Task

#2370 Fix races when muting/unmuting
  src/webrtc/groupCall.ts
Labels: T-Defect

#2364 Attempt to re-structure workflows to be more generic & reusable
  .github/workflows/notify-downstream.yaml
  .github/workflows/pr_details.yml
  .github/workflows/pull_request.yaml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
  .github/workflows/static_analysis.yml
  .github/workflows/tests.yml
Labels: T-Task

#2371 Fix GHA trigger downstream projects
  .github/workflows/notify-downstream.yaml
Labels: T-Task

#2369 Tweak thread creation & event adding to fix bugs around relations
  spec/unit/room.spec.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2272 Add support for HTML renderings of room topics
  spec/unit/content-helpers.spec.ts
  spec/unit/matrix-client.spec.ts
  src/@types/topic.ts
  src/client.ts
  src/content-helpers.ts
Labels: T-Enhancement

#2376 Remove default push rule override for MSC1930
  src/pushprocessor.ts
Labels: T-Defect

#2375 Add a catastrophic throw to thread constructor
  spec/unit/models/thread.spec.ts
  src/models/thread.ts
Labels: T-Task

#2378 Sonarcloud check out upstream develop not fork develop
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
Labels: T-Task

#2379 Revert "Sonarcloud check out upstream develop not fork develop"
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
Labels: T-Task

#2380 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: T-Task

#2374 Ensure rooms are recalculated on re-invites
  spec/integ/matrix-client-syncing.spec.js
  src/sync.ts
Labels: T-Defect

#2322 Add support for sending encrypted to-device events with OLM
  src/crypto/index.ts
  src/webrtc/call.ts
Labels: T-Enhancement

#2385 Catch promise errors in degradable (fixes #2384)
  src/store/indexeddb.ts
Labels: T-Defect, X-Release-Blocker

#2383 Handle other members having no e2e keys
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Defect

#2388 [Release] Catch promise errors in degradable
  src/store/indexeddb.ts
Labels: T-Defect

#2389 Fix behaviour of isRelation with relation m.replace for state events
  spec/unit/relations.spec.ts
  src/models/event.ts
  src/models/relations.ts
Labels: T-Defect

#2390 improve types for registration calls
  src/client.ts
  src/interactive-auth.ts
Labels: T-Task

#2392 Prevent overlapping sync accumulator persists
  src/store/indexeddb-local-backend.ts
Labels: T-Defect

#2395 Remove `dont_notify` from the `.m.rule.room.server_acl` rule
  src/pushprocessor.ts
Labels: T-Task

#2250 Don't cancel SAS verifications if `ready` is received after `start`
  src/crypto/verification/request/VerificationRequest.ts
  src/webrtc/callEventHandler.ts
Labels: T-Defect

#2397 Improve PR Details job to use github-script and output labels
  .github/workflows/pr_details.yml
  .github/workflows/sonarqube.yml
Labels: T-Task

#2400 Fix degraded mode for the IDBStore and test it
  spec/unit/stores/indexeddb.spec.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb.ts
Labels: T-Defect

#2382 Initial attempt at automating jsdoc
  .github/workflows/jsdoc.yml
  release.sh
Labels: T-Task

#2402 Convert `getLocalAliases` to a stable API call
  .eslintrc.js
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/http-api.ts
Labels: T-Enhancement

#2403 Remove unused file
  .istanbul.yml
Labels: T-Task

#2404 Fix gha concurrency conditions
  .github/workflows/pull_request.yaml
Labels: T-Task

#2401 Wait for mute event to send in PTT mode
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Defect

#2394 Fix sonarqube using base branch on fork for detecting new code in pr
  .github/workflows/sonarcloud.yml
Labels: T-Task

#2411 Update sonarcloud.yml
  .github/workflows/sonarcloud.yml
Labels: T-Task

#2420 Revert "Github Actions pull_request synchronize runs on PR open anyway"
  .github/workflows/pull_request.yaml
Labels: T-Task

#2422 Revert "Fix request, crypto, and bs58 imports"
  src/crypto/recoverykey.ts
  src/index.ts
  src/utils.ts
Labels: T-Task

#2419 Update renovate.json
  renovate.json
Labels: T-Task

#2421 Mute disconnected peers in PTT mode
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement
