Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-09, with the labels that each got.

#2621 Link contributing guide to Element Web
  CONTRIBUTING.md
Labels: T-Task

#2631 Add GroupCallEventHandlerEvent.Room
  src/client.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Defect

#2632 Wait for client to start syncing before making group calls
  src/webrtc/groupCallEventHandler.ts
Labels: T-Defect

#2586 utils: Fix bug in deepCompare which would incorrectly return objects with disjoint keys as equal
  spec/unit/matrix-client.spec.ts
  spec/unit/utils.spec.ts
  src/sync.ts
  src/utils.ts
Labels: T-Defect, Z-Community-PR

#2634 Test disabling screenshare in group calls
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2636 Refactor the group call placing calls test
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2637 Test that calls in a group call are retried
  spec/test-utils/flushPromises.ts
  spec/test-utils/webrtc.ts
  spec/unit/queueToDevice.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2638 Test call mute status set on call state chnage
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2616 Simplify releases: move npm publishing to gha, consolidate scripts
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  post-release.sh
  release.sh
Labels: T-Task

#2642 Fix release script for layers without a release_config.yaml file
  release.sh
Labels: T-Task

#2639 Fix handling of remote echoes doubling up
  spec/unit/event-timeline-set.spec.ts
  spec/unit/room.spec.ts
  src/models/event-timeline-set.ts
  src/models/room.ts
Labels: T-Defect

#2641 Add client.waitUntilRoomReadyForGroupCalls()
  src/client.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Defect

#2643 Log ID instead of object
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#2626 Base support for MSC3847: Ignore invites with policy rooms
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/models/invites-ignorer.ts
  src/utils.ts
Labels: T-Enhancement

#2628 sliding sync: add invited|joined_count
  spec/integ/sliding-sync-sdk.spec.ts
  src/sliding-sync-sdk.ts
  src/sliding-sync.ts
Labels: T-Enhancement

#2652 Tweak backport labels
  .github/workflows/backport.yml
Labels: T-Task

#2646 MediaHandler Tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/mediaHandler.spec.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#2655 Fix import locations
  src/models/invites-ignorer.ts
Labels: T-Task

#2654 GroupCallEventhandler Tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#2656 Add a property aggregating all names of a NamespacedValue
  spec/unit/NamespacedValue.spec.ts
  src/NamespacedValue.ts
Labels: T-Enhancement

#2658 Test active speaker events
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2659 Test fallback screensharing
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2633 Add login flow types from matrix-react-sdk
  src/@types/auth.ts
  src/client.ts
Labels: T-Task

#2398 Implementation of MSC3824 to add action= param on SSO login
  spec/unit/login.spec.ts
  src/@types/auth.ts
  src/client.ts
Labels: T-Enhancement

#2660 Add test for removing RTX codec
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2661 Revert "Add login flow types from matrix-react-sdk (#2633)"
  src/client.ts
Labels: X-Release-Blocker, T-Task

#2624 Remove support for unstable private read receipts
  spec/unit/room.spec.ts
  spec/unit/sync-accumulator.spec.ts
  spec/unit/utils.spec.ts
  src/@types/read_receipts.ts
  src/client.ts
  src/models/room.ts
  src/utils.ts
Labels: T-Task

#2662 Fix race in creating calls
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Defect

#2667 Prevent exception when muting
  src/webrtc/groupCall.ts
Labels: T-Defect

#2665 Have setup-node set up the npmrc for NODE_AUTH_TOKEN
  .github/workflows/release-npm.yml
Labels: X-Release-Blocker, T-Task

#2664 Fix reset_dependency for if the dep is indirect
  release.sh
Labels: X-Release-Blocker, T-Task

#2630 Change return type to avoid null strict error
  src/client.ts
  src/models/event-timeline.ts
  src/models/thread.ts
Labels: T-Task

#2666 Add tests for call answering / candidate sending
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2671 Add commit status for the sonarcloud workflow run
  .github/workflows/sonarcloud.yml
Labels: T-Task

#2674 Add tests for ice candidate sending
  spec/unit/webrtc/call.spec.ts
Labels: T-Defect

#2673 test typescriptification - spec/unit/crypto/verification
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/InRoomChannel.spec.ts
  spec/unit/crypto/verification/qr_code.spec.ts
  spec/unit/crypto/verification/request.spec.ts
  spec/unit/crypto/verification/util.ts
Labels: T-Task

#2670 Target widget actions at a specific room
  spec/unit/embedded.spec.ts
  src/embedded.ts
Labels: T-Defect

#2676 Upgrade matrix-widget-api (and fix the lockfile)
  package.json
  yarn.lock
Labels: T-Task

#2675 test typescriptification - last few unit test files
  spec/browserify/sync-browserify.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/crypto/verification/secret_request.spec.ts
  spec/unit/crypto/verification/verification_request.spec.ts
Labels: T-Task

#2678 Add a few new `GroupCall` tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2677 Add test for call transfers
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2635 Read receipts for threads
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/http-api.ts
  src/models/event-timeline-set.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync-accumulator.ts
  src/sync.ts
Labels: T-Enhancement

#2680 Fix backpagination at end logic being spec non-conforming
  spec/integ/matrix-client-event-timeline.spec.ts
  src/client.ts
Labels: T-Defect

#2686 Support to remotely toggle push notifications
  spec/integ/matrix-client-methods.spec.js
  spec/test-utils/test-utils.ts
  spec/unit/pusher.spec.ts
  src/@types/PushRules.ts
  src/@types/event.ts
  src/client.ts
Labels: T-Enhancement

#2688 Add unstable device_id field for MSC3881
  src/@types/event.ts
Labels: T-Task

#2679 Add a few group call event handler tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
Labels: T-Task

#2424 Typings for MSC2965 OIDC provider discovery
  src/client.ts
Labels: T-Enhancement

#2668 Refer to explicit Matrix spec versions instead of Latest
  src/@types/auth.ts
Labels: T-Task

#2687 Implementation of MSC3882 login token request
  spec/integ/matrix-client-methods.spec.js
  src/@types/auth.ts
  src/@types/uia.ts
  src/client.ts
Labels: T-Enhancement

#2690 Merge latest develop into group calls branch
  .github/workflows/sonarcloud.yml
  package.json
  spec/browserify/sync-browserify.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.js
  spec/test-utils/test-utils.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/InRoomChannel.spec.ts
  spec/unit/crypto/verification/qr_code.spec.ts
  spec/unit/crypto/verification/request.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/crypto/verification/secret_request.spec.ts
  spec/unit/crypto/verification/util.ts
  spec/unit/crypto/verification/verification_request.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/pusher.spec.ts
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/@types/PushRules.ts
  src/@types/event.ts
  src/client.ts
  src/http-api.ts
  src/models/event-timeline-set.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync-accumulator.ts
  src/sync.ts
  yarn.lock
Labels: T-Task

#2695 Merge changes from latest develop into group calls branch (attempt number 2)
  .github/workflows/sonarcloud.yml
  package.json
  spec/browserify/sync-browserify.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.js
  spec/test-utils/test-utils.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/InRoomChannel.spec.ts
  spec/unit/crypto/verification/qr_code.spec.ts
  spec/unit/crypto/verification/request.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/crypto/verification/secret_request.spec.ts
  spec/unit/crypto/verification/util.ts
  spec/unit/crypto/verification/verification_request.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/pusher.spec.ts
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/@types/PushRules.ts
  src/@types/auth.ts
  src/@types/event.ts
  src/@types/uia.ts
  src/client.ts
  src/http-api.ts
  src/models/event-timeline-set.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync-accumulator.ts
  src/sync.ts
  yarn.lock
Labels: T-Task

#2692 Add `MatrixClient` group call tests
  spec/unit/matrix-client.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2691 Typings for MSC3824
  src/@types/auth.ts
Labels: T-Task

#2698 Remove redundant rel_branch logic
  release.sh
Labels: T-Task

#2696 Add `CallEventHandler` tests
  spec/unit/webrtc/callEventHandler.spec.ts
Labels: T-Task

#2697 Add more `MatrixCall` tests
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#2700 Add local notification settings capability
  spec/unit/local_notifications.spec.ts
  src/@types/event.ts
  src/@types/local_notifications.ts
  src/client.ts
Labels: T-Enhancement

#2701 Account data can return undefined
  src/client.ts
  src/store/index.ts
Labels: T-Task

#2702 Fix ICE restarts
  src/webrtc/call.ts
Labels: T-Defect

#2703 Fix incorrect MSC3890 unstable prefix
  src/@types/event.ts
Labels: T-Task

#2705 Bump IDB crypto store version
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/models/beacon.spec.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
Labels: T-Defect, backport staging

#2710 Fix missing return when receiving an invitation without shared history
  spec/integ/matrix-client-syncing.spec.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
Labels: T-Defect, backport staging

#2712 Merge develop
  CHANGELOG.md
  package.json
  release.sh
  spec/integ/matrix-client-crypto.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/megolm-integ.spec.ts
  spec/unit/content-helpers.spec.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/local_notifications.spec.ts
  spec/unit/models/beacon.spec.ts
  src/@types/auth.ts
  src/@types/crypto.ts
  src/@types/event.ts
  src/@types/local_notifications.ts
  src/NamespacedValue.ts
  src/client.ts
  src/content-helpers.ts
  src/crypto/OlmDevice.ts
  src/crypto/SecretStorage.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
  src/crypto/verification/Base.ts
  src/event-mapper.ts
  src/models/beacon.ts
  src/models/event.ts
  src/store/index.ts
  src/sync.ts
Labels: T-Task

#2713 Calculate IndexedDB versions automatically to reduce repeated information and possibilities for error
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/store/indexeddb-local-backend.ts
Labels: T-Task

#2715 Fix issue in sync when crypto is not supported by client
  spec/integ/matrix-client-crypto.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  src/client.ts
  src/sync.ts
Labels: T-Defect, Z-Community-PR, backport staging

#2717 Fix release-npm.yml dist-tag npm token passing mechanism
  .github/workflows/release-npm.yml
Labels: T-Task

#2718 Fix IDB initial migration handling causing spurious lazy loading upgrade loops
  spec/unit/stores/indexeddb.spec.ts
  src/store/indexeddb-local-backend.ts
Labels: T-Defect, X-Release-Blocker
