Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-07, with the labels that each got.

#2485 Revert hack to only clone streams on safari
  src/webrtc/groupCall.ts
Labels: T-Task

#2486 Remove empty decryption listener
  src/webrtc/callEventHandler.ts
Labels: T-Task

#2488 Fix return type on funcs in matrixClient to be optionally null
  src/client.ts
Labels: Z-Community-PR, T-Task

#2487 Don't mute the remote side immediately in PTT calls
  src/webrtc/call.ts
Labels: T-Defect

#2490 Run the changelog action regardless of trigger phase
  .github/workflows/pull_request.yaml
Labels: T-Task

#2492 Add config option for e2e group call signalling
  src/client.ts
  src/webrtc/call.ts
Labels: T-Enhancement

#2495 Improve VoIP integrations testing
  spec/TestClient.ts
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  src/webrtc/call.ts
Labels: T-Task

#2504 Remove MSC3244 support
  src/client.ts
Labels: T-Deprecation

#2503 Actually store the identity server in the client when given as an option
  spec/integ/matrix-client-methods.spec.js
  src/client.ts
Labels: T-Defect

#2502 Prevent double mute status changed events
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
Labels: T-Defect

#2505 Properly re-insert room ID in bundled thread relation messages from sync
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/test-utils/test-utils.ts
  src/models/thread.ts
Labels: T-Defect

#2509 Remove `setNow` from `realtime-callbacks.ts`
  spec/unit/realtime-callbacks.spec.js
  src/realtime-callbacks.ts
Labels: T-Task

#2510 Remove dead code
  spec/unit/utils.spec.ts
  src/crypto/api.ts
  src/crypto/verification/Error.ts
  src/utils.ts
Labels: T-Task

#2500 Don't crash with undefined room in `processBeaconEvents()`
  src/client.ts
Labels: T-Defect

#2511 Add a basic PR checklist for all PRs
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#2508 Typescriptify crypto integration tests
  spec/TestClient.ts
  spec/integ/matrix-client-crypto.spec.js
  spec/integ/matrix-client-crypto.spec.ts
Labels: T-Task

#2513 Merge develop into group call branch again
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull_request.yaml
  CHANGELOG.md
  package.json
  spec/TestClient.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.js
  spec/test-utils/test-utils.ts
  spec/test-utils/webrtc.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/crypto/crypto-utils.ts
  spec/unit/realtime-callbacks.spec.js
  spec/unit/utils.spec.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  src/client.ts
  src/crypto/api.ts
  src/crypto/verification/Error.ts
  src/models/room.ts
  src/models/thread.ts
  src/realtime-callbacks.ts
  src/utils.ts
  src/webrtc/call.ts
  yarn.lock
Labels: T-Task

#2520 Correct the units in TURN servers expiry documentation
  src/client.ts
Labels: T-Defect

#2514 Update release.sh to support a `staging` branch
  release.sh
Labels: T-Task

#2512 Remove unstable support for `m.room_key.withheld`
  spec/integ/megolm-integ.spec.js
  spec/unit/crypto/algorithms/megolm.spec.js
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
Labels: T-Deprecation

#2518 Typescriptify megolm integration tests
  spec/integ/megolm-integ.spec.ts
Labels: T-Task

#2519 Rewrite megolm integration tests with async arrow functions
  spec/integ/megolm-integ.spec.ts
  spec/test-utils/test-utils.ts
Labels: T-Task

#2531 Re-insert room IDs when decrypting bundled redaction events returned by `/sync`
  spec/integ/megolm-integ.spec.ts
  src/crypto/index.ts
Labels: T-Defect

#2525 Add local volume control
  src/webrtc/callFeed.ts
Labels: T-Task

#2527 Add missing events from reemitter to GroupCall
  src/webrtc/groupCall.ts
Labels: T-Defect

#2540 Require confirmation when doing proper release when intending to make an RC
  release.sh
Labels: T-Task

#2539 test typescriptification - timeline-window, scheduler, etc
  spec/unit/scheduler.spec.ts
  spec/unit/sync-accumulator.spec.ts
  spec/unit/timeline-window.spec.js
  spec/unit/timeline-window.spec.ts
  spec/unit/user.spec.ts
Labels: T-Task

#2538 test typescriptification: unit/crypto/algorithm specs
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/crypto/algorithms/olm.spec.ts
Labels: T-Task

#2537 Use stable prefixes for MSC3827
  src/@types/requests.ts
Labels: T-Enhancement

#2547 test typescriptification - misc
  spec/unit/content-repo.spec.ts
  spec/unit/event.spec.ts
  spec/unit/filter.spec.ts
  spec/unit/interactive-auth.spec.ts
  spec/unit/login.spec.ts
  spec/unit/pushprocessor.spec.ts
  spec/unit/realtime-callbacks.spec.ts
  src/content-repo.ts
Labels: T-Task

#2548 Use consolidated Renovate config
  .github/renovate.json
  renovate.json
Labels: T-Task

#2526 Make SDP munging media type specific
  src/webrtc/call.ts
Labels: T-Task

#2522 Prevent double mute status changed events
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
Labels: X-Breaking-Change, T-Task

#2530 Add support for audio sharing
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#2550 test typescriptification - autodiscovery / crypto specs
  spec/unit/autodiscovery.spec.ts
  spec/unit/content-repo.spec.ts
  spec/unit/crypto.spec.ts
  spec/unit/event-timeline.spec.ts
Labels: T-Task
