Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-03, with the labels that each got.

#2211 Throw error if both browser-index and (node) index are loaded
  src/browser-index.js
  src/client.ts
  src/index.ts
Labels: T-Task

#2213 Fix wrong event_id being sent for m.in_reply_to of threads
  src/client.ts
Labels: T-Defect

#2214 add LocationAssetType enum
  spec/unit/location.spec.ts
  src/@types/location.ts
  src/content-helpers.ts
Labels: T-Enhancement

#2216 Fix defer not supporting resolving with a Promise<T>
  src/utils.ts
Labels: T-Enhancement

#2217 Fix wrongly asserting that PushRule::conditions is non-null
  src/pushprocessor.ts
Labels: T-Defect

#2219 Add test coverage around push rules with no conditions
  spec/unit/pushprocessor.spec.js
Labels: T-Task

#2223 Add lint for unused locals
  src/client.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/http-api.ts
  tsconfig.json
Labels: T-Task

#2218 Update thread relation fields to match MSC3440 changes
  src/models/event.ts
Labels: T-Task

#2227 Fix incorrect usage of unstable variant of `is_falling_back`
  src/models/event.ts
  src/models/thread.ts
Labels: T-Defect

#2229 Location event helper functions
  spec/unit/location.spec.ts
  src/@types/location.ts
  src/content-helpers.ts
Labels: T-Task

#2232 Send and handle stable name for withheld codes
  spec/integ/megolm-integ.spec.js
  spec/unit/crypto/algorithms/megolm.spec.js
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
Labels: T-Task

#2236 Move test-utils into a directory
  spec/TestClient.js
  spec/browserify/sync-browserify.spec.js
  spec/integ/devicelist-integ-spec.js
  spec/integ/matrix-client-crypto.spec.js
  spec/integ/matrix-client-event-emitter.spec.js
  spec/integ/matrix-client-event-timeline.spec.js
  spec/integ/matrix-client-methods.spec.js
  spec/integ/matrix-client-opts.spec.js
  spec/integ/matrix-client-room-timeline.spec.js
  spec/integ/matrix-client-syncing.spec.js
  spec/integ/megolm-integ.spec.js
  spec/test-utils/test-utils.js
  spec/unit/crypto/algorithms/megolm.spec.js
  spec/unit/crypto/backup.spec.js
  spec/unit/crypto/cross-signing.spec.js
  spec/unit/event-timeline.spec.js
  spec/unit/filter-component.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/pushprocessor.spec.js
  spec/unit/room-member.spec.js
  spec/unit/room-state.spec.js
  spec/unit/room.spec.ts
  spec/unit/scheduler.spec.js
  spec/unit/timeline-window.spec.js
  spec/unit/user.spec.js
Labels: T-Task

#2238 Live location sharing - create m.beacon_info events
  spec/test-utils/beacon.ts
  spec/unit/models/beacon.spec.ts
  spec/unit/room-state.spec.js
  src/@types/beacon.ts
  src/client.ts
  src/content-helpers.ts
  src/models/beacon.ts
  src/models/room-state.ts
Labels: T-Enhancement

#2241 emit aggregate room beacon liveness
  spec/test-utils/emitter.ts
  spec/unit/models/beacon.spec.ts
  spec/unit/room-state.spec.js
  src/matrix.ts
  src/models/beacon.ts
  src/models/room-state.ts
Labels: T-Enhancement

#2243 fix missed types for event emitter
  src/client.ts
  src/models/beacon.ts
Labels: T-Task

#2245 reemit beacon events
  spec/unit/room-state.spec.js
  src/models/beacon.ts
  src/models/room-state.ts
  src/sync.ts
Labels: T-Task

#2251 Use beacon info event type as beacon identifier
  spec/test-utils/beacon.ts
  spec/unit/models/beacon.spec.ts
  spec/unit/room-state.spec.js
  src/models/beacon.ts
  src/models/room-state.ts
Labels: T-Task

#2249 Voice rooms prototype
  src/@types/event.ts
  src/models/room.ts
Labels: X-Blocked

#2234 Remove groups and groups-related APIs
  src/client.ts
  src/matrix.ts
  src/models/group.js
  src/store/index.ts
  src/store/indexeddb-local-backend.ts
  src/store/memory.ts
  src/store/stub.ts
  src/sync-accumulator.ts
  src/sync.ts
Labels: T-Enhancement, X-Blocked, X-Breaking-Change

#2258 Port codecov improvements matrix-react-sdk -> matrix-js-sdk
  .github/codecov.yml
  .github/workflows/test_coverage.yml
Labels: T-Task

#2260 Prevent exception 'Unable to set up secret storage'
  spec/unit/crypto.spec.js
  src/crypto/index.ts
Labels: T-Defect

#2261 Fix issues with /search and /context API handling for threads
  spec/integ/matrix-client-event-timeline.spec.js
  spec/integ/matrix-client-methods.spec.js
  src/client.ts
  src/models/event-context.ts
  src/models/room.ts
  src/models/search-result.ts
  src/models/thread.ts
  src/timeline-window.ts
Labels: T-Defect

#2263 Fix coverage diffs for PRs that aren't up to date
  .github/workflows/test_coverage.yml
Labels: T-Task
