Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-11, with the labels that each got.

#2832 [Backport staging] Catch server versions API call exception when starting the client
  spec/integ/matrix-client-syncing.spec.ts
  src/client.ts
Labels: T-Defect

#2833 Add eslint rule unicorn/no-instanceof-array
  package.json
  yarn.lock
Labels: T-Task

#2841 Fix queueToDevice.spec.ts test flakiness
  spec/unit/queueToDevice.spec.ts
Labels: T-Task

#2845 Update matrix-org/sonarcloud-workflow-action
  .github/workflows/sonarcloud.yml
Labels: T-Task

#2835 Make the js-sdk conform to tsc --strict
  package.json
  patches/matrix-events-sdk+0.0.1-beta.7.patch
  spec/integ/matrix-client-syncing.spec.ts
  spec/unit/event-timeline.spec.ts
  spec/unit/webrtc/call.spec.ts
  src/@types/PushRules.ts
  src/autodiscovery.ts
  src/client.ts
  src/content-helpers.ts
  src/crypto/backup.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/http-api/errors.ts
  src/interactive-auth.ts
  src/models/MSC3089Branch.ts
  src/models/beacon.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/event.ts
  src/models/invites-ignorer.ts
  src/models/room.ts
  src/models/thread.ts
  src/pushprocessor.ts
  src/webrtc/call.ts
  tsconfig.json
  yarn.lock
Labels: T-Enhancement

#2821 Add unit test for device de-/rehydration
  spec/unit/crypto/dehydration.spec.ts
Labels: T-Task

#2844 Don't remove our own member for a split second when entering a call
  src/webrtc/groupCall.ts
Labels: T-Defect

#2847 Remove tsc-strict ci, it has served its purpose
  .github/workflows/static_analysis.yml
Labels: T-Task

#2848 Extra insurance that we don't mix events in the wrong timelines
  .DS_Store
  spec/unit/event-timeline-set.spec.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/room.ts
Labels: T-Defect

#2853 Revert "Extra insurance that we don't mix events in the wrong timelines"
  spec/unit/event-timeline-set.spec.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/room.ts
Labels: T-Task

#2846 Do not freeze state in `initialiseState()`
  src/models/event-timeline.ts
Labels: T-Defect

#2854 Merge changes from develop
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
  .github/workflows/static_analysis.yml
  .gitignore
  package.json
  patches/matrix-events-sdk+0.0.1-beta.7.patch
  sonar-project.properties
  spec/integ/matrix-client-syncing.spec.ts
  spec/unit/crypto/dehydration.spec.ts
  spec/unit/event-timeline.spec.ts
  spec/unit/queueToDevice.spec.ts
  spec/unit/webrtc/call.spec.ts
  src/@types/PushRules.ts
  src/autodiscovery.ts
  src/client.ts
  src/content-helpers.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/http-api/errors.ts
  src/interactive-auth.ts
  src/models/MSC3089Branch.ts
  src/models/beacon.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/event.ts
  src/models/invites-ignorer.ts
  src/models/room.ts
  src/models/thread.ts
  src/pushprocessor.ts
  src/sliding-sync-sdk.ts
  src/webrtc/call.ts
  tsconfig.json
  yarn.lock
Labels: T-Task

#2855 Fix pagination token tracking for mixed room timelines
  spec/unit/event-timeline.spec.ts
  src/models/event-timeline.ts
Labels: T-Defect

#2850 Make SonarCloud happier
  src/@types/PushRules.ts
  src/client.ts
  src/crypto/DeviceList.ts
  src/crypto/OlmDevice.ts
  src/crypto/algorithms/olm.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
  src/filter-component.ts
  src/interactive-auth.ts
  src/models/event-timeline-set.ts
  src/models/room.ts
  src/models/user.ts
  src/pushprocessor.ts
  src/realtime-callbacks.ts
  src/rendezvous/MSC3906Rendezvous.ts
  src/store/indexeddb-local-backend.ts
  src/sync-accumulator.ts
  src/sync.ts
  src/utils.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callFeed.ts
Labels: T-Task

#2553 Add support for group calls using MSC3401
  .github/CODEOWNERS
  package.json
  spec/test-utils/flushPromises.ts
  spec/test-utils/webrtc.ts
  spec/unit/embedded.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/queueToDevice.spec.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callEventHandler.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
  spec/unit/webrtc/mediaHandler.spec.ts
  src/@types/event.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/SecretStorage.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  src/embedded.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
  src/matrix.ts
  src/models/beacon.ts
  src/models/read-receipt.ts
  src/models/thread.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
  src/webrtc/audioContext.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callEventTypes.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
  src/webrtc/mediaHandler.ts
  yarn.lock
Labels: T-Enhancement

#2856 Extra insurance that we don't mix events in the wrong timelines - v2
  spec/unit/event-timeline-set.spec.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/room.ts
Labels: T-Defect

#2860 Move patch-package out of dev dependencies
  package.json
Labels: T-Defect

#2843 Hide pending events in thread timelines
  spec/integ/matrix-client-event-timeline.spec.ts
  src/models/room.ts
Labels: T-Defect

#2434 webrtc: add advanced audio settings
  spec/unit/webrtc/mediaHandler.spec.ts
  src/webrtc/mediaHandler.ts
Labels: T-Enhancement

#2864 Add logging saying why we hung up calls
  src/webrtc/call.ts
Labels: T-Task

#2865 Log the call ID when receiving a call
  src/webrtc/groupCall.ts
Labels: T-Task

#2868 Upload docs artifact for PRs
  .github/workflows/docs-pr-netlify.yaml
  .github/workflows/static_analysis.yml
Labels: T-Task

#2862 Fixes unwanted highlight notifications with encrypted threads
  spec/test-utils/test-utils.ts
  spec/test-utils/thread.ts
  spec/unit/models/thread.spec.ts
  src/models/thread.ts
Labels: T-Defect

#2869 Switch to typedoc for documentation
  .github/workflows/release.yml
  .github/workflows/static_analysis.yml
  .gitignore
  README.md
  jsdoc.json
  package.json
  tsconfig.json
  yarn.lock
Labels: T-Task

#2834 sliding sync: add custom room subscriptions support
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Enhancement

#2871 Remove `Crypto.start()`
  spec/unit/crypto.spec.ts
  src/client.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/index.ts
Labels: T-Task

#2873 Use an underride rule for Element Call notifications
  src/pushprocessor.ts
Labels: T-Defect

#2877 Add way to abort search requests
  src/@types/search.ts
  src/client.ts
Labels: T-Enhancement

#2878 Add ability to send unthreaded receipt
  spec/unit/read-receipt.spec.ts
  src/client.ts
Labels: T-Enhancement

#2876 fix registration add phone number not working
  src/client.ts
Labels: T-Defect, Z-Community-PR

#2879 Improve logs for decrypting events
  src/crypto/olmlib.ts
  src/models/event.ts
Labels: T-Task

#2880 Make calls go back to 'connecting' state when media lost
  src/webrtc/call.ts
Labels: T-Enhancement

#2881 Read receipt accumulation for threads
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  spec/unit/sync-accumulator.spec.ts
  src/@types/read_receipts.ts
  src/client.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/sync-accumulator.ts
Labels: T-Defect

#2884 Improve logging of e2ee messages
  src/crypto/OlmDevice.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Enhancement

#2885 Improve logging on Olm session errors
  src/crypto/OlmDevice.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Enhancement

#2896 Add CI check with tsc --noImplicitAny
  .github/workflows/static_analysis.yml
Labels: T-Task

#2898 Don't hang up calls that haven't started yet
  src/webrtc/call.ts
Labels: T-Defect

#2893 sliding sync: add support for typing extension
  spec/integ/sliding-sync-sdk.spec.ts
  src/sliding-sync-sdk.ts
Labels: T-Enhancement

#2900 Further improvements to e2ee logging
  src/crypto/index.ts
Labels: T-Enhancement

#2897 Add jest metrics
  .github/workflows/tests.yml
  spec/slowReporter.js
Labels: T-Task

#2907 Fix 3pid invite acceptance not working due to mxid being sent in body
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Defect, X-Release-Blocker

#2904 Deprecate a function containing a typo
  src/models/event.ts
  src/scheduler.ts
Labels: T-Deprecation

#2910 Process `m.room.encryption` events before emitting `RoomMember` events
  spec/integ/megolm-integ.spec.ts
  spec/test-utils/test-utils.ts
  src/crypto/index.ts
  src/sync.ts
Labels: T-Defect

#2882 Define a spec support policy for the js-sdk
  README.md
Labels: T-Enhancement

#2913 Revert "Process `m.room.encryption` events before emitting `RoomMember` events"
  spec/integ/megolm-integ.spec.ts
  spec/test-utils/test-utils.ts
  src/crypto/index.ts
  src/sync.ts
Labels: T-Task

#2912 sliding sync: add receipts extension
  spec/integ/sliding-sync-sdk.spec.ts
  src/sliding-sync-sdk.ts
Labels: T-Enhancement

#2902 Refactor GroupCall participant management
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
  src/client.ts
  src/utils.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Enhancement, X-Breaking-Change

#2875 Implement a very basic focus selection algorithm
  src/client.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2917 Update @typescript-eslint/parser
  yarn.lock
Labels: T-Task

#2892 add-privileged-users-in-room
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Enhancement, Z-Community-PR

#2916 Fix synthesizeReceipt
  spec/unit/notifications.spec.ts
  spec/unit/read-receipt.spec.ts
  src/client.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2918 Update CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#2914 Process `m.room.encryption` events before emitting `RoomMember` events
  spec/integ/megolm-integ.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/crypto.spec.ts
  src/crypto/index.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Defect, X-Breaking-Change
