Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-10, with the labels that each got.

#2709 Rename redecryption-related function arguments for clarity
  src/crypto/algorithms/megolm.ts
  src/models/event.ts
Labels: T-Task

#2722 Check for the spec version when determining private read receipt support
  src/client.ts
Labels: T-Task

#2727 Add custom error message for restricted import
  .eslintrc.js
Labels: T-Task

#2724 Unexpected ignored self key request when it's not shared history
  src/crypto/algorithms/megolm.ts
Labels: T-Defect, Z-Community-PR

#2728 Device manager - `last_seen_user_agent` device property
  src/client.ts
Labels: T-Task

#2729 Use stable calls to `/room_keys`
  src/client.ts
  src/crypto/EncryptionSetup.ts
Labels: T-Enhancement

#2730 Use the correct sender key when checking shared secret
  src/crypto/SecretStorage.ts
Labels: T-Defect, backport staging

#2726 Add support for unread thread notifications
  package.json
  spec/integ/matrix-client-syncing.spec.ts
  spec/test-utils/client.ts
  spec/unit/filter.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/room.spec.ts
  spec/unit/sync-accumulator.spec.ts
  src/@types/sync.ts
  src/client.ts
  src/filter.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/sync-accumulator.ts
  src/sync.ts
  src/utils.ts
  yarn.lock
Labels: T-Enhancement

#2602 Load Thread List with server-side assistance (MSC3856)
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/room-state.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Enhancement

#2714 test typescriptification - spec/integ
  spec/browserify/setupTests.ts
  spec/integ/devicelist-integ.spec.ts
  spec/integ/matrix-client-crypto.spec.ts
  spec/integ/matrix-client-event-emitter.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-opts.spec.ts
  spec/integ/matrix-client-retrying.spec.ts
  spec/integ/matrix-client-room-timeline.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/megolm-backup.spec.ts
  spec/integ/megolm-integ.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/integ/sliding-sync.spec.ts
Labels: T-Task

#2720 Add custom notification handling for MSC3401 call events
  spec/test-utils/test-utils.ts
  spec/unit/pushprocessor.spec.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#2738 Update hidden characters regex
  src/utils.ts
Labels: T-Task

#2739 Fix sync init when thread unread notif is not supported
  spec/unit/feature.spec.ts
  spec/unit/filter.spec.ts
  src/@types/sync.ts
  src/client.ts
  src/feature.ts
  src/filter-component.ts
  src/filter.ts
  src/store/memory.ts
  src/sync.ts
Labels: T-Defect

#2741 Fix `power_level_content_override` type
  src/@types/requests.ts
Labels: T-Enhancement

#2744 Upgrade to Olm 3.2.13 which has been repackaged to support Node 18
  package.json
  yarn.lock
Labels: T-Enhancement

#2745 Correct the dir parameter of MSC3715
  spec/integ/matrix-client-relations.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/models/thread.ts
Labels: T-Defect, Z-Community-PR

#2719 Modernize http-api - move from `browser-request` to `fetch`
  README.md
  package.json
  spec/TestClient.ts
  spec/browserify/sync-browserify.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-opts.spec.ts
  spec/integ/matrix-client-room-timeline.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/setupTests.ts
  spec/unit/autodiscovery.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/crypto/cross-signing.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/event-mapper.spec.ts
  spec/unit/http-api/__snapshots__/index.spec.ts.snap
  spec/unit/http-api/fetch.spec.ts
  spec/unit/http-api/index.spec.ts
  spec/unit/http-api/utils.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/pusher.spec.ts
  spec/unit/queueToDevice.spec.ts
  spec/unit/read-receipt.spec.ts
  spec/unit/utils.spec.ts
  src/@types/global.d.ts
  src/@types/partials.ts
  src/@types/requests.ts
  src/ToDeviceMessageQueue.ts
  src/autodiscovery.ts
  src/browser-index.js
  src/client.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/dehydration.ts
  src/http-api.ts
  src/http-api/errors.ts
  src/http-api/fetch.ts
  src/http-api/index.ts
  src/http-api/interface.ts
  src/http-api/method.ts
  src/http-api/prefix.ts
  src/http-api/utils.ts
  src/index.ts
  src/matrix.ts
  src/models/MSC3089TreeSpace.ts
  src/scheduler.ts
  src/sliding-sync-sdk.ts
  src/sliding-sync.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb.ts
  src/sync.ts
  src/utils.ts
  src/webrtc/call.ts
  yarn.lock
Labels: T-Enhancement, X-Breaking-Change

#2746 Use even more stable calls to `/room_keys`
  src/client.ts
Labels: T-Enhancement

#2749 Improve MatrixError message
  spec/integ/matrix-client-methods.spec.ts
  src/http-api/errors.ts
  src/http-api/utils.ts
Labels: T-Task

#2748 Emit events when setting unread notifications
  spec/unit/notifications.spec.ts
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: X-Breaking-Change, T-Task

#2754 Don't block muting/unmuting on network requests
  src/webrtc/groupCall.ts
Labels: T-Defect

#2753 Always send back an httpStatus property if one is known
  spec/unit/http-api/utils.spec.ts
  spec/unit/interactive-auth.spec.ts
  src/http-api/errors.ts
  src/http-api/index.ts
  src/http-api/utils.ts
Labels: T-Defect

#2756 Make more of the code conform to Strict TSC
  spec/integ/matrix-client-event-emitter.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-room-timeline.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/unit/filter.spec.ts
  spec/unit/interactive-auth.spec.ts
  spec/unit/models/event.spec.ts
  spec/unit/room-member.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/room.spec.ts
  spec/unit/stores/indexeddb.spec.ts
  src/client.ts
  src/content-repo.ts
  src/filter.ts
  src/http-api/index.ts
  src/models/event-context.ts
  src/models/event-timeline-set.ts
  src/models/event.ts
  src/models/relations.ts
  src/models/room-member.ts
  src/models/room-state.ts
  src/models/room.ts
  src/models/user.ts
  src/sliding-sync-sdk.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb-store-worker.ts
  src/store/indexeddb.ts
  src/store/memory.ts
  src/sync.ts
  src/webrtc/call.ts
Labels: T-Task

#2750 Export types for MatrixEvent and Room emitted events, and make event handler map types stricter
  src/models/event.ts
  src/models/room.ts
Labels: T-Enhancement, Z-Community-PR

#2757 Fix notification type when resetting threads notifications
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Task

#2759 Remove deprecated `m.room.aliases` references
  src/@types/event.ts
  src/models/event.ts
  src/models/room.ts
Labels: T-Deprecation

#2761 Fix IdentityPrefix.V2 containing spurious `/api`
  src/http-api/prefix.ts
Labels: T-Defect, X-Release-Blocker

#2766 More debugging for multiple group calls
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#2769 Fix POST data not being passed for registerWithIdentityServer
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#2734 Encryption should not hinder verification
  spec/unit/crypto/algorithms/megolm.spec.ts
  src/@types/event.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/Error.ts
  src/crypto/verification/SAS.ts
  src/crypto/verification/request/VerificationRequest.ts
Labels: T-Defect

#2767 Remove incorrect comment
  src/client.ts
Labels: T-Task

#2747 Support sign in + E2EE set up using QR code implementing MSC3886, MSC3903 and MSC3906
  spec/unit/rendezvous/DummyTransport.ts
  spec/unit/rendezvous/ecdh.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  spec/unit/rendezvous/simpleHttpTransport.spec.ts
  src/crypto/verification/SAS.ts
  src/crypto/verification/SASDecimal.ts
  src/feature.ts
  src/rendezvous/MSC3906Rendezvous.ts
  src/rendezvous/RendezvousChannel.ts
  src/rendezvous/RendezvousCode.ts
  src/rendezvous/RendezvousError.ts
  src/rendezvous/RendezvousFailureReason.ts
  src/rendezvous/RendezvousIntent.ts
  src/rendezvous/RendezvousTransport.ts
  src/rendezvous/channels/MSC3903ECDHv1RendezvousChannel.ts
  src/rendezvous/channels/index.ts
  src/rendezvous/index.ts
  src/rendezvous/transports/MSC3886SimpleHttpRendezvousTransport.ts
  src/rendezvous/transports/index.ts
Labels: T-Enhancement

#2776 README.md: fix jsdoc viewer incantation
  README.md
Labels: T-Task

#2780 Fix connectivity regressions
  src/webrtc/call.ts
Labels: T-Defect

#2768 Fix to keep locally computed thread notifications
  spec/unit/room.spec.ts
  src/models/room.ts
  src/sync.ts
Labels: T-Task

#2777 Add debugging for unsent to-device messages
  src/ToDeviceMessageQueue.ts
Labels: T-Task

#2783 fix build error caused by wrong ts-strict improvements
  src/crypto/DeviceList.ts
Labels: T-Defect

#2784 Add `room_type` field to /publicRooms response
  src/client.ts
Labels: T-Task

#2791 Improve crypto init code and allow easier shimming
  src/crypto/crypto.ts
Labels: X-Release-Blocker, T-Task, backport staging

#2793 [Backport] Improve crypto init code and allow easier shimming (#2791)
  src/crypto/crypto.ts
Labels: T-Task

#2787 Add throwOnFail to groupCall.setScreensharingEnabled
  src/webrtc/groupCall.ts
  src/webrtc/mediaHandler.ts
Labels: T-Defect

#2785 Sliding sync: add include_old_rooms; remove is_tombstoned
  src/sliding-sync.ts
Labels: T-Task

#2794 Fix incorrect prevEv being sent in ClientEvent.AccountData events
  spec/integ/matrix-client-syncing.spec.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Defect

#2797 Add event and message capabilities to RoomWidgetClient
  spec/unit/embedded.spec.ts
  src/client.ts
  src/embedded.ts
Labels: T-Enhancement

#2805 TS strict mode compliance in the call / groupcall code
  spec/unit/webrtc/callEventHandler.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/audioContext.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#2806 Clean up group call tests
  spec/unit/webrtc/groupCall.spec.ts
Labels: T-Task

#2808 More TS strict mode fixes
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callEventHandler.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/groupCall.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#2801 Sliding sync: add include_old_rooms; remove is_tombstoned
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Task

#2804 Emit UnreadNotification event on notifications reset
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Defect

#2814 Switch ESLint warnings to be errors instead
  .eslintrc.js
Labels: T-Task

#2812 Replace `instanceof Array` with `Array.isArray`
  src/crypto/verification/SAS.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
  src/utils.ts
Labels: T-Defect

#2816 A few more strict mode fixes
  src/client.ts
  src/embedded.ts
Labels: T-Task

#2815 Let leave requests outlive the window
  spec/unit/webrtc/groupCall.spec.ts
  src/client.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2825 Fix JSDoc
  src/client.ts
  src/http-api/index.ts
Labels: T-Task, backport staging

#2822 Fix authedRequest including `Authorization: Bearer undefined` for password resets
  spec/unit/http-api/fetch.spec.ts
  src/client.ts
  src/http-api/fetch.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#2828 Catch server versions API call exception when starting the client
  spec/integ/matrix-client-syncing.spec.ts
  src/client.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#2826 Resolve races between `initLocalCallFeed` and `leave`
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Defect

#2830 Fix default behavior of Room.getBlacklistUnverifiedDevices
  spec/unit/room.spec.ts
  src/crypto/algorithms/megolm.ts
  src/models/room.ts
Labels: T-Defect, backport staging
