Repository matrix-org/matrix-js-sdk, pull requests merged in 2022-12, with the labels that each got.

#2930 Add method to get outgoing room key requests for a given event
  spec/integ/matrix-client-crypto.spec.ts
  src/client.ts
Labels: T-Enhancement

#2935 Make GroupCall work better with widgets
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#2936 Backport "Make GroupCall work better with widgets" to staging
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement, X-Release-Blocker

#2911 Switch to stable /relations endpoint, stop using unspecced original_event field
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-relations.spec.ts
  src/@types/requests.ts
  src/client.ts
Labels: T-Task

#2922 Include pending events in thread summary and count again
  spec/unit/models/thread.spec.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Enhancement

#2901 Improve perceived performance for threads
  src/models/thread.ts
Labels: T-Task

#2937 Fix highlight notifications increasing when total notification is zero
  spec/unit/notifications.spec.ts
  src/client.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect, backport staging

#2923 Move updated threads to the end of the thread list
  spec/integ/matrix-client-event-timeline.spec.ts
  src/models/room.ts
Labels: T-Defect

#2927 Move @types deps into devDeps
  package.json
Labels: T-Task

#2921 Redo key sharing after own device verification
  spec/unit/crypto/verification/setDeviceVerification.spec.ts
  src/crypto/index.ts
Labels: T-Defect

#2933 bugfix: sliding sync initial room timelines shouldn't notify
  spec/integ/sliding-sync-sdk.spec.ts
  src/sliding-sync-sdk.ts
  src/sliding-sync.ts
Labels: T-Defect

#2941 Don't expose `calls` on `GroupCall`
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
Labels: X-Breaking-Change, T-Task

#2938 Add a message ID on each to-device message
  package.json
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  src/@types/event.ts
  src/ToDeviceMessageQueue.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/SecretStorage.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  src/webrtc/call.ts
  yarn.lock
Labels: T-Enhancement

#2948 Update test runner instructions
  README.md
Labels: A-Documentation, T-Task

#2872 Upload device keys during initCrypto
  spec/integ/matrix-client-crypto.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/backup.spec.ts
  src/client.ts
Labels: T-Task

#2953 Cache read receipts for unknown threads
  spec/integ/matrix-client-syncing.spec.ts
  src/models/room.ts
Labels: T-Defect

#2952 Fix `examples/browser`
  examples/browser/README.md
  examples/browser/browserTest.js
Labels: T-Task

#2950 Expose a new 'userHasCrossSigningKeys' method
  spec/unit/crypto/cross-signing.spec.ts
  src/client.ts
  src/crypto/index.ts
Labels: T-Task

#2946 Minor VoIP stack improvements
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#2957 Do not calculate highlight notifs for threads unknown to the room
  spec/unit/notifications.spec.ts
  src/client.ts
Labels: T-Defect

#2959 Apply prettier to the client.ts file
  src/client.ts
Labels: T-Task

#2960 Make sure that MegolmEncryption.setupPromise always resolves
  spec/unit/crypto/algorithms/megolm.spec.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Defect

#2962 Don't swallow errors coming from the shareSession call
  src/crypto/algorithms/megolm.ts
Labels: T-Defect

#2963 Fix infinite loop when restoring cached read receipts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2961 Exclude generated files from prettier
  .prettierignore
Labels: T-Task

#2965 Fix #23919: Root message for new thread loaded from network
  src/models/thread.ts
Labels: T-Defect

#2951 Fix #23916: Prevent edits of the last message in a thread getting lost
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/test-utils/thread.ts
  spec/unit/room.spec.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2955 Begin factoring out a CryptoBackend interface
  spec/integ/megolm-integ.spec.ts
  spec/unit/crypto/cross-signing.spec.ts
  spec/unit/room.spec.ts
  src/@types/crypto.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/common-crypto/README.md
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/index.ts
  src/models/event.ts
Labels: T-Task

#2968 Avoid creating duplicate threads
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Task

#2947 Tweak how the SonarCloud scan fails
  .github/workflows/sonarcloud.yml
Labels: T-Task

#2967 Support MSC3391: Account data deletion
  spec/unit/matrix-client.spec.ts
  spec/unit/stores/memory.spec.ts
  src/client.ts
  src/feature.ts
  src/store/memory.ts
Labels: T-Enhancement

#2979 Add prettier formatting to .git-blame-ignore-revs
  .git-blame-ignore-revs
Labels: T-Task

#2969 Introduce a mechanism for using the rust-crypto-sdk
  package.json
  spec/integ/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/constants.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement

#2920 Resume to-device message queue after resumed sync
  spec/unit/ToDeviceMessageQueue.spec.ts
  src/ToDeviceMessageQueue.ts
Labels: T-Defect

#2992 Close all streams when a call ends
  src/webrtc/call.ts
Labels: T-Defect

#2996 Threads are missing from the timeline
  spec/integ/matrix-client-event-timeline.spec.ts
  src/client.ts
Labels: T-Defect, backport staging

#2993 Don't use `RoomMember` as a `calls` a key on `GroupCall`
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#2954 Implement MSC3912: Relation-based redactions
  spec/unit/matrix-client.spec.ts
  src/@types/event.ts
  src/@types/requests.ts
  src/client.ts
  src/feature.ts
Labels: T-Enhancement

#2970 Add `exportRoomKeys` to `CryptoBackend`
  spec/unit/rust-crypto.spec.ts
  src/@types/crypto.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/OlmDevice.ts
  src/crypto/algorithms/base.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#2991 sliding sync: Fix issue where no unsubs are sent when switching rooms
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Defect

#2999 Fix release scripts to not fight with prettier
  release.sh
Labels: X-Release-Blocker, T-Task, backport staging

#3005 Add `device_id` to `/account/whoami` types
  src/client.ts
Labels: T-Enhancement

#3002 Apply edits discovered from sync after thread is initialised
  spec/unit/event-timeline-set.spec.ts
  src/models/thread.ts
Labels: T-Defect

#3008 bugfix: upload OTKs in sliding sync mode
  src/sliding-sync-sdk.ts
Labels: T-Defect

#2998 Break coupling between `Room` and `Crypto.trackRoomDevices`
  spec/TestClient.ts
  spec/integ/megolm-integ.spec.ts
  src/crypto/index.ts
  src/models/room-state.ts
  src/models/room.ts
Labels: T-Task
