Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-08, with the labels that each got.

#3641 ElementR: Throw error if missing `userId` in `CryptoApi.findVerificationRequestDMInProgress`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3640 Fix wrong handling of encrypted rooms when loading them from sync accumulator
  spec/integ/matrix-client-syncing.spec.ts
  src/client.ts
  src/sync.ts
Labels: T-Defect

#3645 Mark more logs as debug to tidy the console
  src/crypto/OlmDevice.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#3633 Implement `CryptoApi.checkKeyBackupAndEnable`
  spec/integ/crypto/megolm-backup.spec.ts
  spec/test-utils/test-data/index.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto-api/keybackup.ts
  src/crypto/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3650 ElementR: Process all verification events, not just requests
  spec/unit/rust-crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
Labels: T-Defect

#3660 Re-export localStorage-crypto-store
  src/matrix.ts
Labels: T-Task

#3007 Set minimum supported Matrix 1.1 version (drop legacy r0 versions)
  README.md
  spec/TestClient.ts
  spec/integ/crypto/crypto.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/test-utils/E2EKeyReceiver.ts
  spec/test-utils/E2EKeyResponder.ts
  spec/test-utils/SyncResponder.ts
  spec/test-utils/client.ts
  spec/test-utils/mockEndpoints.ts
  spec/unit/autodiscovery.spec.ts
  spec/unit/content-repo.spec.ts
  spec/unit/http-api/__snapshots__/index.spec.ts.snap
  spec/unit/http-api/index.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/queueToDevice.spec.ts
  src/@types/requests.ts
  src/autodiscovery.ts
  src/client.ts
  src/content-repo.ts
  src/http-api/index.ts
  src/http-api/prefix.ts
  src/interactive-auth.ts
  src/sync.ts
  src/version-support.ts
Labels: T-Enhancement, X-Breaking-Change

#3652 RustCrypto | Implement keybackup loop
  package.json
  spec/integ/crypto/megolm-backup.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto/backup.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#3643 ElementR: Add `CryptoApi.requestVerificationDM`
  spec/integ/crypto/verification.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3666 Export de-facto public types out of @types
  src/@types/crypto.ts
  src/common-crypto/CryptoBackend.ts
  src/matrix.ts
Labels: T-Task

#3674 Improve/fix `client.restoreKeyBackupWithPassword` docs
  src/client.ts
Labels: T-Task

#3673 Add `join_rule` field to /publicRooms response
  src/client.ts
Labels: T-Enhancement, Z-Community-PR

#3646 ElementR: Update `CryptoApi.userHasCrossSigningKeys`
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3683 `OutgoingRequestProcessor`: do not throw errors if shutting down
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Task

#3687 Emit summary update event
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Enhancement
