Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-11, with the labels that each got.

#3813 New release automations
  .github/release-drafter.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-master.yml
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  docs/SUMMARY.md
  docs/release.md
Labels: T-Task

#3848 Make release automation reusable and add dependency upgrade support
  .github/workflows/release-action.yml
  .github/workflows/release.yml
Labels: T-Task

#3839 Age fallback using origin_server_ts instead of 0
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/matrixrtc/CallMembership.ts
  src/models/event.ts
Labels: T-Defect

#3853 Revert "Age fallback using origin_server_ts instead of 0"
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/matrixrtc/CallMembership.ts
  src/models/event.ts
Labels: T-Task

#3830 Fix members being loaded from server on initial sync (defeating lazy loading)
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/OutgoingRequestsManager.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/OutgoingRequestsManager.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3817 Ignore receipts pointing at missing or invalid events
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/models/read-receipt.ts
Labels: T-Defect

#3851 Iterate reusable release automation workflows
  .github/workflows/release-action.yml
  .github/workflows/release-gitflow.yml
Labels: T-Task

#3854 Better fallback for unavailable event age
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/matrixrtc/CallMembership.ts
  src/models/event.ts
Labels: T-Task

#3833 Rotate per-participant keys when a member leaves
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
Labels: T-Enhancement

#3858 Revert code moving deleted messages to main timeline
  spec/unit/models/event.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/room.spec.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: X-Release-Blocker, T-Task, backport staging

#3857 Tidy release automation
  .github/workflows/release-action.yml
  .github/workflows/release-gitflow.yml
  post-release.sh
  release.sh
  scripts/release/post-merge-master.sh
  scripts/release/pre-release.sh
Labels: T-Task

#3868 Update workfile to pull in changes from react-sdk
  .github/workflows/cypress.yml
Labels: T-Task

#3862 Shorten TimelineWindow when an event is removed
  spec/test-utils/test-utils.ts
  spec/unit/timeline-window.spec.ts
  src/timeline-window.ts
Labels: T-Defect

#3852 Extend release automation with GPG signing, assets & changelog merging
  .github/actions/sign-release-tarball/action.yml
  .github/actions/upload-release-assets/action.yml
  .github/workflows/release-action.yml
  scripts/release/merge-release-notes.js
Labels: T-Task

#3870 Revert "Better fallback for unavailable event age"
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/matrixrtc/CallMembership.ts
  src/models/event.ts
Labels: T-Task

#3849 Bump matrix-sdk-crypto-wasm to 3.0.1
  package.json
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  yarn.lock
Labels: T-Task

#3847 Run tests on LTS and Node 21
  .github/workflows/tests.yml
Labels: T-Task

#3865 Automate checking there is no published release using the version already
  .github/workflows/release-action.yml
Labels: T-Task

#3867 Ensure `setUserCreator` is called when a store is assigned
  src/client.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#3872 Automatically add tech-debt issues to the right project
  .github/workflows/triage-labelled.yml
Labels: T-Task

#3866 Add automation to advance release blocker labels during the release
  .github/workflows/release-action.yml
Labels: T-Task

#3864 Add support for ingest-changes to refer to a project without package.json
  .github/workflows/release-action.yml
  scripts/release/merge-release-notes.js
Labels: X-Release-Blocker, T-Task

#3869 Unrevert "Move redacted messages out of any thread, into main thread"
  spec/unit/models/event.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/room.spec.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#3878 Add CallNotifyEvent to support matrixRTC ringing
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/@types/event.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/types.ts
Labels: T-Enhancement

#3877 Don't rotate keys if not managing media keys
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#3874 Remove unused dependencies and add transitive dep
  package.json
  yarn.lock
Labels: T-Task

#3893 Specify the correct environment for the docs builder workflow
  .github/workflows/docs-pr-netlify.yaml
Labels: T-Task

#3894 Explicitly forward ELEMENT_BOT_TOKEN
  .github/workflows/triage-labelled.yml
Labels: T-Task

#3897 Stop logging decryptions as retries
  src/models/MSC3089Branch.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Task

#3898 Improve logging of event encryption in `RustCrypto`
  spec/unit/rust-crypto/KeyClaimManager.spec.ts
  src/logger.ts
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3900 Better fallback for the event `localTimestamp` calculation.
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/matrixrtc/CallMembership.ts
  src/models/event.ts
Labels: T-Enhancement

#3896 Reduce console log spam
  src/client.ts
  src/models/thread.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#3902 Only await key query after lazy members resolved
  src/rust-crypto/RoomEncryptor.ts
Labels: T-Task

#3904 Remove 'Ignoring receipt' log line that logs very often'
  spec/unit/room.spec.ts
  src/models/read-receipt.ts
Labels: T-Task

#3906 Fix type for TimestampToEventResponse.origin_server_ts
  src/client.ts
Labels: T-Defect

#3905 Set up CI to lint workflows with action-validator
  .github/workflows/release-make.yml
  .github/workflows/release.yml
  .github/workflows/static_analysis.yml
  package.json
  yarn.lock
Labels: T-Task

#3909 Update to matrix-sdk-crypto-wasm 3.1.0
  package.json
  yarn.lock
Labels: T-Task

#3911 Explicitly free some Rust-side objects
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3901 Rewrite receipt-handling code
  spec/test-utils/thread.ts
  spec/unit/models/room-receipts.spec.ts
  spec/unit/models/thread.spec.ts
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/compare-event-ordering.ts
  src/models/event-timeline-set.ts
  src/models/read-receipt.ts
  src/models/room-receipts.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#3927 Fix broken downstream cypress tests
  .github/workflows/cypress.yml
Labels: T-Task

#3907 fix uncaught exceptions in Backup Loop for rust sdk
  src/rust-crypto/backup.ts
Labels: T-Task

#3899 move get device key API from client to crypto
  spec/integ/crypto/crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3928 Signal key backup in cache
  spec/integ/crypto/verification.spec.ts
  src/client.ts
  src/crypto/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task
