Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-12, with the labels that each got.

#3910 Update Sibz/github-status-action to use node16 to silence warning
  .github/workflows/cypress.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/tests.yml
Labels: T-Task

#3933 Bump `matrix-rust-sdk-crypto-wasm` to v3.2.0
  package.json
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#3912 Rust-crypto: fix `bootstrapCrossSigning` on second call
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/AccountDataAccumulator.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3914 Run matrix-react-sdk playwright tests downstream
  .github/workflows/cypress.yml
Labels: T-Task

#3932 Element-R: await `/keys/query` during Verification requests
  spec/unit/rust-crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
Labels: T-Task

#3938 Bump matrix-sdk-crypto-wasm to 3.4.0
  package.json
  yarn.lock
Labels: T-Task

#3940 Fix "mark_skipped" action for end-to-end tests
  .github/workflows/cypress.yml
Labels: T-Task

#3935 Call scheduleAllGroupSessionsForBackup during resetKeyBackup
  spec/integ/crypto/crypto.spec.ts
  src/client.ts
  src/crypto/index.ts
Labels: T-Task

#3918 Fix upload with empty Content-Type
  src/http-api/index.ts
Labels: T-Defect, Z-Community-PR

#3934 Don't back up keys that we got from backup
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3945 Include event & room ID in log line
  src/client.ts
Labels: T-Task

#3939 Element-R: disable sending room key requests
  src/rust-crypto/index.ts
Labels: T-Enhancement

#3944 Move roomList out of MatrixClient, into legacy Crypto
  spec/unit/crypto.spec.ts
  src/client.ts
  src/crypto/RoomList.ts
  src/crypto/index.ts
Labels: T-Task

#3959 Remove m.thread filter from relations API call
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/unit/thread-utils.spec.ts
  src/client.ts
  src/models/thread.ts
  src/thread-utils.ts
Labels: T-Defect

#3961 Bump matrix-sdk-crypto-wasm to 3.5.0
  package.json
  yarn.lock
Labels: T-Task

#3948 ElementR: Ensure there is only one call to shareRoomKeys in flight at once
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  src/rust-crypto/RoomEncryptor.ts
Labels: T-Task

#3965 Add some perfomance logs
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/OutgoingRequestsManager.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
  src/utils.ts
Labels: T-Task

#3950 ElementR: Fix missing key check values in 4S key storage
  spec/integ/crypto/crypto.spec.ts
  spec/unit/crypto/crypto-utils.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/secret-storage.spec.ts
  src/crypto-api.ts
  src/crypto/SecretStorage.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/secret-storage.ts
Labels: T-Defect, X-Breaking-Change

#3969 Add new methods to `CryptoStore` for Rust Crypto migration
  spec/unit/crypto/store/CryptoStore.spec.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
Labels: T-Task

#3968 Send authenticated /versions request
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement

#3962 Move sonarcloud shard support into reusable workflow
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
  .github/workflows/tests.yml
Labels: T-Task

#3976 Element-R: fix `bootstrapSecretStorage` not resetting key backup when requested
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect
