Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-07, with the labels that each got.

#3526 Element-R: Implement `VerificationRequest.accept`
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
  yarn.lock
Labels: T-Task

#3536 Rust crypto: allow using a memory store
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
Labels: T-Enhancement

#3532 Element-R: Implement `VerificationRequest.{timeout,pending}`
  package.json
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/rust-crypto/verification.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
  src/rust-crypto/verification.ts
  yarn.lock
Labels: T-Task

#3531 OIDC: validate id token
  package.json
  spec/unit/oidc/authorize.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/oidc/authorize.ts
  src/oidc/error.ts
  src/oidc/validate.ts
  yarn.lock
Labels: T-Enhancement

#3486 Fix an instance of failed to decrypt error when an in flight `/keys/query` fails.
  src/crypto/algorithms/olm.ts
Labels: T-Defect

#3540 Ignore thread relations on state events for consistency with edits
  spec/unit/models/event.spec.ts
  src/models/event.ts
Labels: T-Enhancement

#3543 Log the message ID of any undecryptable to-device messages
  src/models/event.ts
Labels: T-Enhancement

#3552 Upgrade `@matrix-org/matrix-sdk-crypto-js` to `^0.1.1`
  package.json
  yarn.lock
Labels: T-Task

#3553 add stop() api to BackupManager for clean shutdown
  src/crypto/backup.ts
  src/crypto/index.ts
Labels: T-Enhancement

#3547 Update IUnsigned type to be extensible
  src/models/event.ts
Labels: T-Enhancement

#3541 Prevent threads code from making identical simultaneous API hits
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/test-utils/thread.ts
  spec/unit/models/thread.spec.ts
  spec/unit/room.spec.ts
  src/models/thread.ts
Labels: T-Enhancement

#3549 Don't allow Olm unwedging rate-limiting to race
  src/crypto/index.ts
Labels: T-Defect

#3544 OIDC: use `oidc-client-ts`
  package.json
  spec/test-utils/oidc.ts
  spec/unit/autodiscovery.spec.ts
  spec/unit/oidc/authorize.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/autodiscovery.ts
  src/oidc/authorize.ts
  src/oidc/discovery.ts
  src/oidc/validate.ts
  yarn.lock
Labels: T-Task

#3556 Send 'contentLoaded' event
  src/embedded.ts
Labels: T-Task

#3563 Add comment on updating the livekit service URL
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#3562 Add async method for generating a QR code
  spec/integ/crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/rust-crypto/verification.ts
Labels: T-Deprecation

#3554 OIDC: Log in
  spec/unit/oidc/authorize.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/oidc/authorize.ts
  src/oidc/error.ts
  src/oidc/validate.ts
Labels: T-Enhancement

#3570 Simplify `MatrixClient::setPowerLevel` API
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Enhancement, T-Deprecation

#3571 add getOpenIdToken to embedded client backend
  spec/unit/embedded.spec.ts
  src/embedded.ts
Labels: T-Enhancement

#3577 Throw saner error when peeking has its room pulled out from under it
  src/sync.ts
Labels: T-Enhancement

#3579 remove symlinks to missing documentation versions
  v16.0
  v25.2
Labels: T-Defect

#3574 Mark all the rust crypto stuff internal
  src/common-crypto/CryptoBackend.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/device-converter.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/secret-storage.ts
  src/rust-crypto/verification.ts
Labels: T-Task

#3576 Use `cryptoBackend` in `client.ts` for new rust-crypto implementation
  src/client.ts
Labels: T-Task

#3565 Add support for scanning QR codes during verification, with Rust crypto
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/verification.spec.ts
  src/client.ts
  src/crypto-api/verification.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
Labels: T-Enhancement

#3485 Improve logging of http requests to aid debugging
  spec/unit/http-api/fetch.spec.ts
  src/http-api/fetch.ts
Labels: T-Task

#3587 Bump matrix-crypto-sdk-js
  package.json
  yarn.lock
Labels: T-Task

#3397 Stabilize support for MSC3952: intentional mentions
  spec/unit/pushprocessor.spec.ts
  src/@types/PushRules.ts
  src/feature.ts
  src/models/event.ts
  src/pushprocessor.ts
Labels: T-Task

#3590 Fix broken DeviceList.spec.ts test
  spec/unit/crypto/DeviceList.spec.ts
Labels: T-Task

#3589 Improve types
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/index.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
  src/rendezvous/MSC3906Rendezvous.ts
  src/webrtc/stats/media/mediaTrackHandler.ts
Labels: T-Task

#3594 Fix sending `auth: null` due to broken types around UIA
  src/crypto/EncryptionSetup.ts
  src/interactive-auth.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Defect

#3595 Fix types in getSessionBackupPrivateKey
  src/@types/requests.ts
  src/client.ts
  src/crypto/index.ts
Labels: T-Task

#3598 Don't update calls with no livekit URL
  src/client.ts
  src/webrtc/callEventTypes.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Defect

#3586 Fix jest/valid-expects lints
  .eslintrc.js
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/sliding-sync.spec.ts
  spec/unit/login.spec.ts
  spec/unit/oidc/register.spec.ts
  spec/unit/rendezvous/ecdhv2.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  spec/unit/rendezvous/simpleHttpTransport.spec.ts
  spec/unit/stores/indexeddb.spec.ts
  spec/unit/utils.spec.ts
  spec/unit/webrtc/call.spec.ts
Labels: T-Task

#3600 Fix read receipt sending behaviour around thread roots
  src/client.ts
Labels: T-Defect

#3599 Element-R: ensure that `userHasCrossSigningKeys` uses up-to-date data
  package.json
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Defect

#3597 Export typed event emitter key types
  src/matrix.ts
Labels: T-Defect

#3588 Element-R: support for displaying QR codes during verification
  spec/integ/crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/rust-crypto/verification.ts
Labels: T-Enhancement

#3591 Log query parameters on HTTP requests
  spec/unit/http-api/fetch.spec.ts
  src/http-api/fetch.ts
Labels: T-Task

#3602 matrix-sdk-crypto-js -> matrix-sdk-crypto-wasm
  package.json
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  spec/unit/rust-crypto/KeyClaimManager.spec.ts
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/rust-crypto/verification.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/device-converter.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
  yarn.lock
Labels: T-Task

#3606 Add tests for room-hierarchy
  spec/unit/room-hierarchy.spec.ts
Labels: T-Task

#3605 Remove unused better-docs & docdash
  package.json
  yarn.lock
Labels: T-Task

#3609 Specify /preview_url requests as low priority
  src/@types/global.d.ts
  src/client.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
Labels: T-Enhancement

#3607 Fix edge cases around non-thread relations to thread roots and read receipts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/test-utils/thread.ts
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Defect

#3610 Make sure to drop references to user device lists
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3611 ElementR: Fix `userId` parameter usage in `CryptoApi#getVerificationRequestsToDeviceInProgress`
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3612 Only send threaded read receipts if threads support is enabled
  spec/unit/read-receipt.spec.ts
  src/client.ts
Labels: T-Defect

#3613 Avoid running cypress tests outside of merge queue
  .github/workflows/downstream-artifacts.yml
Labels: T-Task

#3615 Fix how `Room::eventShouldLiveIn` handles replies to unknown parents
  spec/unit/room.spec.ts
  src/models/event-timeline-set.ts
  src/models/room.ts
Labels: T-Defect

#3616 Fix registration check your emails stage regression
  spec/unit/interactive-auth.spec.ts
  src/interactive-auth.ts
Labels: T-Defect, X-Release-Blocker

#3617 Ensure we do not clobber a newer RR with an older unthreaded one
  spec/unit/read-receipt.spec.ts
  spec/unit/room.spec.ts
  src/models/read-receipt.ts
Labels: T-Defect

#3618 Fix threads ending up with chunks of their timelines missing
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/unit/models/thread.spec.ts
  spec/unit/room.spec.ts
  src/models/thread.ts
Labels: T-Defect, X-Release-Blocker

#3608 ElementR: Stub `CheckOwnCrossSigningTrust`, import cross signing keys and verify local device in `bootstrapCrossSigning`
  spec/integ/crypto/cross-signing.spec.ts
  spec/test-utils/mockEndpoints.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3550 Replace deprecated TestClient with fetchMock
  spec/TestClient.ts
  spec/integ/crypto/megolm-backup.spec.ts
Labels: T-Task

#3619 ElementR: Add `CryptoApi.getCrossSigningKeyId`
  spec/integ/crypto/cross-signing.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3621 Upgrade matrix-widget-api
  package.json
  yarn.lock
Labels: T-Task

#3631 Clean up megolm-backup integ test
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/crypto/verification.spec.ts
  spec/test-utils/E2EKeyResponder.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
Labels: T-Task

#3555 Add `CryptoApi.getActiveSessionBackupVersion()`
  spec/integ/crypto/megolm-backup.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3632 Implement `CryptoApi.isKeyBackupTrusted`
  package.json
  spec/integ/crypto/megolm-backup.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto-api/keybackup.ts
  src/crypto/backup.ts
  src/crypto/deviceinfo.ts
  src/crypto/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#3614 Export more into the public interface
  src/matrix.ts
Labels: T-Enhancement

#3634 Ensure we don't overinflate the total notification count
  spec/unit/event-timeline-set.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/event.ts
Labels: T-Defect

#3638 Bump pagination limit to account for threaded events
  src/timeline-window.ts
Labels: T-Enhancement

#3642 Skip processing thread roots and fetching threads list when support is disabled
  spec/integ/matrix-client-event-timeline.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Defect
