Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-05, with the labels that each got.

#3337 Update `@matrix-org/matrix-sdk-crypto-js` to `^0.1.0-alpha.8`
  package.json
  yarn.lock
Labels: T-Task

#3339 Accumulate receipts for the main thread and unthreaded separately
  spec/unit/receipt-accumulator.spec.ts
  src/receipt-accumulator.ts
Labels: T-Defect

#3330 Update types to match spec
  src/client.ts
Labels: T-Task

#3344 Use WeakMap in ReEmitter to help enable garbage collection
  src/ReEmitter.ts
Labels: T-Task

#3350 Revert "Update JS-DevTools/npm-publish action to v2 (#3336)"
  .github/workflows/release-npm.yml
Labels: T-Task, backport staging

#3341 Do an ICE Restart if WebRTC become disconnected
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  src/webrtc/call.ts
Labels: T-Task

#3352 Rename and move `crypto.IBootstrapCrossSigningOpts`
  spec/unit/crypto/cross-signing.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/index.ts
  src/interactive-auth.ts
Labels: T-Task

#3353 Pass SecretStorage into RustCrypto
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3354 Element-R: Stub out `isCrossSigningReady` and `isSecretStorageReady`
  spec/unit/matrix-client.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3349 Audio concealment
  spec/unit/webrtc/stats/statsReportBuilder.spec.ts
  spec/unit/webrtc/stats/statsReportGatherer.spec.ts
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  spec/unit/webrtc/stats/trackStatsReporter.spec.ts
  src/webrtc/stats/connectionStats.ts
  src/webrtc/stats/media/mediaTrackStats.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportBuilder.ts
  src/webrtc/stats/statsReportGatherer.ts
  src/webrtc/stats/summaryStats.ts
  src/webrtc/stats/summaryStatsReporter.ts
  src/webrtc/stats/trackStatsReporter.ts
Labels: T-Enhancement

#3361 Keep measuring a call feed's volume after a stream replacement
  src/webrtc/callFeed.ts
Labels: T-Defect

#3351 Total summary count
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/summaryStatsReporter.ts
Labels: T-Enhancement

#3356 Enable better tree shaking
  src/content-repo.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/memory-crypto-store.ts
  src/http-api/fetch.ts
  src/http-api/index.ts
  src/models/read-receipt.ts
  src/models/room-member.ts
  src/models/room-state.ts
  src/models/room.ts
  src/scheduler.ts
  src/sliding-sync-sdk.ts
  src/store/indexeddb-local-backend.ts
  src/sync.ts
  src/webrtc/call.ts
Labels: T-Task

#3358 Fix typedoc release documentation deployment
  .github/workflows/release.yml
  package.json
  yarn.lock
Labels: X-Release-Blocker, T-Task

#3357 Deprecate device methods in MatrixClient
  src/client.ts
Labels: T-Enhancement

#3359 Check permission on mute mic, only if no audio track exists.
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#3365 Element-R: support for SigningKeysUploadRequest
  package.json
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  yarn.lock
Labels: T-Task

#3366 correctly accumulate sync summaries.
  spec/unit/sync-accumulator.spec.ts
  src/sync-accumulator.ts
Labels: T-Defect

#3367 fix accumulated sync summaries - andy review
  spec/unit/sync-accumulator.spec.ts
Labels: T-Other

#3369 Fix CI failure on develop due to force merged PR and prettier failure
  spec/unit/sync-accumulator.spec.ts
Labels: X-Release-Blocker, T-Task

#3362 Add methods to terminate idb worker
  spec/unit/stores/indexeddb.spec.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb.ts
  src/store/memory.ts
  src/store/stub.ts
Labels: T-Enhancement

#3368 Element-R: initial implementation of `bootstrapCrossSigning`
  spec/integ/cross-signing.spec.ts
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3377 Filter all summary stats which collect the first time webrtc metrics.
  spec/unit/webrtc/stats/groupCallStats.spec.ts
  spec/unit/webrtc/stats/statsReportGatherer.spec.ts
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  src/webrtc/stats/statsReportGatherer.ts
  src/webrtc/stats/summaryStats.ts
  src/webrtc/stats/summaryStatsReporter.ts
Labels: T-Task

#3380 Comments for typed-event-emitter classes
  src/matrix.ts
  src/models/typed-event-emitter.ts
Labels: T-Task

#3382 Fix verification bug with `pendingEventOrdering: "chronological"`
  src/crypto/verification/request/InRoomChannel.ts
Labels: T-Defect

#3379 Add typedoc-plugin-coverage
  package.json
  typedoc.json
  yarn.lock
Labels: T-Task

#3384 Attempt a potential workaround for stuck notifs
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/thread.ts
Labels: T-Defect, backport staging

#3376 Don't try run sonarcloud if tests got cancelled/failed
  .github/workflows/sonarqube.yml
Labels: T-Task

#3388 Make sonar happier about our code & tests
  spec/integ/crypto.spec.ts
  spec/olm-loader.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/room.spec.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/autodiscovery.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/DeviceList.ts
  src/crypto/store/memory-crypto-store.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/embedded.ts
Labels: T-Task

#3386 Combine `QrCodeEvent`, `SasEvent` and `VerificationEvent`
  src/crypto-api.ts
  src/crypto-api/verification.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/QRCode.ts
  src/crypto/verification/SAS.ts
Labels: T-Deprecation

#3393 Fix mark as unread button
  spec/test-utils/thread.ts
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: X-Release-Blocker, T-Task

#3391 Test for inserting events into the timeline in timestamp order
  spec/test-utils/test-utils.ts
  spec/unit/models/thread.spec.ts
  spec/unit/room.spec.ts
Labels: T-Task

#3378 Add more context for why threaded vs unthreaded read receipts
  src/receipt-accumulator.ts
Labels: A-Documentation, T-Task

#3406 Minor fixes to CryptoApi doc comments
  src/crypto-api.ts
Labels: T-Task

#3389 Minor improvements to the code inserting events into timelines
  src/models/event-timeline.ts
  src/models/thread.ts
Labels: T-Task

#3390 Isolate changes to Thread global into a single describe block
  spec/unit/event-timeline-set.spec.ts
Labels: T-Task

#3407 Fix an existing test for editing messages in threads
  spec/unit/event-timeline-set.spec.ts
Labels: T-Task

#3399 Only add a local receipt if it's after an existing receipt
  spec/unit/models/thread.spec.ts
  src/models/thread.ts
Labels: T-Defect

#3409 Simplify thread-editing test
  spec/test-utils/test-utils.ts
  spec/unit/models/thread.spec.ts
Labels: T-Task

#3404 Refactor naming of webrtc stats reporter
  spec/unit/webrtc/stats/callStatsReportGatherer.spec.ts
  spec/unit/webrtc/stats/connectionStatsReportBuilder.spec.ts
  spec/unit/webrtc/stats/connectionStatsReporter.spec.ts
  spec/unit/webrtc/stats/groupCallStats.spec.ts
  spec/unit/webrtc/stats/summaryStatsReportGatherer.spec.ts
  spec/unit/webrtc/stats/trackStatsBuilder.spec.ts
  spec/unit/webrtc/stats/transportStatsBuilder.spec.ts
  spec/unit/webrtc/stats/valueFormatter.spec.ts
  src/webrtc/stats/callStatsReportGatherer.ts
  src/webrtc/stats/callStatsReportSummary.ts
  src/webrtc/stats/connectionStatsBuilder.ts
  src/webrtc/stats/connectionStatsReportBuilder.ts
  src/webrtc/stats/groupCallStats.ts
  src/webrtc/stats/summaryStatsReportGatherer.ts
  src/webrtc/stats/trackStatsBuilder.ts
  src/webrtc/stats/transportStatsBuilder.ts
  src/webrtc/stats/valueFormatter.ts
Labels: T-Task

#3411 Adjust fetchEditsWhereNeeded to use a clearer filter and async function
  src/models/thread.ts
Labels: T-Task

#3423 Remove spec non-compliant extended glob format
  spec/unit/pushprocessor.spec.ts
  spec/unit/utils.spec.ts
  src/models/invites-ignorer.ts
  src/utils.ts
Labels: T-Defect

#3425 Mark room version 10 as safe
  src/models/room.ts
Labels: T-Enhancement
