Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-09, with the labels that each got.

#3689 Deprecate `MatrixClient.{prepare,create}KeyBackupVersion` in favour of new `CryptoApi.resetKeyBackup` API
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/mockEndpoints.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Deprecation

#3692 Legacy crypto: re-check key backup after `bootstrapSecretStorage`
  spec/unit/crypto/secrets.spec.ts
  src/crypto/EncryptionSetup.ts
Labels: T-Defect

#3695 Allow calls without ICE/TURN/STUN servers
  src/webrtc/call.ts
Labels: T-Enhancement

#3690 Implement key backup APIs for rust and create backup in `bootstrapSecretStorage`
  spec/integ/crypto/crypto.spec.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3691 Deprecate `MatrixClient.checkUserTrust`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/CrossSigning.ts
  src/crypto/index.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Deprecation

#3703 Sync knock rooms
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/matrix-client-unread-notifications.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/sync-accumulator.spec.ts
  src/models/room.ts
  src/sync-accumulator.ts
  src/sync.ts
Labels: T-Enhancement, Z-Community-PR

#3706 Don't reset unread count when adding a synthetic receipt
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Defect

#3693 Implement `getEncryptionInfoForEvent` and deprecate `getEventEncryptionInfo`
  spec/unit/crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/models/event.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Deprecation

#3715 Explain why synthetic receipts don't mark the room as read
  src/models/room.ts
Labels: T-Task

#3707 Dont access indexed db when undefined
  spec/integ/crypto/rust-crypto.spec.ts
  src/client.ts
Labels: T-Defect, Z-Community-PR

#3716 Element-R: Emit `CryptoEvent.UserTrustStatusChanged` when user identity is updated
  package.json
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#3708 Refactor key backup recovery to prepare for rust
  spec/integ/crypto/megolm-backup.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3722 Avoid an infinite loop in the interactive-auth test
  spec/unit/interactive-auth.spec.ts
Labels: T-Task

#3723 Fix codeowners
  .github/CODEOWNERS
Labels: T-Task

#3709 rust backup restore support
  spec/integ/crypto/megolm-backup.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  spec/unit/crypto/base64.spec.ts
  src/common-crypto/CryptoBackend.ts
  src/common-crypto/base64.ts
  src/crypto-api/keybackup.ts
  src/crypto/index.ts
  src/crypto/keybackup.ts
  src/crypto/recoverykey.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3710 Map decryption errors correctly from rust
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3711 Rust: Query backup on fail to decrypt similar to libolm
  spec/integ/crypto/megolm-backup.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-utils.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3726 Cleanup, separate backup bootstrap and mgmt
  spec/integ/crypto/crypto.spec.ts
Labels: T-Task

#3717 Fix potential delay in sending out requests from the rust SDK
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3718 Rust implementation of `getEncryptionInfoForEvent`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3729 Delete knocked room when knock membership changes
  spec/unit/sync-accumulator.spec.ts
  src/sync-accumulator.ts
Labels: T-Enhancement, Z-Community-PR

#3732 Element-R: use the pickleKey to encrypt the crypto store
  spec/integ/crypto/rust-crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
Labels: T-Task

#3720 Stop keep alive, when sync was stoped
  spec/integ/matrix-client-syncing-errors.spec.ts
  src/client.ts
  src/sync.ts
Labels: T-Defect, Z-Community-PR

#3743 Fix the warning for messages from unsigned devices
  spec/unit/crypto.spec.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3730 Implement isSecretStorageReady in rust
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/rust-crypto/secret-storage.spec.ts
  src/crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/secret-storage.ts
Labels: T-Task

#3744 Add github action to mark cypress tests skipped
  .github/workflows/cypress-skipped.yml
Labels: T-Task

#3747 Fix a case where joinRoom creates a duplicate Room object
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Defect

#3746 fix restoreKeyBackupWithSecretStorage for rust
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/unit/crypto/backup.spec.ts
  src/client.ts
Labels: T-Task

#3752 Remove IsUserMention and IsRoomMention from DEFAULT_OVERRIDE_RULES
  src/pushprocessor.ts
Labels: T-Enhancement

#3731 Implement exportCrossSigningKeysToStorage
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
Labels: T-Task

#3416 Support for stable MSC3882 get_login_token
  spec/integ/matrix-client-methods.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  src/@types/auth.ts
  src/client.ts
  src/rendezvous/MSC3906Rendezvous.ts
Labels: T-Enhancement

#3757 Bump matrix-sdk-crypto-wasm to 1.3.0
  yarn.lock
Labels: T-Task

#3758 Clean up integ tests for incoming user verification
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/olm-utils.ts
  spec/integ/crypto/verification.spec.ts
Labels: T-Task
