Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-10, with the labels that each got.

#3763 Use globalThis instead of global
  spec/olm-loader.ts
  src/browser-index.ts
  src/crypto/crypto.ts
  src/crypto/index.ts
Labels: Z-Community-PR, T-Task

#3759 Remove browserify builds
  .github/workflows/tests.yml
  README.md
  examples/browser/README.md
  examples/browser/browserTest.js
  examples/browser/index.html
  examples/browser/lib/matrix.js
  examples/crypto-browser/lib/.gitignore
  examples/crypto-browser/lib/matrix.js
  examples/crypto-browser/olm-device-export-import.html
  examples/crypto-browser/olm-device-export-import.js
  package.json
  spec/browserify/setupTests.ts
  spec/browserify/sync-browserify.spec.ts
  src/browser-index.ts
  src/rust-crypto/browserify-index.ts
  yarn.lock
Labels: X-Release-Blocker, T-Deprecation

#3768 Export AutoDiscoveryError and fix type of ALL_ERRORS
  src/autodiscovery.ts
Labels: T-Enhancement

#3772 Remove the dist script since we no longer have a browserify build
  package.json
Labels: T-Task

#3762 Element-R: emit `VerificationRequestReceived` on incoming request
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3760 ElementR: Check key backup when user identity changes
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3765 OIDC: add `idTokenClaims` to authorization grant response
  spec/unit/oidc/authorize.spec.ts
  src/oidc/authorize.ts
Labels: T-Task

#3773 Grab bag of Element-R cleanups
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3770 Rust crypto: ensure we persist the key backup version
  spec/integ/crypto/megolm-backup.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3779 Element-R: Avoid errors in `VerificationRequest.generateQRCode` when QR code is unavailable
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/verification.ts
Labels: T-Defect

#3780 Element-R: don't log every HTTP request
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Task

#3785 Warn when we drop an event trying to add it to a thread
  src/models/thread.ts
Labels: T-Task

#3756 make leaveRoomSession async
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Task

#3786 Comments attempting to explain the addEvent method
  src/models/thread.ts
Labels: T-Task

#3784 Element-R: Connect device to key backup when crypto is created
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3769 OIDC: Token refresher class
  spec/unit/oidc/tokenRefresher.spec.ts
  src/http-api/interface.ts
  src/matrix.ts
  src/oidc/authorize.ts
  src/oidc/index.ts
  src/oidc/tokenRefresher.ts
Labels: T-Task

#3788 Fix small typo in README.md in root dir
  README.md
Labels: Z-Community-PR, T-Task

#3792 Allow applications to specify their own logger instance
  spec/unit/http-api/fetch.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3791 Element-R: Don't mark QR code verification as done until it's done
  spec/integ/crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/rust-crypto/verification.ts
Labels: T-Defect

#3793 Don't use event.sender in CallMembership
  spec/unit/matrixrtc/CallMembership.spec.ts
  src/matrixrtc/CallMembership.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#3794 OIDC: add `prompt` param to auth url creation
  spec/unit/oidc/authorize.spec.ts
  src/oidc/authorize.ts
Labels: T-Enhancement

#3764 OIDC: refresh tokens
  spec/integ/crypto/verification.spec.ts
  spec/unit/http-api/fetch.spec.ts
  src/client.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
Labels: T-Enhancement

#3795 Bump wasm bindings version to 2.0.0
  package.json
  yarn.lock
Labels: T-Task

#3797 Clarify code that chooses a thread ID to include in a receipt
  spec/unit/read-receipt.spec.ts
  src/client.ts
Labels: T-Task

#3799 Fix sending call member events on leave
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#3787 Add events to the thread even if they appear to be out of order
  spec/unit/models/thread.spec.ts
  src/models/thread.ts
Labels: T-Task

#3801 Deprecate `MatrixEvent.toJSON`
  src/models/event.ts
Labels: T-Deprecation

#3808 OIDC: document `OidcError` use
  src/oidc/authorize.ts
  src/oidc/error.ts
  src/oidc/index.ts
  src/oidc/register.ts
Labels: T-Task

#3778 Handle backup secret gossip
  spec/integ/crypto/olm-utils.ts
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3810 Element-R: log when we send to-device messages
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Enhancement

#3812 Reduce some log spam from `MatrixRTCSession.callMembershipsForRoom`
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Task

#3815 Move the redaction event to main at the same time we move redacted
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#3814 Don't remove thread info from a thread root when it is redacted
  spec/unit/models/event.spec.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#3818 Refactor & make base64 functions browser-safe
  spec/integ/crypto/verification.spec.ts
  spec/unit/base64.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/secret_request.spec.ts
  spec/unit/rendezvous/ecdhv2.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  src/base64.ts
  src/client.ts
  src/common-crypto/base64.ts
  src/crypto/CrossSigning.ts
  src/crypto/aes.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
  src/crypto/verification/QRCode.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3811 Bump wasm bindings version to 2.1.0
  package.json
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  yarn.lock
Labels: T-Task

#3820 Export base64 utils
  src/matrix.ts
Labels: T-Task

#3819 Reduce log spam from rust crypto
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3821 Element-R: silence log errors when viewing a decryption failure
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3823 Bump matrix-sdk-crypto-wasm to 2.1.1
  package.json
  yarn.lock
Labels: T-Task

#3831 Change latest node ver to '*'
  .github/workflows/tests.yml
Labels: T-Task

#3832 Don't emit a closed event if the indexeddb is closed by Element
  src/store/indexeddb-local-backend.ts
Labels: T-Defect, Z-Community-PR

#3824 Element-R: silence log errors when viewing a pending event
  spec/integ/crypto/crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3805 Element-R: Wire up room history visibility
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  src/rust-crypto/RoomEncryptor.ts
Labels: T-Enhancement

#3825 Element-R: Add current version of the rust-sdk and vodozemac
  spec/unit/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3834 Fix up comments on `globalErrorOnUnknownDevices`
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3807 Element-R: Wire up room rotation
  spec/integ/crypto/crypto.spec.ts
  src/rust-crypto/RoomEncryptor.ts
Labels: T-Enhancement

#3826 Element-R: reduce log spam when checking server key backup
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/test-utils/test-utils.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3790 Element-R: Wire up `globalBlacklistUnverifiedDevices` field to rust crypto encryption settings
  spec/integ/crypto/crypto.spec.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3796 Fix reemitter not being correctly wired on user objects created in storage classes
  spec/integ/matrix-client-event-emitter.spec.ts
  spec/unit/event-mapper.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/stores/indexeddb.spec.ts
  src/client.ts
  src/models/user.ts
  src/store/index.ts
  src/store/indexeddb.ts
  src/store/memory.ts
  src/store/stub.ts
  src/sync.ts
Labels: T-Defect

#3835 feat: Add autoformat and lint for ts/tsx files
  .husky/pre-commit
  .lintstagedrc
  package.json
  yarn.lock
Labels: Z-Community-PR, T-Task

#3837 Use olm from default npm registry, since it's there now
  package.json
  yarn.lock
Labels: T-Task

#3838 Element-R: Add the git sha of the binding crate to `CryptoApi#getVersion`
  package.json
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement

#3667 Add E2EE for embedded mode of Element Call
  spec/unit/base64.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/MatrixRTCSessionManager.spec.ts
  spec/unit/matrixrtc/mocks.ts
  spec/unit/randomstring.spec.ts
  src/@types/event.ts
  src/base64.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
  src/matrixrtc/types.ts
  src/randomstring.ts
Labels: T-Enhancement

#3755 Remove deprecated support for unstable MSC3882
  spec/integ/matrix-client-methods.spec.ts
  src/@types/auth.ts
  src/client.ts
Labels: T-Task
