Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-02, with the labels that each got.

#3114 Move the logic of roomPredecessor into the RoomState class
  src/models/room-state.ts
  src/models/room.ts
Labels: T-Task

#3119 Handle optional last_known_event_id property in m.predecessor
  spec/unit/room.spec.ts
  src/models/room-state.ts
Labels: T-Enhancement

#3072 Poll model - validate end events
  spec/test-utils/client.ts
  spec/unit/models/poll.spec.ts
  src/models/poll.ts
  src/models/room.ts
Labels: T-Enhancement

#3073 Poll model - page /relations results
  spec/unit/models/poll.spec.ts
  src/models/poll.ts
Labels: T-Enhancement

#3117 Element R: Fix obscure errors when we fail to decrypt to-device events
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3120 Work around pion bug to fix screen sharing
  src/webrtc/call.ts
Labels: T-Defect

#3121 Element-R: Fix invite processing
  src/sync.ts
Labels: T-Defect

#3079 Update typescript bits to aid matrix-react-sdk achieve noImplicitAny
  src/@types/another-json.d.ts
  src/autodiscovery.ts
  src/client.ts
  src/interactive-auth.ts
Labels: T-Task

#3122 Element-R: implement encryption of outgoing events
  package.json
  spec/integ/crypto.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/rust-crypto/KeyClaimManager.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/index.ts
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
  yarn.lock
Labels: T-Enhancement

#3126 Element-R: fix a bug which prevented encryption working after a reload
  yarn.lock
Labels: T-Defect

#3127 Element-R: log outgoing HTTP requests
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Task

#3129 Add @typescript-eslint/no-base-to-string
  .eslintrc.js
  package.json
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  yarn.lock
Labels: T-Task

#3131 Messages sent out of order after one message fails
  spec/unit/scheduler.spec.ts
  src/models/room.ts
  src/scheduler.ts
Labels: T-Defect

#3123 Improve WebRTC logging
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/call.ts
  src/webrtc/callEventHandler.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#3139 Clear notifications when we can infer read status from receipts
  spec/integ/matrix-client-unread-notifications.spec.ts
  spec/test-utils/webrtc.ts
  spec/unit/models/thread.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#2973 Add `matrix-org/jest` linting
  .eslintrc.js
  package.json
  spec/TestClient.ts
  spec/integ/crypto.spec.ts
  spec/integ/matrix-client-event-emitter.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-opts.spec.ts
  spec/integ/matrix-client-retrying.spec.ts
  spec/integ/matrix-client-room-timeline.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/unit/ToDeviceMessageQueue.spec.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/DeviceList.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/crypto/cross-signing.spec.ts
  spec/unit/event-timeline-set.spec.ts
  spec/unit/extensible_events_v1/PollResponseEvent.spec.ts
  spec/unit/interactive-auth.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/poll.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/rendezvous/ecdh.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  spec/unit/rendezvous/simpleHttpTransport.spec.ts
  spec/unit/room.spec.ts
  spec/unit/scheduler.spec.ts
  spec/unit/utils.spec.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/mediaHandler.spec.ts
  yarn.lock
Labels: T-Task

#3144 Re-use transceivers for user media
  src/webrtc/call.ts
Labels: T-Defect

#3147 Stop the ICE disconnected timer on call terminate
  src/webrtc/call.ts
Labels: T-Defect

#3149 Include 'browser' in list of adjusted properties in release.sh
  post-release.sh
  release.sh
Labels: T-Task, backport staging

#3148 Poll history: decrypt poll relations before processing
  spec/unit/models/poll.spec.ts
  src/models/poll.ts
Labels: T-Task

#3142 Switch `crypto.spec.ts` away from `TestClient` and `matrix-mock-request`.
  package.json
  spec/TestClient.ts
  spec/integ/crypto.spec.ts
  spec/integ/olm-encryption-spec.ts
  spec/test-utils/E2EKeyReceiver.ts
  spec/test-utils/SyncResponder.ts
  src/@types/crypto.ts
  src/client.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/crypto/olmlib.ts
  yarn.lock
Labels: T-Task

#3130 Fix notification counts for encrypted rooms with ignored event rules
  spec/unit/notifications.spec.ts
  src/client.ts
  src/sync.ts
Labels: T-Defect

#3156 Iterate types
  src/client.ts
  src/crypto/index.ts
Labels: T-Task

#3159 Fix predecessor types, nowhere does the spec say it can be `null`
  spec/unit/room.spec.ts
  src/models/room-state.ts
  src/models/room.ts
Labels: T-Task

#3163 Polls: count undecryptable poll relations
  spec/unit/models/poll.spec.ts
  src/models/poll.ts
Labels: T-Enhancement

#3165 Better type guard parseTopicContent
  src/content-helpers.ts
Labels: T-Defect, X-Release-Blocker

#3161 Run matrix-react-sdk tests on merge queue
  .editorconfig
  .github/workflows/pull_request.yaml
  .github/workflows/static_analysis.yml
  .github/workflows/tests.yml
Labels: T-Task

#3167 Add easy way to determine if the decryption failure is due to "DecryptionError: The sender has disabled encrypting to unverified devices."
  spec/unit/models/event.spec.ts
  src/@types/crypto.ts
  src/models/event.ts
Labels: T-Enhancement

#3175 Improve types
  spec/integ/matrix-client-methods.spec.ts
  src/@types/IIdentityServerProvider.ts
  src/client.ts
  src/http-api/fetch.ts
Labels: T-Task

#3146 Fix reactions in threads sometimes causing stuck notifications
  spec/integ/matrix-client-unread-notifications.spec.ts
  src/models/room.ts
Labels: T-Defect

#3178 Fix spec compliance issue around encrypted `m.relates_to`
  spec/unit/models/event.spec.ts
  src/models/event.ts
Labels: T-Defect
