Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-06, with the labels that each got.

#3417 mention deno support in the README
  README.md
Labels: T-Enhancement, Z-Community-PR

#3413 Add remote user and call id in webrtc call stats
  spec/unit/webrtc/stats/callStatsReportGatherer.spec.ts
  src/webrtc/call.ts
  src/webrtc/stats/callStatsReportGatherer.ts
  src/webrtc/stats/groupCallStats.ts
  src/webrtc/stats/statsReport.ts
Labels: T-Task

#3427 Ensure we do not add relations to the wrong timeline
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/matrix-client-unread-notifications.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/unit/models/thread.spec.ts
  spec/unit/room.spec.ts
  src/@types/event.ts
  src/client.ts
  src/models/event.ts
  src/models/room.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Defect, X-Breaking-Change

#3429 Export FALLBACK_ICE_SERVER
  src/webrtc/call.ts
Labels: T-Task

#3440 Always show a summary after Jest tests
  jest.config.ts
Labels: T-Task

#3016 Use correct /v3 prefix for /refresh
  spec/unit/login.spec.ts
  src/client.ts
Labels: T-Enhancement, Z-Community-PR

#3381 Update Mutual Rooms (MSC2666) support
  spec/unit/room-member.spec.ts
  src/client.ts
Labels: Z-Community-PR, T-Task

#3412 GHA: build and cypress-test a copy of element-web after each push
  .github/workflows/cypress.yml
  .github/workflows/downstream-artifacts.yml
Labels: T-Task

#3443 Fix downstream-artifacts build
  .github/workflows/cypress.yml
  .github/workflows/downstream-artifacts.yml
Labels: T-Task

#3442 Make sliding sync linearize processing of sync requests
  spec/integ/sliding-sync-sdk.spec.ts
  src/models/typed-event-emitter.ts
  src/sliding-sync-sdk.ts
  src/sliding-sync.ts
Labels: T-Defect

#3444 Disable downstream artifacts build for develop branch
  .github/workflows/downstream-artifacts.yml
Labels: T-Task

#3447 Export thread-related types from SDK
  src/matrix.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Enhancement, Z-Community-PR, X-Breaking-Change

#3439 Integration test for QR code verification
  spec/integ/crypto/verification.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
Labels: T-Task

#3422 Add `getShowSasCallbacks`, `getShowQrCodeCallbacks` to VerifierBase
  spec/integ/crypto/verification.spec.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/QRCode.ts
  src/crypto/verification/SAS.ts
Labels: T-Task

#3445 use cli.canSupport to determine intentional mentions support
  src/client.ts
  src/feature.ts
Labels: T-Defect

#3420 Update MSC3912 implementation to use `with_rel_type` instead of `with_relations`
  spec/unit/matrix-client.spec.ts
  src/@types/event.ts
  src/@types/requests.ts
  src/client.ts
Labels: T-Enhancement

#3441 Add new methods to VerificationRequest
  spec/integ/crypto/verification.spec.ts
  src/crypto/verification/request/VerificationRequest.ts
Labels: T-Task

#3421 Expand webrtc stats with connection and call feed track information
  spec/test-utils/webrtcReports.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/stats/__snapshots__/callFeedStatsReporter.spec.ts.snap
  spec/unit/webrtc/stats/callFeedStatsReporter.spec.ts
  spec/unit/webrtc/stats/callStatsReportGatherer.spec.ts
  spec/unit/webrtc/stats/statsReportEmitter.spec.ts
  src/webrtc/groupCall.ts
  src/webrtc/stats/callFeedStatsReporter.ts
  src/webrtc/stats/callStatsReportGatherer.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportEmitter.ts
Labels: T-Task

#3453 Update `@matrix-org/matrix-sdk-crypto-js` to `0.1.0-alpha.10`
  package.json
  yarn.lock
Labels: T-Task

#3455 Fix: handle `baseUrl` with trailing slash in `fetch.getUrl`
  spec/unit/http-api/fetch.spec.ts
  src/http-api/fetch.ts
Labels: T-Defect

#3458 Fix thread list being ordered based on all updates
  spec/integ/matrix-client-event-timeline.spec.ts
  src/models/room.ts
Labels: T-Defect, X-Release-Blocker

#3414 Element-R: Pull out an interface from `VerificationBase`
  spec/integ/crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/QRCode.ts
  src/crypto/verification/SAS.ts
Labels: T-Deprecation

#3461 Pass Kiwi secrets to react-sdk Cypress build
  .github/workflows/cypress.yml
Labels: T-Task

#3452 ElementR: Add `CryptoApi.getCrossSigningStatus`
  spec/integ/crypto/cross-signing.spec.ts
  spec/unit/rust-crypto/secret-storage.spec.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/secret-storage.ts
Labels: T-Enhancement

#3419 OIDC: Validate `m.authentication` configuration
  spec/unit/autodiscovery.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/autodiscovery.ts
  src/client.ts
  src/oidc/validate.ts
Labels: T-Enhancement

#3462 Add `rust-crypto#isCrossSigningReady` implementation
  spec/integ/crypto/cross-signing.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3364 Element-R: support for manual import/export of Room keys
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3449 Pull out a new `VerificationRequest` interface
  spec/integ/crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/crypto/verification/request/VerificationRequest.ts
Labels: T-Deprecation

#3456 Upgrade JS-DevTools/npm-publish to v2.2.0
  .github/workflows/release-npm.yml
Labels: Z-Community-PR, T-Task

#3472 ElementR: Add `rust-crypto#createRecoveryKeyFromPassphrase` implementation
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api.ts
  src/crypto/api.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3474 Add new methods for verification to `CryptoApi`
  spec/integ/crypto/verification.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Deprecation

#3475 Fix: remove polls from room state on redaction
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Defect

#3480 Specify git tags for cypress workflow so updating tests is gated by renovate PRs
  .github/workflows/cypress.yml
  .github/workflows/downstream-artifacts.yml
Labels: T-Task

#3488 Element-R: implement `userHasCrossSigningKeys`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3491 Fix order of things in `crypto-api.ts`
  src/crypto-api.ts
Labels: T-Task

#3483 ElementR: Add `CryptoApi#bootstrapSecretStorage`
  .eslintrc.js
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto-api/keybackup.ts
  src/crypto/api.ts
  src/crypto/index.ts
  src/crypto/keybackup.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement, T-Deprecation

#3487 Element-R: wait for OlmMachine on startup
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/index.ts
Labels: T-Task

#3489 Fix bug where switching media caused media in subsequent calls to fail
  src/webrtc/mediaHandler.ts
Labels: T-Defect

#3494 Add debug logging to figure out missing reactions in main timeline
  src/logger.ts
  src/models/room.ts
Labels: T-Task

#3493 Add getLastUnthreadedReceiptFor utility to Thread delegating to the underlying Room
  src/models/event-timeline-set.ts
  src/models/read-receipt.ts
  src/models/thread.ts
Labels: T-Enhancement

#3481 OIDC: add dynamic client registration util function
  spec/unit/autodiscovery.spec.ts
  spec/unit/oidc/register.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/autodiscovery.ts
  src/oidc/error.ts
  src/oidc/register.ts
  src/oidc/validate.ts
Labels: T-Enhancement

#3492 Element-R: speed up slow unit test
  spec/unit/rust-crypto/rust-crypto.spec.ts
Labels: T-Task

#3500 Increase crypto test timeout
  spec/integ/crypto/crypto.spec.ts
Labels: T-Task

#3498 Element-R: Store cross signing keys in secret storage
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/mockEndpoints.ts
  src/client.ts
  src/crypto-api.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3496 Aggregate relations regardless of whether event fits into the timeline
  spec/unit/event-timeline-set.spec.ts
  src/models/event-timeline-set.ts
  src/models/room.ts
Labels: T-Defect, X-Release-Blocker

#3490 Element-R: Basic implementation of SAS verification
  package.json
  spec/integ/crypto/verification.spec.ts
  spec/test-utils/E2EKeyReceiver.ts
  spec/test-utils/E2EKeyResponder.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
  yarn.lock
Labels: T-Enhancement

#3501 Bump version of the react-sdk cypress workflow file
  .github/workflows/cypress.yml
Labels: T-Task

#3503 Element R: Implement `requestOwnUserVerification`
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3508 Element R: Implement `requestOwnUserVerification`
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3504 Rearrange the verification integration tests, again
  spec/integ/crypto/verification.spec.ts
Labels: T-Task

#3505 Element-R: implement cancellation of verification requests
  spec/integ/crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/rust-crypto/verification.ts
Labels: T-Enhancement

#3515 Further fixes to test timeouts
  spec/integ/crypto/verification.spec.ts
Labels: T-Task

#3499 OIDC: navigate to authorization endpoint
  spec/unit/oidc/authorize.spec.ts
  src/client.ts
  src/oidc/authorize.ts
  src/oidc/error.ts
Labels: T-Enhancement

#3509 Increase another crypto test timeout
  spec/unit/rust-crypto/rust-crypto.spec.ts
Labels: T-Task

#3514 Create a new event type for verification requests
  spec/integ/crypto/verification.spec.ts
  src/client.ts
  src/crypto/index.ts
Labels: T-Deprecation

#3510 Improve types to match reality around old identity servers
  src/@types/requests.ts
  src/client.ts
Labels: T-Task

#3523 Use the right smiley in emoji verification
  src/crypto/verification/SAS.ts
Labels: T-Defect

#3525 Rust crypto: emit `VerificationRequestReceived` events
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3527 QRCode: fix breakage on node 16
  spec/integ/crypto/verification.spec.ts
  src/crypto/verification/QRCode.ts
Labels: T-Task

#3528 Element-R: support for starting a SAS verification
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/verification.spec.ts
  src/crypto-api/verification.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/rust-crypto/verification.ts
Labels: T-Deprecation

#3533 Drop support for Node 16
  .github/workflows/tests.yml
  package.json
Labels: T-Deprecation

#3534 Use the right anchor emoji for SAS verification
  src/crypto/verification/SAS.ts
Labels: T-Defect
