Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-03, with the labels that each got.

#3134 Implement MSC3873 to handle escaped dots in push rule keys
  spec/unit/pushprocessor.spec.ts
  src/client.ts
  src/pushprocessor.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Enhancement

#3181 Polls push rules
  spec/unit/pushprocessor.spec.ts
  src/@types/PushRules.ts
  src/pushprocessor.ts
Labels: T-Task

#3184 Remove experimental support for MSC3903 v1
  spec/unit/rendezvous/ecdhv1.spec.ts
  src/rendezvous/channels/MSC3903ECDHv1RendezvousChannel.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
  src/rendezvous/channels/index.ts
Labels: T-Task

#3162 Enable group calls without video and audio track by configuration of MatrixClient
  .gitignore
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/mediaHandler.spec.ts
  src/client.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
  src/webrtc/mediaHandler.ts
Labels: T-Enhancement, T-Task

#2982 Stop requesting room keys from other users
  spec/unit/crypto.spec.ts
  src/crypto/algorithms/megolm.ts
  src/models/event.ts
Labels: T-Task

#3186 Fix: braking changes with GroupCall and ensure backwards-compatibility
  spec/unit/webrtc/groupCall.spec.ts
  src/client.ts
  src/webrtc/groupCall.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Task

#3187 Stub out the rust crypto implementation for browserify
  package.json
  src/rust-crypto/browserify-index.ts
  yarn.lock
Labels: T-Task

#3185 Room call push rule should be an underride, not an override.
  spec/unit/pushprocessor.spec.ts
Labels: T-Task

#3190 Remove items incorrectly included in changelog for 23.4.0
  CHANGELOG.md
Labels: T-Task

#3179 Implement MSC3758: a push rule condition to match event properties exactly
  spec/unit/pushprocessor.spec.ts
  src/@types/PushRules.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#3194 Fix jest/no-conditional-expect lint and enable it
  .eslintrc.js
  spec/integ/matrix-client-opts.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/unit/NamespacedValue.spec.ts
  spec/unit/crypto/CrossSigningInfo.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/MSC3089Branch.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/pushprocessor.spec.ts
  spec/unit/room.spec.ts
  spec/unit/scheduler.spec.ts
Labels: T-Task

#2391 Add GHA for requiring all reviews to be dismissed or approving before merging
  .github/workflows/pending_reviews.yml
Labels: T-Task

#3180 Implement MSC3966: a push rule condition to check if an array contains a value
  spec/unit/pushprocessor.spec.ts
  src/@types/PushRules.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#3201 adjust beacon model to make beaconInfo definitely assigned in constructor
  src/models/beacon.ts
Labels: T-Task

#3202 Fixes to event encryption in the Rust Crypto implementation
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#3208 Pin versions of third-party github actions
  .github/workflows/backport.yml
  .github/workflows/docs-pr-netlify.yaml
  .github/workflows/notify-downstream.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
  .github/workflows/tests.yml
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#3214 Fix CallOpts types
  src/webrtc/call.ts
Labels: T-Task

#3217 Add a type to the structure used by the SendVoipEvent event
  src/webrtc/call.ts
Labels: T-Task

#3205 Add WebRTC media stats collector
  .gitignore
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/stats/connectionStatsReporter.spec.ts
  spec/unit/webrtc/stats/groupCallStats.spec.ts
  spec/unit/webrtc/stats/media/mediaSsrcHandler.spec.ts
  spec/unit/webrtc/stats/media/mediaTrackHandler.spec.ts
  spec/unit/webrtc/stats/media/mediaTrackStatsHandler.spec.ts
  spec/unit/webrtc/stats/statsCollector.spec.ts
  spec/unit/webrtc/stats/statsReportBuilder.spec.ts
  spec/unit/webrtc/stats/statsReportEmitter.spec.ts
  spec/unit/webrtc/stats/statsValueFormatter.spec.ts
  spec/unit/webrtc/stats/trackStatsReporter.spec.ts
  spec/unit/webrtc/stats/transportStatsReporter.spec.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
  src/webrtc/stats/connectionStats.ts
  src/webrtc/stats/connectionStatsReporter.ts
  src/webrtc/stats/groupCallStats.ts
  src/webrtc/stats/media/mediaSsrcHandler.ts
  src/webrtc/stats/media/mediaTrackHandler.ts
  src/webrtc/stats/media/mediaTrackStats.ts
  src/webrtc/stats/media/mediaTrackStatsHandler.ts
  src/webrtc/stats/statsCollector.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportBuilder.ts
  src/webrtc/stats/statsReportEmitter.ts
  src/webrtc/stats/statsValueFormatter.ts
  src/webrtc/stats/trackStatsReporter.ts
  src/webrtc/stats/transportStats.ts
  src/webrtc/stats/transportStatsReporter.ts
Labels: T-Task

#3219 Update matrix-widget-api
  package.json
  yarn.lock
Labels: T-Task

#3203 Add a new test for event encryption, which works with rust
  package.json
  spec/integ/crypto.spec.ts
  yarn.lock
Labels: T-Task

#3223 Export `TimestampToEventResponse` to use in `matrix-react-sdk` tests
  src/client.ts
Labels: T-Task

#3224 Exporting live WebRTC metric as GroupCall Event from SDK #3220
  spec/unit/webrtc/stats/statsCollector.spec.ts
  spec/unit/webrtc/stats/statsReportEmitter.spec.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
  src/webrtc/stats/statsCollector.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportEmitter.ts
Labels: T-Task

#3215 Send one time key count and unused fallback keys for rust-crypto
  spec/integ/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/sync.ts
Labels: T-Enhancement

#3092 Implement MSC3952: intentional mentions
  spec/unit/pushprocessor.spec.ts
  src/@types/PushRules.ts
  src/client.ts
  src/models/event.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#3227 Stop doing O(n^2) work to find event's home
  src/models/room.ts
Labels: T-Defect, Z-Community-PR

#3225 Enable the `prepareToEncrypt` test for Element-R
  spec/integ/crypto.spec.ts
Labels: T-Task

#3231 Handle group call redaction
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
  src/webrtc/groupCallEventHandler.ts
Labels: T-Defect

#3233 Run prettier on groupCall.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#3229 Add the call object to Call events
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#3235 Update changelog for v24.0.0 now the security issue is public
  CHANGELOG.md
Labels: T-Task

#3209 Element-R: Add support for `/discardsession`
  spec/integ/crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3237 Re-apply "Add the call object to Call events"
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/callFeed.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#3234 Refactor the way group calls hang up
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#3218 Fire `closed` event when IndexedDB closes unexpectedly
  spec/unit/stores/indexeddb-store-worker.spec.ts
  spec/unit/stores/indexeddb.spec.ts
  src/store/index.ts
  src/store/indexeddb-backend.ts
  src/store/indexeddb-local-backend.ts
  src/store/indexeddb-remote-backend.ts
  src/store/indexeddb-store-worker.ts
  src/store/indexeddb.ts
Labels: T-Enhancement

#3240 Allow via_servers property in findPredecessor (update to MSC3946)
  spec/unit/room.spec.ts
  src/models/room-state.ts
  src/models/room.ts
Labels: T-Enhancement
