Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-01, with the labels that each got.

#3006 Update comment for `m.key.verification.ready` event type definition
  src/@types/event.ts
Labels: T-Task

#3003 Remove usage of v1 Identity Server API
  spec/unit/autodiscovery.spec.ts
  src/autodiscovery.ts
  src/http-api/prefix.ts
Labels: T-Enhancement

#3017 In release.yml use an env section to get ref_name
  .github/workflows/release.yml
Labels: T-Defect

#3009 Factor `SyncApi` options out of `IStoredClientOptions`
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  src/client.ts
  src/embedded.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Task

#3004 Avoid triggering decryption errors when decrypting redacted events
  spec/unit/crypto.spec.ts
  src/crypto/index.ts
Labels: T-Defect

#3019 Handle outgoing requests from rust crypto SDK
  spec/unit/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3022 Avoid logical assignment operator
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3023 Indirect event decryption attempts via Client
  src/models/room.ts
Labels: T-Task

#3021 Pass to-device messages into rust crypto-sdk
  spec/unit/rust-crypto.spec.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/index.ts
  src/event-mapper.ts
  src/rust-crypto/rust-crypto.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Task

#3029 Fix false key requests after verifying new device
  spec/unit/crypto/verification/setDeviceVerification.spec.ts
  src/crypto/index.ts
Labels: T-Defect

#3025 Fix outgoing messages for rust-crypto
  spec/unit/rust-crypto.spec.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3024 Make error handling in decryptionLoop more generic
  spec/unit/models/event.spec.ts
  src/models/event.ts
Labels: T-Task

#3026 Fix threaded cache receipt when event holds multiple receipts
  spec/integ/matrix-client-syncing.spec.ts
  src/@types/read_receipts.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#3034 Make poll start event type available (PSG-962)
  src/@types/event.ts
Labels: T-Enhancement

#3028 Remove video track when muting video
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/mediaHandler.spec.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
  src/webrtc/mediaHandler.ts
Labels: T-Enhancement

#3033 Remove 'qs' dependency
  package.json
  yarn.lock
Labels: Z-Community-PR, T-Task

#2915 Prefer stable `/timestamp_to_event` endpoint first - MSC3030
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Task

#3038 Tests for getVisibleRooms
  spec/unit/matrix-client.spec.ts
Labels: T-Task

#3039 Factor out a (public) function to find a room's predecessor
  spec/unit/room.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Task

#3040 Remove extensible events v1 field population on legacy events
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Deprecation

#3031 Improve hasUserReadEvent and getUserReadUpTo realibility with threads
  spec/unit/models/thread.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/room.spec.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Enhancement

#3050 Avoid use of mkdirp
  package.json
Labels: T-Task

#3049 Fix dated example
  README.md
Labels: T-Task

#3051 Fix browser entrypoint
  package.json
Labels: T-Defect, X-Release-Blocker, backport staging

#3052 [Release] Fix browser entrypoint
  package.json
Labels: T-Defect, X-Release-Blocker

#3047 Add proper (un)subscribe logic
  spec/unit/webrtc/call.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#3045 Handle edits which are bundled with an event, per MSC3925
  src/event-mapper.ts
Labels: T-Enhancement

#3043 Improve logging in legacy megolm code
  spec/unit/crypto/algorithms/megolm.spec.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Task

#3058 Fix failure to start in firefox private browser
  src/client.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#3060 Improvements to megolm integration tests
  spec/integ/megolm-integ.spec.ts
Labels: T-Task

#3061 Fix spurious "Decryption key withheld" messages
  spec/integ/megolm-integ.spec.ts
  src/crypto/algorithms/megolm.ts
Labels: T-Defect

#3062 Extract v1 extensible events polls types out of the events-sdk
  spec/unit/content-helpers.spec.ts
  spec/unit/extensible_events_v1/ExtensibleEvent.spec.ts
  spec/unit/extensible_events_v1/MessageEvent.spec.ts
  spec/unit/extensible_events_v1/PollEndEvent.spec.ts
  spec/unit/extensible_events_v1/PollResponseEvent.spec.ts
  spec/unit/extensible_events_v1/PollStartEvent.spec.ts
  spec/unit/extensible_events_v1/utilities.spec.ts
  spec/unit/location.spec.ts
  spec/unit/models/beacon.spec.ts
  spec/unit/relations.spec.ts
  src/@types/beacon.ts
  src/@types/extensible_events.ts
  src/@types/location.ts
  src/@types/polls.ts
  src/@types/topic.ts
  src/content-helpers.ts
  src/extensible_events_v1/ExtensibleEvent.ts
  src/extensible_events_v1/InvalidEventError.ts
  src/extensible_events_v1/MessageEvent.ts
  src/extensible_events_v1/PollEndEvent.ts
  src/extensible_events_v1/PollResponseEvent.ts
  src/extensible_events_v1/PollStartEvent.ts
  src/extensible_events_v1/utilities.ts
Labels: T-Task

#3065 Fix typos in `src/webrtc/`
  spec/unit/webrtc/call.spec.ts
  src/webrtc/call.ts
  src/webrtc/callFeed.ts
  src/webrtc/groupCall.ts
Labels: T-Task

#3066 Add some debugging & a debug event for decryption
  spec/unit/crypto.spec.ts
  src/client.ts
  src/crypto/OlmDevice.ts
  src/crypto/index.ts
Labels: T-Task

#3056 Correctly handle limited sync responses by resetting the thread timeline
  spec/unit/models/thread.spec.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#3070 Remove brokenheaded encryption test
  spec/integ/megolm-integ.spec.ts
Labels: T-Task

#3075 Element-R: stub implementations of some methods
  spec/unit/rust-crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3074 Implement decryption via the rust sdk
  spec/TestClient.ts
  spec/integ/megolm-integ.spec.ts
  spec/test-utils/test-utils.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3077 Rename some of the .spec files which test crypto
  spec/integ/crypto.spec.ts
  spec/integ/olm-encryption-spec.ts
Labels: T-Task

#3078 Handle group call getting initialised twice in quick succession
  src/webrtc/groupCall.ts
  src/webrtc/mediaHandler.ts
Labels: T-Defect

#3080 replace .at(-1) with array.length-1
  src/models/thread.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#3082 Add null check for our own member event
  src/webrtc/groupCall.ts
Labels: T-Defect

#3076 refactor: sliding sync: swap to lists-as-keys
  spec/integ/sliding-sync-sdk.spec.ts
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Task

#3086 refactor: sliding sync: swap to lists-as-keys
  spec/integ/sliding-sync-sdk.spec.ts
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync.ts
Labels: T-Task

#3087 Always subscribe to audio tracks
  src/webrtc/call.ts
Labels: T-Defect

#3088 Tests for getRoomUpgradeHistory
  spec/unit/matrix-client.spec.ts
Labels: T-Task

#3089 Fix "verifyLinks" functionality of getRoomUpgradeHistory
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Defect

#3035 Reduce Megolm blocking and add cancellation
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/utils.spec.ts
  src/crypto/algorithms/megolm.ts
  src/utils.ts
Labels: T-Enhancement, Z-Community-PR

#3090 Refactor getRoomUpgradeHistory to use Room.findPredecessorRoomId
  src/client.ts
Labels: T-Task

#3093 Don't forget about simulcast in `updateLocalUsermediaStream()`
  src/webrtc/call.ts
Labels: T-Defect

#3094 Fix volume indicators and speaker detection not working in SFU mode
  src/webrtc/callFeed.ts
Labels: T-Defect

#3098 Remove flaky megolm test
  spec/unit/crypto/algorithms/megolm.spec.ts
Labels: T-Defect, Z-Community-PR

#3091 Remove video tracks on video mute without renegotiating
  spec/unit/webrtc/call.spec.ts
  src/webrtc/call.ts
Labels: T-Enhancement

#3042 MSC3946 Dynamic room predecessors
  spec/unit/matrix-client.spec.ts
  spec/unit/room.spec.ts
  src/@types/event.ts
  src/client.ts
  src/models/room.ts
Labels: T-Enhancement

#3095 Provide eventId as well as roomId from Room.findPredecessor
  spec/unit/room.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Enhancement

#3107 Don't throw with no `opponentDeviceInfo`
  src/webrtc/call.ts
Labels: T-Defect

#3109 Fix simulcast on chrome
  src/webrtc/call.ts
Labels: T-Defect

#3064 Stop labelling threads as experimental
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/test-utils/webrtc.ts
  spec/unit/event-timeline-set.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/thread.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
  src/sync.ts
Labels: T-Task

#3101 Add support for stable identifier for fixed MAC in SAS verification
  spec/unit/crypto/verification/sas.spec.ts
  src/crypto/verification/SAS.ts
Labels: T-Enhancement

#3083 Element-R: implement remaining OutgoingMessage request types
  package.json
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#3118 Don't require e2e keys for foci
  src/webrtc/call.ts
Labels: T-Defect

#3115 Cleanup pre MSC3773 thread unread notif logic
  spec/unit/read-receipt.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Task
