Repository matrix-org/matrix-js-sdk, pull requests merged in 2023-04, with the labels that each got.

#3239 Remove redundant "default" module in generated typedoc.
  tsconfig.json
Labels: T-Task

#3242 Split up, rename, and move `ISecretStorageKeyInfo`
  spec/unit/crypto/secrets.spec.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/SecretStorage.ts
  src/crypto/api.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/matrix.ts
  src/secret-storage.ts
Labels: T-Task

#3247 Skip sonarcloud & coverage in merge_queue
  .github/workflows/sonarqube.yml
  .github/workflows/tests.yml
Labels: T-Task

#3222 indexddb-local-backend - return the current sync to database promise …
  src/store/indexeddb-local-backend.ts
Labels: T-Defect, Z-Community-PR

#3241 indicator whether call members send media.
  spec/unit/webrtc/stats/groupCallStats.spec.ts
  spec/unit/webrtc/stats/statsReportEmitter.spec.ts
  spec/unit/webrtc/stats/statsReportGatherer.spec.ts
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  src/webrtc/groupCall.ts
  src/webrtc/stats/groupCallStats.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportEmitter.ts
  src/webrtc/stats/statsReportGatherer.ts
  src/webrtc/stats/summaryStats.ts
  src/webrtc/stats/summaryStatsReporter.ts
Labels: T-Task

#3251 Add an event emitted when a Call creates a PeerConnection
  src/webrtc/call.ts
Labels: T-Task

#3230 Element-R: handle events which arrive before their keys
  package.json
  spec/integ/crypto.spec.ts
  spec/test-utils/test-utils.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Defect

#3244 Move `SecretStorage`-related interfaces out to new module
  spec/unit/crypto/secrets.spec.ts
  src/client.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/SecretStorage.ts
  src/crypto/api.ts
  src/crypto/index.ts
  src/secret-storage.ts
Labels: T-Task

#3252 Tidy up merge queue automation
  .github/workflows/tests.yml
Labels: T-Task

#3253 Use `processKeyCounts` in sliding sync
  spec/integ/sliding-sync-sdk.spec.ts
  src/crypto/index.ts
  src/sliding-sync-sdk.ts
Labels: T-Task

#3228 Support for MSC3882 revision 1
  spec/integ/matrix-client-methods.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  src/@types/auth.ts
  src/client.ts
  src/feature.ts
  src/rendezvous/MSC3906Rendezvous.ts
Labels: T-Enhancement

#3265 Fix another export type
  src/crypto/SecretStorage.ts
Labels: T-Task

#3255 Handle concurrency in merge_queues better
  .github/workflows/pull_request.yaml
Labels: T-Task

#3264 Switch away from peter-evans/enable-pull-request-automerge
  .github/workflows/upgrade_dependencies.yml
Labels: T-Task

#3249 Measure whether we receive media and add the mute state as an exception
  spec/unit/webrtc/stats/groupCallStats.spec.ts
  spec/unit/webrtc/stats/media/mediaSsrcHandler.spec.ts
  spec/unit/webrtc/stats/media/mediaTrackHandler.spec.ts
  spec/unit/webrtc/stats/media/mediaTrackStatsHandler.spec.ts
  spec/unit/webrtc/stats/statsReportGatherer.spec.ts
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  spec/unit/webrtc/stats/trackStatsReporter.spec.ts
  src/webrtc/stats/media/mediaTrackHandler.ts
  src/webrtc/stats/media/mediaTrackStats.ts
  src/webrtc/stats/media/mediaTrackStatsHandler.ts
  src/webrtc/stats/statsReportGatherer.ts
  src/webrtc/stats/summaryStats.ts
  src/webrtc/stats/summaryStatsReporter.ts
  src/webrtc/stats/trackStatsReporter.ts
Labels: T-Task

#3246 Retry processing potential poll events after decryption
  spec/unit/models/poll.spec.ts
  spec/unit/room.spec.ts
  src/models/poll.ts
  src/models/room.ts
Labels: T-Defect

#3266 Export type for return of getCapabilities()
  src/client.ts
Labels: T-Task

#3254 Element-R: pass device list change notifications into rust crypto-sdk
  spec/integ/sliding-sync-sdk.spec.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  src/sliding-sync-sdk.ts
  src/sync-accumulator.ts
  src/sync.ts
Labels: T-Enhancement

#3221 Change `Store.save()` to return a `Promise`
  src/store/index.ts
  src/store/memory.ts
  src/store/stub.ts
  src/sync.ts
Labels: T-Defect, Z-Community-PR, X-Breaking-Change

#3269 Improve output in github actions for jest tests
  .github/workflows/tests.yml
  jest.config.ts
  package.json
  yarn.lock
Labels: T-Task

#3267 Split `SecretStorage` into two parts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/secret-storage.spec.ts
  src/crypto/CrossSigning.ts
  src/crypto/SecretSharing.ts
  src/crypto/SecretStorage.ts
  src/crypto/index.ts
  src/secret-storage.ts
Labels: T-Task

#3271 Update types to match reality
  src/client.ts
  src/http-api/fetch.ts
  src/pushprocessor.ts
Labels: T-Task

#3273 Element-R: fix to device list change notifications
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3274 Typescript fix to `AccountDataClient`
  spec/unit/secret-storage.spec.ts
  src/crypto/EncryptionSetup.ts
  src/secret-storage.ts
Labels: T-Task

#3275 Fix typedoc warnings
  .github/workflows/static_analysis.yml
  src/client.ts
  src/crypto/index.ts
  src/crypto/store/base.ts
  src/interactive-auth.ts
  src/matrix.ts
  src/models/room.ts
Labels: T-Task

#3277 Add missing methods to `ServerSideSecretStorgage`
  src/secret-storage.ts
Labels: T-Task

#3278 OutgoingRoomKeyRequest is only a type
  src/matrix.ts
Labels: T-Task

#3270 Add Jitter to exported webrtc stats
  spec/unit/webrtc/stats/statsReportBuilder.spec.ts
  spec/unit/webrtc/stats/trackStatsReporter.spec.ts
  src/webrtc/stats/media/mediaTrackStats.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportBuilder.ts
  src/webrtc/stats/statsReportGatherer.ts
  src/webrtc/stats/trackStatsReporter.ts
Labels: T-Task

#3276 Remove `eventNames` from `TypedEventEmitter`
  src/models/typed-event-emitter.ts
Labels: T-Task

#3280 Expose ServerSideSecretStorage independently of Crypto
  spec/unit/crypto.spec.ts
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/crypto/index.ts
  src/secret-storage.ts
Labels: T-Task

#3279 Add Room.threadsTimelineSets doc
  src/models/room.ts
Labels: T-Task

#3282 Fix screen sharing on Firefox 113
  src/webrtc/call.ts
Labels: T-Defect, Z-Community-PR

#3283 unit test paginating /notifications
  spec/unit/matrix-client.spec.ts
Labels: T-Task

#3284 Annotate events with executed push rule
  spec/unit/matrix-client.spec.ts
  spec/unit/models/event.spec.ts
  spec/unit/pushprocessor.spec.ts
  src/client.ts
  src/models/event.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#3292 Add typedoc-plugin-mdn-links
  package.json
  yarn.lock
Labels: T-Enhancement

#3281 Element-R: implement `{get,set}TrustCrossSignedDevices`
  spec/integ/matrix-client-methods.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3293 Add max jitter and max packet loss
  spec/unit/webrtc/stats/statsReportGatherer.spec.ts
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  spec/unit/webrtc/stats/trackStatsReporter.spec.ts
  src/webrtc/stats/statsReport.ts
  src/webrtc/stats/statsReportGatherer.ts
  src/webrtc/stats/summaryStats.ts
  src/webrtc/stats/summaryStatsReporter.ts
  src/webrtc/stats/trackStatsReporter.ts
Labels: T-Task

#3287 New `CryptoApi.getDeviceVerificationStatus` api
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/CrossSigning.ts
  src/crypto/index.ts
  src/matrix.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3289 Use typedoc-plugin-versions
  .github/workflows/release.yml
  .github/workflows/static_analysis.yml
  package.json
  yarn.lock
Labels: T-Task

#3285 Fix TimelineWindow getEvents exploding if no neigbouring timeline
  src/timeline-window.ts
Labels: T-Defect

#3301 stats: calculate received media and ignore not added tracks
  spec/unit/webrtc/stats/summaryStatsReporter.spec.ts
  src/webrtc/stats/summaryStatsReporter.ts
Labels: T-Task

#3291 Add proper deprecation doc to room fields
  src/models/room.ts
Labels: T-Task

#3305 Improve types
  src/client.ts
Labels: T-Task

#3152 Increase log level for scheduler
  src/scheduler.ts
Labels: T-Task

#3309 Update `@matrix-org/matrix-sdk-crypto-js` to `0.1.0-alpha.7`
  package.json
  yarn.lock
Labels: T-Task

#3272 Element-R: wire up device lists
  spec/integ/crypto.spec.ts
  spec/unit/crypto/device-converter.spec.ts
  spec/unit/rust-crypto/device-converter.spec.ts
  src/crypto-api.ts
  src/crypto/device-converter.ts
  src/crypto/deviceinfo.ts
  src/crypto/index.ts
  src/matrix.ts
  src/models/device.ts
  src/rust-crypto/device-converter.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#3311 `DeviceVerificationStatus`: add new `signedByOwner` property
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api.ts
  src/crypto/CrossSigning.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3308 Add some comments to `OlmDecryption.decryptEvent`
  src/crypto/algorithms/olm.ts
Labels: T-Task

#3316 Deprecate MatrixClient::resolveRoomAlias
  src/client.ts
Labels: T-Deprecation

#3318 Fix lack of media when a user reconnects
  spec/unit/webrtc/groupCall.spec.ts
  src/webrtc/groupCall.ts
Labels: T-Defect

#3314 Adjust negotiation process for pending answer process
  src/webrtc/call.ts
Labels: T-Task

#3319 Factor out ReceiptAccumulator
  spec/unit/sync-accumulator.spec.ts
  src/receipt-accumulator.ts
  src/sync-accumulator.ts
Labels: T-Task

#3322 Fix various APIs which incorrectly use an `IAuthData`
  src/@types/uia.ts
  src/client.ts
  src/interactive-auth.ts
Labels: T-Task

#3323 Use safeSet in recursivelyAssign
  src/utils.ts
Labels: T-Task

#3307 Make webrtc stats collection optional
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/stats/groupCallStats.spec.ts
  src/webrtc/groupCall.ts
  src/webrtc/stats/groupCallStats.ts
Labels: T-Task

#3320 Move receipt-specific logic into ReceiptAccumulator
  src/receipt-accumulator.ts
  src/sync-accumulator.ts
Labels: T-Task

#3327 Fix racing between one-time-keys processing and sync
  src/sync.ts
Labels: T-Defect

#3321 Add `Room.getLastLiveEvent` and `Room.getLastThread`
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Enhancement

#3248 Implement MSC 3981
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/unit/event-timeline-set.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/feature.ts
  src/models/thread.ts
Labels: T-Enhancement

#3326 Tests for the ReceiptAccumulator
  spec/unit/receipt-accumulator.spec.ts
Labels: T-Task

#3324 add client method to remove pusher
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement

#3328 Correct interactive-auth types
  src/interactive-auth.ts
Labels: T-Task
