Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-02, with the labels that each got.

#4043 Saner Releases - improve changelog merging & allow pre-public testing (pack)
  package.json
  scripts/release/merge-release-notes.js
Labels: T-Task

#4037 WebR: migrate the megolm session imported flag
  src/rust-crypto/libolm_migration.ts
Labels: T-Defect

#4044 Saner releases: improve drafts, handle offcycle releases, bump downstream projects
  .github/release-drafter.yml
  .github/workflows/release-drafter-workflow.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-make.yml
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  docs/SUMMARY.md
  docs/release.md
  package.json
  scripts/release/merge-release-notes.js
  yarn.lock
Labels: T-Task

#4045 Add waits for post-release steps for improved visibility
  .github/workflows/release-make.yml
Labels: T-Task

#4055 Add utility to check for non migrated legacy db
  spec/unit/crypto/store/IndexedDBCryptoStore.spec.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
Labels: T-Task

#4060 Bump matrix-sdk-crypto-wasm to 4.5.0
  package.json
  yarn.lock
Labels: T-Defect

#4059 ElementR | Ensure own user and device trust are updated after migration before giving back control to the app.
  spec/integ/crypto/rust-crypto.spec.ts
  src/crypto/store/base.ts
  src/rust-crypto/index.ts
Labels: T-Defect

#4057 Add "AsJson" forms of the key import/export methods
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4063 Await encrypted messages
  spec/unit/matrixrtc/MatrixRTCSessionManager.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
Labels: T-Defect

#4069 Add unread marker event type
  src/models/event.ts
Labels: T-Enhancement

#4070 Allow specifying more OIDC client metadata for dynamic registration
  spec/unit/oidc/register.spec.ts
  src/@types/common.ts
  src/matrix.ts
  src/oidc/register.ts
Labels: T-Enhancement

#4071 Add getAuthIssuer method for MSC2965
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement

#4072 Saner releases clean up
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pull_request.yaml
  package.json
  post-release.sh
  release.sh
  yarn.lock
Labels: T-Task

#4068 Allow specifying OIDC url state parameter for passing data to callback
  src/oidc/authorize.ts
Labels: T-Enhancement

#4074 Validate `account_management_uri` and `account_management_actions_supported` from OIDC Issuer well-known
  spec/unit/oidc/validate.spec.ts
  src/oidc/validate.ts
Labels: T-Enhancement

#4080 Update stale comment
  src/models/thread.ts
Labels: T-Task

#4082 Bump matrix-react-sdk-crypto-wasm to v4.6.0
  package.json
  yarn.lock
Labels: T-Task

#4064 Update MSC2965 OIDC Discovery implementation
  spec/test-utils/oidc.ts
  spec/unit/autodiscovery.spec.ts
  spec/unit/oidc/authorize.spec.ts
  spec/unit/oidc/register.spec.ts
  spec/unit/oidc/tokenRefresher.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/autodiscovery.ts
  src/client.ts
  src/oidc/authorize.ts
  src/oidc/discovery.ts
  src/oidc/index.ts
  src/oidc/register.ts
  src/oidc/tokenRefresher.ts
  src/oidc/validate.ts
Labels: T-Enhancement

#4061 Add basic retry for rust crypto outgoing requests
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  src/http-api/utils.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/scheduler.ts
Labels: T-Defect
