Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-10, with the labels that each got.

#4431 Move out `crypto/aes`
  README.md
  spec/integ/crypto/cross-signing.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/secret-storage.spec.ts
  src/@types/AESEncryptedSecretStoragePayload.ts
  src/calculateKeyCheck.ts
  src/crypto-api/keybackup.ts
  src/crypto/CrossSigning.ts
  src/crypto/aes.ts
  src/crypto/backup.ts
  src/crypto/dehydration.ts
  src/crypto/index.ts
  src/crypto/store/base.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/libolm_migration.ts
  src/secret-storage.ts
  src/types.ts
  src/utils/decryptAESSecretStorageItem.ts
  src/utils/encryptAESSecretStorageItem.ts
  src/utils/internal/deriveKeys.ts
  typedoc.json
Labels: T-Task

#4440 Clean AES file
  spec/unit/secret-storage.spec.ts
  src/calculateKeyCheck.ts
  src/crypto/aes.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/secret-storage.ts
Labels: T-Task

#4441 Fix MatrixRTC sender key wrapping
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#4439 Expose crypto-api as its own typedoc module
  src/crypto-api/index.ts
  src/crypto-api/keybackup.ts
  src/crypto-api/verification.ts
  src/matrix.ts
  src/models/typed-event-emitter.ts
  src/secret-storage.ts
  src/store/indexeddb.ts
  typedoc.json
Labels: T-Task

#4442 Deprecate the crypto events which are not used by the rust-crypto
  src/crypto/index.ts
Labels: T-Deprecation

#4445 Fix the rust crypto import in esm environments.
  babel.config.cjs
  package.json
  src/client.ts
  yarn.lock
Labels: T-Defect, Z-Community-PR

#4443 Add crypto events to `crypto-api`
  spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
  spec/unit/rust-crypto/backup.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api/CryptoEvent.ts
  src/crypto-api/CryptoEventHandlerMap.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/PerSessionKeyBackupDownloader.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4444 Deprecate top level crypto events re-export
  src/matrix.ts
Labels: T-Deprecation

#4446 Fix DelayedEventInfo type
  src/@types/requests.ts
Labels: T-Defect, S-Tolerable

#4451 Update workflows referencing matrix-react-sdk to use only element-web
  .github/workflows/downstream-end-to-end-tests.yml
  .github/workflows/notify-downstream.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: T-Task

#4461 Pin GHA runner versions
  .github/workflows/backport.yml
  .github/workflows/docs-pr-netlify.yaml
  .github/workflows/notify-downstream.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-drafter-workflow.yml
  .github/workflows/release-gitflow.yml
  .github/workflows/release-make.yml
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/static_analysis.yml
  .github/workflows/tests.yml
  .github/workflows/triage-incoming.yml
Labels: T-Task

#4447 Prepare delayed call leave events more reliably
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4453 Organise MatrixRTCSession tests
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
Labels: T-Task

#4469 Remove abandoned MSC3886, MSC3903, MSC3906 experimental implementations
  spec/unit/rendezvous/ecdhv2.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  spec/unit/rendezvous/simpleHttpTransport.spec.ts
  src/rendezvous/MSC3906Rendezvous.ts
  src/rendezvous/RendezvousFailureReason.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
  src/rendezvous/channels/index.ts
  src/rendezvous/index.ts
  src/rendezvous/transports/MSC3886SimpleHttpRendezvousTransport.ts
  src/rendezvous/transports/index.ts
Labels: T-Deprecation

#4466 Refactor/simplify Promises in MatrixRTCSession
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4463 Fix gitflow workflow not handling edge case
  .github/workflows/release-gitflow.yml
Labels: X-Release-Blocker, T-Task

#4473 Avoid `<sender>|<session>` notation in log messages
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4472 Do not rotate MatrixRTC media encryption key when a new member joins a session
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4380 Add CryptoApi.encryptToDeviceMessages() and deprecate Crypto.encryptAndSendToDevices()
  spec/integ/crypto/to-device-messages.spec.ts
  spec/unit/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement, T-Deprecation

#4474 Deprecate `CreateSecretStorageOpts.keyBackupInfo` used in `CryptoApi.bootstrapSecretStorage.`
  src/crypto-api/index.ts
Labels: T-Deprecation

#4478 Update codeowners for `crypto-api`
  .github/CODEOWNERS
Labels: T-Task

#4475 Add RoomWidgetClient.sendToDeviceViaWidgetApi()
  spec/unit/embedded.spec.ts
  src/embedded.ts
Labels: T-Enhancement

#4486 Replace legacy keyBackup types
  spec/unit/rust-crypto/backup.spec.ts
  src/rust-crypto/backup.ts
Labels: T-Task

#4471 Capture HTTP error response headers & handle Retry-After header (MSC4041)
  spec/unit/http-api/errors.spec.ts
  spec/unit/http-api/index.spec.ts
  spec/unit/http-api/utils.spec.ts
  src/http-api/errors.ts
  src/http-api/utils.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/rust-crypto/PerSessionKeyBackupDownloader.ts
  src/rust-crypto/backup.ts
Labels: T-Enhancement
