Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-12, with the labels that each got.

#4546 Extract release sanity checks to reusable workflow
  .github/workflows/release-checks.yml
  .github/workflows/release-make.yml
Labels: T-Task

#3310 More typescript linting
  .eslintrc.cjs
  spec/integ/matrix-client-methods.spec.ts
  spec/test-utils/webrtc.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/@types/global.d.ts
  src/autodiscovery.ts
  src/client.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/dehydration.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/models/event.ts
  src/sliding-sync.ts
  src/store/indexeddb.ts
  src/webrtc/call.ts
  src/webrtc/groupCall.ts
  src/webrtc/stats/callFeedStatsReporter.ts
  src/webrtc/stats/media/mediaTrackHandler.ts
Labels: T-Task

#4571 Add multiprocess health warnings to `initRustCrypto`
  README.md
  src/client.ts
Labels: T-Task

#4567 Rename `MatrixClient.initCrypto` into `MatrixClient.initLegacyCrypto`
  README.md
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/olm-encryption-spec.ts
  spec/integ/devicelist-integ.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/crypto/cross-signing.spec.ts
  spec/unit/crypto/dehydration.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/util.ts
  src/client.ts
Labels: T-Enhancement, X-Breaking-Change

#3635 Fix age field check in event echo processing
  src/models/event.ts
Labels: T-Defect, Z-Community-PR

#4566 Update matrix-sdk-crypto-wasm to 11.0.0
  package.json
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task, Dependencies

#4575 Only re-prepare MatrixrRTC delayed disconnection event on 404
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#4542 Save the key backup key to 4S during `bootstrapCrossSigning`
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4584 Handle when aud OIDC claim is an Array
  spec/unit/oidc/validate.spec.ts
  src/oidc/validate.ts
Labels: T-Defect, Z-Community-PR

#4585 Improve documentation on various secret-storage related methods
  src/crypto-api/index.ts
Labels: T-Task

#4586 Avoid key prompts when resetting crypto
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4589 Update matrix-sdk-crypto-wasm to 12.0.0
  package.json
  yarn.lock
Labels: T-Task, Dependencies

#4593 Upgrade matrix-sdk-crypto-wasm to 1.11.0
  package.json
  yarn.lock
Labels: T-Defect

#4596 Upgrade matrix-sdk-crypto-wasm to 12.1.0
  package.json
  yarn.lock
Labels: T-Defect

#4590 Use mapped types for account data content
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/rust-crypto/secret-storage.spec.ts
  spec/unit/secret-storage.spec.ts
  src/@types/event.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/SecretStorage.ts
  src/crypto/index.ts
  src/models/invites-ignorer-types.ts
  src/models/invites-ignorer.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/secret-storage.ts
  src/secret-storage.ts
Labels: T-Task
