Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-07, with the labels that each got.

#4290 Remove redundant `TextEncoder` shim
  src/crypto/aes.ts
  src/crypto/crypto.ts
  src/crypto/key_passphrase.ts
  src/oidc/authorize.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
Labels: T-Task

#4288 Rust crypto: Clean up handling of verification events
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4295 Sync labels with element-meta and add local labels yml for others.
  .github/labels.yml
  .github/workflows/sync-labels.yml
Labels: T-Task

#4296 Fix error when sending encrypted messages in large rooms
  yarn.lock
Labels: T-Defect, backport staging

#4298 Fix "Unable to restore session" error
  yarn.lock
Labels: T-Defect, backport staging

#4300 Add ability to choose how many timeline events to sync when peeking
  spec/integ/matrix-client-syncing.spec.ts
  src/client.ts
  src/sync.ts
Labels: T-Enhancement, Z-Community-PR

#4293 Bump node.js requirement to 20.
  .github/workflows/release-make.yml
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  .github/workflows/static_analysis.yml
  .github/workflows/tests.yml
  package.json
Labels: T-Task

#4301 Fix incorrect "Olm is not available" errors
  src/crypto/key_passphrase.ts
Labels: T-Defect

#4242 Fix room state being updated with old (now overwritten) state and emitting for those updates.
  spec/unit/room-state.spec.ts
  src/models/event-timeline.ts
  src/models/room-state.ts
Labels: T-Defect

#4292 Remove `crypto` shims
  spec/unit/oidc/authorize.spec.ts
  src/crypto/aes.ts
  src/crypto/backup.ts
  src/crypto/crypto.ts
  src/crypto/key_passphrase.ts
  src/crypto/verification/QRCode.ts
  src/oidc/authorize.ts
  src/randomstring.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
  src/rust-crypto/DehydratedDeviceManager.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4302 Element-R: detect "withheld key" UTD errors, and mark them as such
  spec/integ/crypto/crypto.spec.ts
  spec/unit/models/event.spec.ts
  src/crypto-api/index.ts
  src/crypto/OlmDevice.ts
  src/models/event.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4313 Deprecate `CreateSecretStorageOpts.getKeyBackupPassphrase`
  src/crypto-api/index.ts
Labels: T-Task

#4315 Remove the compare function from utils
  spec/unit/room.spec.ts
  src/models/room.ts
  src/utils.ts
Labels: T-Task

#4316 Bump rust sdk wasm version to 7.0.0
  package.json
  src/rust-crypto/RoomEncryptor.ts
  yarn.lock
Labels: T-Task

#4314 Add index.ts for matrixrtc module
  src/matrixrtc/index.ts
Labels: T-Enhancement

#4328 Be specific about what is considered a MSC4143 call member event.
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4330 Fix comment for useAuthorizationHeader config.
  src/client.ts
Labels: T-Task

#4310 Handle late-arriving `m.room_key.withheld` messages
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4332 Remove flaky test
  spec/unit/room.spec.ts
Labels: T-Task

#4294 Support MSC4140: Delayed events (Futures)
  spec/unit/matrix-client.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/embedded.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement
