Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-03, with the labels that each got.

#4085 When merging release notes, allow considering later versions in the same release cycle
  scripts/release/merge-release-notes.js
Labels: T-Task

#4086 Make sending ContentLoaded optional for a widgetClient
  spec/unit/embedded.spec.ts
  src/embedded.ts
  src/matrix.ts
Labels: T-Enhancement

#4081 PR template: reminder to document your stuff
  .github/PULL_REQUEST_TEMPLATE.md
Labels: T-Task

#4088 Don't re-fetch thread root if we already have it
  spec/integ/matrix-client-event-timeline.spec.ts
  src/client.ts
Labels: T-Task

#4089 Fix race condition with sliding sync extensions
  spec/integ/sliding-sync.spec.ts
  src/sliding-sync-sdk.ts
  src/sliding-sync.ts
Labels: T-Defect, Z-Community-PR

#4100 Add `.m.rule.is_room_mention` push rule to DEFAULT_OVERRIDE_RULES
  spec/unit/pushprocessor.spec.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#4092 Export types describing all specced media event formats
  README.md
  src/@types/media.ts
  src/types.ts
  typedoc.json
Labels: T-Enhancement

#4017 fix automatic DM avatar with functional members
  spec/unit/room.spec.ts
  src/models/room.ts
Labels: T-Enhancement, Z-Community-PR

#4107 Introduce Membership TS type (take 2)
  README.md
  examples/node/app.js
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/olm-encryption-spec.ts
  spec/integ/devicelist-integ.spec.ts
  spec/integ/matrix-client-event-emitter.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-opts.spec.ts
  spec/integ/matrix-client-room-timeline.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/matrix-client-unread-notifications.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/event-timeline.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  spec/unit/room-member.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/room.spec.ts
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  spec/unit/scheduler.spec.ts
  spec/unit/sync-accumulator.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  spec/unit/webrtc/groupCallEventHandler.spec.ts
  src/@types/membership.ts
  src/client.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/index.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/models/MSC3089TreeSpace.ts
  src/models/event.ts
  src/models/room-member.ts
  src/models/room-state.ts
  src/models/room.ts
  src/rust-crypto/RoomEncryptor.ts
  src/sliding-sync-sdk.ts
  src/store/memory.ts
  src/sync.ts
  src/types.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#4122 Fix permissions for deploying docs to github pages
  .github/workflows/release.yml
Labels: T-Task

#4105 Improve types for `sendStateEvent`
  spec/unit/embedded.spec.ts
  spec/unit/matrix-client.spec.ts
  src/@types/common.ts
  src/@types/event.ts
  src/@types/partials.ts
  src/@types/state_events.ts
  src/client.ts
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
  src/models/invites-ignorer.ts
  src/types.ts
  src/webrtc/groupCall.ts
Labels: T-Enhancement

#4109 Move code for processing our own receipts to Room
  spec/integ/matrix-client-syncing.spec.ts
  src/client.ts
  src/models/room.ts
Labels: T-Task

#4110 Fix public rooms post request search params and body
  src/client.ts
Labels: T-Defect, Z-Community-PR

#4106 Fix highlights from threads disappearing on new messages
  spec/integ/matrix-client-syncing.spec.ts
  spec/unit/room.spec.ts
  src/models/room.ts
  src/sync.ts
Labels: T-Defect, X-Breaking-Change

#4127 Add some test utils in a new entrypoint
  README.md
  spec/unit/testing.spec.ts
  src/testing.ts
  typedoc.json
Labels: T-Enhancement

#4124 Remove the logic that throws when the lazy loading options has changed.
  src/errors.ts
  src/sync.ts
Labels: T-Defect, X-Breaking-Change

#4126 Clean up code for handling decryption failures
  spec/integ/crypto/crypto.spec.ts
  spec/unit/models/event.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/testing.spec.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api.ts
  src/crypto/OlmDevice.ts
  src/crypto/algorithms/base.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/index.ts
  src/models/event.ts
  src/rust-crypto/rust-crypto.ts
  src/testing.ts
Labels: T-Task

#4129 Add new enum for verification methods.
  src/client.ts
  src/crypto/verification/QRCode.ts
  src/crypto/verification/SAS.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
  src/types.ts
Labels: T-Enhancement

#4130 Use RoomEvent.MyMembership in auto-join example
  README.md
Labels: Z-Community-PR, T-Task

#4125 Remove various deprecated methods & re-exports
  spec/unit/matrix-client.spec.ts
  spec/unit/models/event.spec.ts
  src/@types/partials.ts
  src/@types/uia.ts
  src/client.ts
  src/interactive-auth.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
  src/oidc/validate.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Enhancement, X-Breaking-Change, X-Upcoming-Release-Blocker

#4108 Improve types for `sendEvent`
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/olm-encryption-spec.ts
  spec/integ/matrix-client-retrying.spec.ts
  spec/integ/matrix-client-unread-notifications.spec.ts
  spec/unit/embedded.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/MSC3089TreeSpace.spec.ts
  src/@types/event.ts
  src/@types/events.ts
  src/client.ts
  src/content-helpers.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/models/MSC3089Branch.ts
  src/models/MSC3089TreeSpace.ts
  src/types.ts
  src/webrtc/call.ts
  src/webrtc/callEventTypes.ts
Labels: T-Enhancement, X-Upcoming-Release-Blocker

#4133 Add new `decryptExistingEvent` test helper
  spec/unit/testing.spec.ts
  src/testing.ts
Labels: T-Enhancement

#4135 Fix merging of default push rules
  spec/unit/pushprocessor.spec.ts
  src/pushprocessor.ts
Labels: T-Defect, X-Release-Blocker, backport staging

#4136 Fix merging of default push rules (backport)
  spec/unit/pushprocessor.spec.ts
  src/pushprocessor.ts
Labels: T-Defect
