Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-11, with the labels that each got.

#4493 Reduce cognitive complexity of Room.addLiveEvents()
  src/models/room.ts
Labels: T-Task

#4491 Remove remaining legacy crypto imports in new crypto and tests
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  src/rust-crypto/index.ts
Labels: T-Task

#4490 Refactor MatrixClient::forget to not abuse membershipChange API
  src/client.ts
Labels: T-Task

#4477 Make doc clearer on getCrossSigningKeyId
  src/crypto-api/index.ts
Labels: T-Task

#4496 Remove dead release scripts
  .github/workflows/release-gitflow.yml
  .github/workflows/release-make.yml
  .github/workflows/static_analysis.yml
  scripts/release/post-merge-master.sh
  scripts/release/pre-release.sh
  scripts/switch_package_to_release.cjs
  scripts/switch_package_to_release.js
Labels: T-Task

#4501 Deprecate unused callbacks in `CryptoCallbacks`
  src/crypto-api/index.ts
Labels: T-Deprecation

#4505 Deprecate `MatrixClient.getKeyBackupVersion`
  src/client.ts
Labels: T-Deprecation

#4492 Send/receive error details with widgets
  package.json
  spec/unit/embedded.spec.ts
  spec/unit/http-api/errors.spec.ts
  src/embedded.ts
  src/http-api/errors.ts
  yarn.lock
Labels: T-Enhancement

#4494 MatrixRTCSession: handle rate limit errors
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4507 Remove redundant type arguments in function call
  src/embedded.ts
Labels: T-Enhancement

#4504 Fix tsdoc error in rust-crypto folder
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4342 When state says you've left ongoing call, rejoin
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4510 Allow configuration of MatrixRTC timers when calling joinRoomSession()
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4511 Handle M_MAX_DELAY_EXCEEDED errors
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4513 Fix tests after security patches
  spec/integ/matrix-client-syncing.spec.ts
Labels: X-Release-Blocker, T-Task

#4503 Update e2e doc in `README.md`
  README.md
  src/client.ts
Labels: T-Task

#4476 Add `restoreKeybackup` to `CryptoApi`.
  spec/integ/crypto/megolm-backup.spec.ts
  src/client.ts
  src/crypto-api/index.ts
  src/crypto-api/keybackup.ts
  src/crypto/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement, T-Deprecation

#4526 Use crypto api import for `CryptoCallbacks` instead of legacy crypto
  src/client.ts
Labels: T-Task

#4527 Deprecate `MatrixClient.isEventSenderVerified`
  src/client.ts
Labels: T-Deprecation

#4508 Add downstream tsc for element-web
  .github/workflows/static_analysis.yml
Labels: T-Task

#4498 Fix local echo in embedded mode
  spec/unit/embedded.spec.ts
  src/embedded.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
Labels: T-Enhancement

#4537 Fix `RustBackupManager` remaining values after current backup removal
  spec/integ/crypto/megolm-backup.spec.ts
  src/rust-crypto/backup.ts
Labels: T-Defect

#4538 Tighten GITHUB_TOKEN permissions
  .github/workflows/backport.yml
  .github/workflows/docs-pr-netlify.yaml
  .github/workflows/downstream-end-to-end-tests.yml
  .github/workflows/notify-downstream.yaml
  .github/workflows/pull_request.yaml
  .github/workflows/release-drafter-workflow.yml
  .github/workflows/release-drafter.yml
  .github/workflows/release-gitflow.yml
  .github/workflows/release-make.yml
  .github/workflows/release-npm.yml
  .github/workflows/release.yml
  .github/workflows/sonarcloud.yml
  .github/workflows/sonarqube.yml
  .github/workflows/static_analysis.yml
  .github/workflows/sync-labels.yml
  .github/workflows/tests.yml
  .github/workflows/triage-incoming.yml
  .github/workflows/triage-labelled.yml
Labels: T-Task

#4539 Switch away from deprecated github-status-action
  .github/workflows/sonarcloud.yml
  .github/workflows/tests.yml
Labels: T-Task, Dependencies

#4540 Ensure we disambiguate display names which look like MXIDs
  spec/unit/room-member.spec.ts
  spec/unit/utils.spec.ts
  src/models/room-member.ts
Labels: T-Enhancement

#4543 Prevent releases when release blockers exist
  .github/workflows/release-make.yml
Labels: T-Task

#4532 Revert "Fix room state being updated with old (now overwritten) state and emitting for those updates. (#4242)"
  spec/unit/room-state.spec.ts
  src/models/event-timeline.ts
  src/models/room-state.ts
Labels: T-Enhancement

#4487 Support MSC4222 `state_after`
  spec/integ/crypto/crypto.spec.ts
  spec/integ/matrix-client-event-timeline.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/integ/matrix-client-unread-notifications.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/test-utils/test-utils.ts
  spec/test-utils/thread.ts
  spec/unit/embedded.spec.ts
  spec/unit/event-mapper.spec.ts
  spec/unit/event-timeline-set.spec.ts
  spec/unit/event-timeline.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/event.spec.ts
  spec/unit/models/room-receipts.spec.ts
  spec/unit/models/thread.spec.ts
  spec/unit/notifications.spec.ts
  spec/unit/relations.spec.ts
  spec/unit/room.spec.ts
  spec/unit/sync-accumulator.spec.ts
  spec/unit/timeline-window.spec.ts
  spec/unit/webrtc/groupCall.spec.ts
  src/client.ts
  src/embedded.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/event.ts
  src/models/room.ts
  src/models/thread.ts
  src/sliding-sync-sdk.ts
  src/sync-accumulator.ts
  src/sync.ts
Labels: T-Enhancement, X-Breaking-Change

#4547 Move bump downstreams to js-sdk specific release workflow
  .github/workflows/release-make.yml
  .github/workflows/release.yml
Labels: T-Task

#4561 Re-send MatrixRTC media encryption keys for a new joiner even if a rotation is in progress
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4560 Deprecate remaining legacy functions and move `CryptoEvent.LegacyCryptoStoreMigrationProgress` handler
  src/client.ts
  src/crypto-api/CryptoEventHandlerMap.ts
  src/crypto/index.ts
Labels: T-Deprecation

#4563 Remove deprecated calls of `MatrixClient`
  src/models/relations.ts
  src/models/room.ts
Labels: T-Task

#4565 Replace deprecate imports
  src/common-crypto/CryptoBackend.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/libolm_migration.ts
  src/testing.ts
Labels: T-Task, T-Deprecation
