Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-09, with the labels that each got.

#4381 Stabilise MSC4156
  src/client.ts
  src/feature.ts
Labels: Z-Community-PR, T-Task

#4390 Minor improvements to logging in device verification
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/PerSessionKeyBackupDownloader.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4389 Element-R: Mark unsupported MatrixClient methods as deprecated
  src/client.ts
Labels: T-Deprecation

#4395 Expose the event ID of a call membership
  src/matrixrtc/CallMembership.ts
Labels: T-Enhancement

#4397 Improve documentation on `{encrypt,decrypt}AES`
  src/crypto/aes.ts
Labels: T-Task

#4396 Bump dependency on rust-sdk-crypto-wasm to v8.0.0
  package.json
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#4404 Replace `matrix.org/matrix-react-sdk` with `element-hq/matrix-react-sdk` in CI
  .github/workflows/downstream-end-to-end-tests.yml
  .github/workflows/notify-downstream.yaml
  .github/workflows/release.yml
  .github/workflows/tests.yml
Labels: T-Task

#4399 Move `crypto/recoverykey.ts` to `crypto-api/recovery-key.ts`
  spec/unit/crypto-api/recovery-key.spec.ts
  src/client.ts
  src/crypto-api/index.ts
  src/crypto-api/recovery-key.ts
  src/crypto/backup.ts
  src/crypto/index.ts
  src/crypto/recoverykey.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4394 Fix build failure in node.js example
  examples/node/app.js
  examples/node/package.json
Labels: Z-Community-PR, T-Task

#4398 Fix sending redacts in embedded (widget) mode
  src/embedded.ts
Labels: T-Enhancement

#4405 Export membership types
  src/matrix.ts
Labels: T-Enhancement, Z-Community-PR

#4401 Move `crypto/key_passphrase.ts` to `crypto-api/key-passphrase.ts`
  spec/unit/common-crypto/key-passphrase.spec.ts
  src/client.ts
  src/common-crypto/key-passphrase.ts
  src/crypto-api/index.ts
  src/crypto-api/key-passphrase.ts
  src/crypto/key_passphrase.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4409 Add ESLint rule to ensure .ts extensions on imports
  .eslintrc.cjs
  package.json
  src/client.ts
  yarn.lock
Labels: Z-Community-PR, T-Task

#4406 Don't share full key history for RTC per-participant encryption
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/types.ts
Labels: T-Enhancement

#4407 Add crypto mode setting for invisible crypto, and apply it to decrypting events
  package.json
  spec/integ/crypto/crypto.spec.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement

#4412 Throw clearer error if `createSecretStorageKey` misbehaves
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4430 Update sonarcloud action to use v3.3 `matrix-org/sonarcloud-workflow-action`
  .github/workflows/sonarcloud.yml
Labels: T-Task

#4415 Add `CryptoApi.pinCurrentUserIdentity` and `UserIdentity.needsUserApproval`
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/test-data/generate-test-data.py
  spec/test-utils/test-data/index.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4429 crypto: Replace cryptoMode with DeviceIsolationMode concept
  spec/integ/crypto/crypto.spec.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4432 Update OIDC registration types to match latest MSC2966 state
  src/oidc/register.ts
Labels: T-Enhancement

#4403 Update media event content types to include captions
  src/@types/media.ts
Labels: T-Enhancement, Z-Community-PR

#4422 Rotate Matrix RTC media encryption key when a new member joins a call for Post Compromise Security
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4427 RTCSession cleanup: deprecate getKeysForParticipant() and getEncryption(); add emitEncryptionKeys()
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Deprecation

#4425 crypto: configure key sharing strategy based on DeviceIsolationMode
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  src/crypto-api/index.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4435 Bump matrix-rust-sdk to 9.1.0
  yarn.lock
Labels: T-Enhancement
