Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-05, with the labels that each got.

#4185 Add helpers for authenticated media, and associated documentation
  README.md
  spec/unit/content-repo.spec.ts
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/content-repo.ts
Labels: T-Enhancement

#4188 Add missing (and common-ish) HTTP method verbs to types
  src/http-api/method.ts
Labels: T-Task

#4192 Fix sendEventHttpRequest for `m.room.redaction` events without `redacts`
  src/client.ts
Labels: T-Defect

#4193 Simplify OIDC types & export `decodeIdToken`
  src/oidc/validate.ts
Labels: T-Enhancement

#4196 Fix state_events.ts types
  src/@types/partials.ts
  src/@types/state_events.ts
  src/models/room-state.ts
Labels: T-Defect

#4200 Only pass id_server if we had one to begin with
  src/interactive-auth.ts
Labels: T-Defect

#4202 Wire up verification cancel & mismatch for rust crypto
  src/rust-crypto/verification.ts
Labels: T-Defect

#4201 Remove deprecated methods and fields
  spec/unit/crypto/cross-signing.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/models/MSC3089Branch.spec.ts
  src/@types/auth.ts
  src/@types/event.ts
  src/@types/registration.ts
  src/client.ts
  src/crypto/CrossSigning.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/index.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
  src/interactive-auth.ts
  src/matrix.ts
  src/models/room.ts
Labels: X-Breaking-Change, T-Deprecation

#4187 Preserve ESM for async imports to work correctly
  .babelrc
  babel.config.js
  src/models/MSC3089TreeSpace.ts
Labels: T-Enhancement, Z-Community-PR

#4212 Update organization in github action
  .github/workflows/notify-downstream.yaml
  .github/workflows/triage-labelled.yml
Labels: T-Task

#4210 `initRustCrypto`: allow app to pass in the store key directly
  spec/integ/crypto/rust-crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
Labels: T-Enhancement

#4216 Bump matrix-sdk-crypto-wasm to 5.0.0
  package.json
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto/index.ts
  src/rust-crypto/PerSessionKeyBackupDownloader.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Defect

#4217 Remove more deprecated methods, fields, and exports
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-room-timeline.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/autodiscovery.spec.ts
  spec/unit/event-timeline-set.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/room.spec.ts
  src/@types/registration.ts
  src/autodiscovery.ts
  src/client.ts
  src/crypto-api/keybackup.ts
  src/crypto/index.ts
  src/matrix.ts
  src/models/event-timeline-set.ts
  src/models/event-timeline.ts
  src/models/event.ts
  src/models/room.ts
  src/rust-crypto/rust-crypto.ts
  src/sync-accumulator.ts
  src/utils.ts
Labels: X-Release-Blocker, X-Breaking-Change, T-Deprecation

#4218 Don't run migration for Rust crypto if the legacy store is empty
  spec/integ/crypto/rust-crypto.spec.ts
  spec/test-utils/test_indexeddb_cryptostore_dump/empty_account/README.md
  spec/test-utils/test_indexeddb_cryptostore_dump/empty_account/dump.json
  spec/test-utils/test_indexeddb_cryptostore_dump/empty_account/index.ts
  spec/test-utils/test_indexeddb_cryptostore_dump/full_account/index.ts
  spec/test-utils/test_indexeddb_cryptostore_dump/no_cached_msk_dump/index.ts
  spec/test-utils/test_indexeddb_cryptostore_dump/unverified/index.ts
  src/rust-crypto/libolm_migration.ts
Labels: T-Defect

#4189 Add note about MSC3886, MSC3903 and MSC3906 being closed
  src/rendezvous/MSC3906Rendezvous.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
  src/rendezvous/transports/MSC3886SimpleHttpRendezvousTransport.ts
Labels: T-Task

#4225 Fix the queueToDevice tests for the new fakeindexeddb
  spec/unit/queueToDevice.spec.ts
Labels: T-Defect
