Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-08, with the labels that each got.

#4333 Fix hashed ID server lookups with no Olm
  spec/unit/digest.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/oidc/authorize.spec.ts
  src/client.ts
  src/digest.ts
  src/oidc/authorize.ts
Labels: T-Defect

#4311 Support Futures via widgets
  package.json
  spec/integ/rendezvous/MSC4108SignInWithQR.spec.ts
  spec/unit/embedded.spec.ts
  src/client.ts
  src/embedded.ts
  yarn.lock
Labels: T-Enhancement

#4334 Also check for MSC3757 for session state keys
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4335 Make code tsc es2022 compliant
  src/@types/global.d.ts
  src/crypto/algorithms/base.ts
Labels: T-Task

#4336 Bump matrix-widget-api
  package.json
  yarn.lock
Labels: T-Enhancement

#4337 Use non-legacy calls if any are found
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4344 delayBeforeuse => delayBeforeUse for consistency
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Task

#4343 Resend MatrixRTC encryption keys if a membership has changed
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#4345 Handle MatrixRTC encryption keys arriving out of order
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Defect

#4350 Ensure "type" = "module" ES declaration in pre-release.sh
  scripts/release/pre-release.sh
Labels: T-Defect, Z-Community-PR

#4352 Revert "Ensure "type" = "module" ES declaration in pre-release.sh"
  scripts/release/pre-release.sh
Labels: T-Task

#4353 Unrevert prerelease fix, and fix release error
  .prettierrc.cjs
  scripts/release/pre-release.sh
Labels: T-Task

#4355 Move `type:module` declaration into package.json.
  .eslintrc.cjs
  package.json
  scripts/release/pre-release.sh
  scripts/switch_package_to_release.cjs
  scripts/switch_package_to_release.js
Labels: T-Task

#4356 Rename slowReporter to reflect that it is CommonJS
  jest.config.ts
  spec/slowReporter.cjs
Labels: T-Task

#4359 Move `type:module` declaration into package.json. (Backport 4355)
  .eslintrc.cjs
  package.json
  scripts/release/pre-release.sh
  scripts/switch_package_to_release.cjs
  scripts/switch_package_to_release.js
Labels: T-Task

#4357 set entrypoints to use ./lib rather than ./src
  package.json
Labels: T-Task

#4354 Set web team as codeowner for the scripts dir
  .github/CODEOWNERS
Labels: T-Task

#4376 Deprecate unused callback hooks `CryptoCallbacks.onSecretRequested` and `CryptoCallbacks.getDehydrationKey`
  src/crypto-api/index.ts
Labels: T-Deprecation

#4378 Use prefixed loggers for MatrixRTC
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
Labels: T-Task

#4361 Rename merge release notes script to cjs
  .github/workflows/release-drafter-workflow.yml
  scripts/release/merge-release-notes.cjs
Labels: T-Task
