Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-06, with the labels that each got.

#4227 Add crypto methods for export and import of secrets bundle
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/@types/matrix-sdk-crypto-wasm.d.ts
  src/crypto-api.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4230 RustCrypto: fix ordering of methods
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4231 Use LegacyRendezvousFailureReason over RendezvousFailureReason
  src/rendezvous/RendezvousFailureReason.ts
Labels: T-Task

#4134 MSC4108 support OIDC QR code login
  spec/integ/rendezvous/MSC4108SignInWithQR.spec.ts
  spec/test-utils/oidc.ts
  spec/unit/rendezvous/MSC4108RendezvousSession.spec.ts
  spec/unit/rendezvous/channels/MSC4108SecureChannel.spec.ts
  spec/unit/rendezvous/ecdhv2.spec.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  spec/unit/rendezvous/simpleHttpTransport.spec.ts
  src/oidc/register.ts
  src/rendezvous/MSC3906Rendezvous.ts
  src/rendezvous/MSC4108SignInWithQR.ts
  src/rendezvous/RendezvousFailureReason.ts
  src/rendezvous/channels/MSC3903ECDHv2RendezvousChannel.ts
  src/rendezvous/channels/MSC4108SecureChannel.ts
  src/rendezvous/channels/index.ts
  src/rendezvous/index.ts
  src/rendezvous/transports/MSC3886SimpleHttpRendezvousTransport.ts
  src/rendezvous/transports/MSC4108RendezvousSession.ts
  src/rendezvous/transports/index.ts
Labels: T-Enhancement

#4228 Fix incorrect assumptions about required fields in /search response
  src/@types/search.ts
  src/client.ts
Labels: T-Defect

#4232 Add support for stable name for MSC4115
  spec/integ/crypto/crypto.spec.ts
  src/@types/event.ts
  src/models/event.ts
Labels: T-Task

#4240 Replace usages of setImmediate with setTimeout for wider compatibility
  .eslintrc.js
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/utils.ts
Labels: T-Enhancement

#4239 Use stable endpoints for MSC3916
  README.md
  spec/unit/content-repo.spec.ts
  src/content-repo.ts
Labels: T-Task

#4241 Fix screen sharing in recent Chrome
  src/webrtc/call.ts
Labels: T-Defect, backport staging

#4245 Work around spec bug for m.room.avatar state event content type
  src/@types/state_events.ts
Labels: T-Defect

#4195 Make the js-sdk compatible with MSC preferred foci and active focus.
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/LivekitFocus.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/MatrixRTCSessionManager.spec.ts
  src/@types/event.ts
  src/matrixrtc/CallMembership.ts
  src/matrixrtc/LivekitFocus.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
  src/matrixrtc/focus.ts
Labels: T-Enhancement

#4247 Add via parameter for MSC4156
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
  src/feature.ts
Labels: T-Enhancement, Z-Community-PR

#4252 Correctly transform base64 with multiple instances of + or /
  spec/unit/base64.spec.ts
  src/base64.ts
Labels: T-Defect

#4246 Fetch capabilities in the background
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/matrix-client-syncing-errors.spec.ts
  spec/test-utils/client.ts
  spec/unit/rendezvous/rendezvous.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/matrix.ts
  src/models/room.ts
  src/rendezvous/MSC3906Rendezvous.ts
  src/serverCapabilities.ts
Labels: T-Enhancement, X-Breaking-Change

#4254 Replace deprecated babel proposal plugins
  babel.config.js
  package.json
  yarn.lock
Labels: T-Task

#4261 Upgrade Rust Crypto SDK to 6.1.0
  package.json
  yarn.lock
Labels: T-Defect

#4260 Use legacy call membership if anyone else is
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4264 Bump ES target version to ES2022
  src/models/room.ts
  tsconfig.json
Labels: T-Task

#4263 Element-R: Fix resource leaks in verification logic
  src/rust-crypto/verification.ts
Labels: T-Defect

#4253 Remove domexception polyfill, has been native in NodeJS since v17
  package.json
  spec/setupTests.ts
  yarn.lock
Labels: T-Task

#4266 Fix ingest of release notes wiping out the parent notes
  .github/workflows/release-make.yml
  scripts/release/merge-release-notes.js
Labels: T-Task

#4259 Add fetching the well known in embedded mode.
  src/client.ts
  src/embedded.ts
Labels: T-Enhancement

#4285 Declare matrix-js-sdk as an ES module
  babel.config.cjs
  scripts/switch_package_to_release.js
Labels: T-Defect

#4283 Rename `crypto-api.ts` -> `crypto-api/index.ts`
  src/crypto-api/index.ts
Labels: T-Task

#4282 Remove redundant hack for using the old pickle key in rust crypto
  spec/integ/crypto/rust-crypto.spec.ts
  src/client.ts
Labels: T-Enhancement

#4286 Fix build for example script
  examples/node/package.json
Labels: T-Defect

#4289 Remove useless log line
  src/rust-crypto/RoomEncryptor.ts
Labels: T-Task
