Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-04, with the labels that each got.

#4137 Update matrix-rust-sdk-crypto-wasm to 4.9.0
  package.json
  yarn.lock
Labels: T-Task

#4138 Refactoring and simplification in decryption error handling
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4113 ElementR| Retry query backup until it works during migration to avoid spurious correption error popup
  src/rust-crypto/libolm_migration.ts
Labels: T-Defect

#4013 Add knip unused code & dependency analyser
  .github/workflows/static_analysis.yml
  knip.ts
  package.json
  src/crypto/backup.ts
  yarn.lock
Labels: T-Task

#4149 OIDC improvements in prep of OIDC-QR reciprocation
  spec/test-utils/oidc.ts
  spec/unit/oidc/register.spec.ts
  src/@types/oidc-client-ts.d.ts
  src/oidc/register.ts
  src/oidc/validate.ts
Labels: T-Enhancement

#4062 Add support for device dehydration v2 (Element R)
  spec/integ/crypto/device-dehydration.spec.ts
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/models/device.ts
  src/rust-crypto/DehydratedDeviceManager.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/device-converter.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement

#4114 Validate backup private key before migrating it
  spec/integ/crypto/rust-crypto.spec.ts
  spec/test-utils/test_indexeddb_cryptostore_dump/no_cached_msk_dump/index.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/libolm_migration.ts
Labels: T-Defect

#4139 Crypto: use a new error code for UTDs from device-relative historical events
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
  src/crypto-api.ts
  src/rust-crypto/PerSessionKeyBackupDownloader.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4152 Add comment to make clear that RoomStateEvent.Events does not update related objects in the js-sdk
  src/models/room-state.ts
Labels: T-Enhancement

#4156 Element R: fix `isCrossSigningReady` not checking identity trust
  spec/integ/crypto/cross-signing.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4170 Use encoded URI components when storing sessions in memory crypto store
  src/crypto/store/memory-crypto-store.ts
Labels: Z-Community-PR, T-Task

#4169 Modernize window.crypto access constants
  src/crypto/crypto.ts
Labels: T-Enhancement

#4168 Element-R: Fix rust migration when ssss secret are stored not encryted in cache (old legacy behavior)
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/libolm_migration.ts
Labels: T-Defect

#4172 Use a different error code for UTDs when user was not in the room
  spec/integ/crypto/crypto.spec.ts
  src/@types/event.ts
  src/crypto-api.ts
  src/models/event.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4178 Simplify Playwright CI
  .github/workflows/downstream-end-to-end-tests.yml
Labels: T-Task

#4179 Pass all args to Sonar via sonar-project.properties file
  .github/workflows/sonarcloud.yml
Labels: T-Task

#4140 Add some comments to the release drafter workflows
  .github/workflows/release-drafter-workflow.yml
  .github/workflows/release-drafter.yml
Labels: T-Task
