Repository matrix-org/matrix-js-sdk, pull requests merged in 2024-01, with the labels that each got.

#3979 Use enums instead of strings for client event listeners (`client.on`, `client.once` ...) in the README to improve type inference
  README.md
Labels: Z-Community-PR, T-Task

#3973 ElementR: Ensure Encryption order per room
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  src/logger.ts
  src/rust-crypto/RoomEncryptor.ts
  src/utils.ts
Labels: T-Defect, A-Element-R

#3977 Groundwork for supporting migration from libolm to rust crypto.
  spec/integ/crypto/crypto.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#3981 #22606 Fix "Remove" button to users without "m.room.redaction"
  src/models/room-state.ts
Labels: T-Defect, Z-Community-PR

#3970 Bump minimum spec version to v1.5
  README.md
  spec/unit/autodiscovery.spec.ts
  src/version-support.ts
Labels: T-Enhancement, X-Breaking-Change

#3988 Update teams names in CODEOWNERS
  .github/CODEOWNERS
Labels: T-Task

#3989 Bump matrix-sdk-crypto-wasm to 3.6.0
  package.json
  yarn.lock
Labels: T-Task

#3990 bump fake-indexeddb
  package.json
  yarn.lock
Labels: T-Task

#3991 Revert "Bump matrix-sdk-crypto-wasm to 3.6.0"
  package.json
  yarn.lock
Labels: T-Defect

#4001 Bump matrix-sdk-crypto-wasm to 3.6.0 (take 2)
  package.json
  yarn.lock
Labels: T-Task

#4008 Stop running react-sdk Cypress tests
  .github/workflows/downstream-artifacts.yml
  .github/workflows/downstream-end-to-end-tests.yml
  .github/workflows/sonarcloud.yml
Labels: T-Task

#3982 Emit events during migration from libolm
  spec/integ/crypto/rust-crypto.spec.ts
  spec/unit/crypto/store/CryptoStore.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto/index.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
  src/rust-crypto/index.ts
  src/rust-crypto/libolm_migration.ts
Labels: T-Enhancement

#4012 Add CODEOWNERS entries for crypto stuff
  .github/CODEOWNERS
Labels: T-Task

#4009 Fix new threads not appearing.
  spec/integ/matrix-client-event-timeline.spec.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#4014 Broaden spec version support
  README.md
  src/autodiscovery.ts
  src/version-support.ts
Labels: T-Enhancement, backport staging

#3975 drop 'malformed member event' log level, given all TR rooms are malformed like this.
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Task

#4011 Use Github Artifacts v4
  .github/workflows/docs-pr-netlify.yaml
  .github/workflows/sonarcloud.yml
  .github/workflows/static_analysis.yml
  .github/workflows/tests.yml
Labels: T-Task

#4005 Decrypt and Import full backups in chunk with progress
  spec/integ/crypto/megolm-backup.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/keybackup.ts
  src/rust-crypto/backup.ts
Labels: T-Defect

#4018 Element-R: improve logging for secret gossiping
  src/rust-crypto/backup.ts
Labels: T-Task

#4021 Element R: Bump matrix-rust-sdk-crypto-wasm to version 4.0.0
  package.json
  spec/unit/rust-crypto/KeyClaimManager.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/KeyClaimManager.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Task

#4015 ElementR | backup: call expensive `roomKeyCounts` less often
  spec/unit/rust-crypto/backup.spec.ts
  src/rust-crypto/backup.ts
Labels: T-Defect

#4026 Fix type error introduced by crypto-wasm 4.0.0
  src/rust-crypto/verification.ts
Labels: T-Task

#4025 Bump matrix-sdk-crypto-wasm to 4.0.1
  package.json
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  yarn.lock
Labels: T-Task

#4007 Support optional MSC3860 redirects
  spec/unit/content-repo.spec.ts
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/content-repo.ts
Labels: T-Enhancement

#4024 Fix crypto migration for megolm sessions with no sender key
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto/OlmDevice.ts
  src/rust-crypto/libolm_migration.ts
Labels: T-Defect

#3947 Implement getting verification cancellation info in Rust crypto
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/verification.ts
Labels: T-Defect

#4030 Introduce `Room.hasEncryptionStateEvent`
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/models/room.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Task

#3987 fix IndexedDBStore API documentation
  CHANGELOG.md
  src/store/indexeddb.ts
Labels: Z-Community-PR, T-Task

#4034 Update `matrix-rust-sdk-crypto-wasm` to 4.1.0
  package.json
  yarn.lock
Labels: T-Task

#4031 Refactor `MatrixClient.encryptAndSendEvent`
  spec/unit/matrix-client.spec.ts
  spec/unit/queueToDevice.spec.ts
  src/client.ts
  src/models/event.ts
Labels: T-Task

#4035 Element-R: check persistent room list for encryption config
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/mockEndpoints.ts
  spec/unit/matrix-client.spec.ts
  src/client.ts
  src/crypto-api.ts
  src/crypto/index.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4022 Make `timeline` a getter
  spec/unit/room.spec.ts
  src/models/read-receipt.ts
  src/models/room.ts
  src/models/thread.ts
Labels: T-Defect

#4006 ElementR: report invalid keys rather than failing to restore from backup
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/backup.ts
Labels: T-Defect

#4033 Element R: Add test that requests are encoded properly
  spec/unit/rust-crypto/rust-crypto.spec.ts
Labels: T-Task

#4036 Element-R: support for migration of the room list from legacy crypto
  spec/integ/crypto/rust-crypto.spec.ts
  src/crypto/store/base.ts
  src/rust-crypto/index.ts
  src/rust-crypto/libolm_migration.ts
Labels: T-Enhancement

#4032 Add expire_ts compatibility to matrixRTC
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/CallMembership.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4019 Element R: emit events when devices have changed
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/rust-crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4042 Dependencies: Bump wasm bindings version to 4.3.0
  package.json
  yarn.lock
Labels: T-Defect

#4004 ElementR: fix emoji verification stalling when both ends hit start at the same time
  spec/unit/rust-crypto/verification.spec.ts
  src/rust-crypto/verification.ts
Labels: T-Defect
