Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-09, with the labels that each got.

#4983 Fix stable-suffixed MSC4133 support
  src/client.ts
Labels: T-Defect

#4979 Remove custom `org.matrix.msc4075.rtc.notification.parent` relation type
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/@types/event.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4984 Fix `m.topic` format
  spec/unit/content-helpers.spec.ts
  src/@types/topic.ts
  src/content-helpers.ts
Labels: T-Defect, Z-Community-PR

#4977 Remove knocked room when membership changes to join
  spec/unit/sync-accumulator.spec.ts
  src/sync-accumulator.ts
Labels: T-Defect, Z-Community-PR
