Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-06, with the labels that each got.

#4861 Fix MatrixRTC membership manager failing to rejoin in a race condition (sync vs not found response)
  spec/setupTests.ts
  spec/unit/matrixrtc/MembershipManager.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/NewMembershipManager.ts
  src/utils.ts
Labels: T-Defect

#4876 Remove `@matrix-org/olm` from dependency list
  package.json
Labels: T-Enhancement

#4878 Allow customizing the IndexedDB database prefix used by Rust crypto.
  spec/integ/crypto/rust-crypto.spec.ts
  src/client.ts
Labels: T-Enhancement, Z-Community-PR

#4882 Update matrix-sdk-crypto-wasm to `15.0.0`
  package.json
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement
