Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-05, with the labels that each got.

#4825 Fix token refresh behaviour for non-expired tokens
  spec/unit/http-api/fetch.spec.ts
  src/http-api/refresh.ts
Labels: T-Defect, backport staging

#4828 Write a log line when cancelling verification
  spec/unit/rust-crypto/verification.spec.ts
  src/rust-crypto/rust-crypto.ts
  src/rust-crypto/verification.ts
Labels: T-Task

#4832 Update to Node 22 LTS
  package.json
  spec/integ/crypto/verification.spec.ts
  src/matrixrtc/EncryptionManager.ts
  src/matrixrtc/MatrixRTCSession.ts
  tsconfig.json
Labels: T-Enhancement

#4829 Deprecate utils function `defer` in favour of `Promise.withResolvers`
  knip.ts
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/crypto/verification.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/integ/rendezvous/MSC4108SignInWithQR.spec.ts
  spec/integ/sliding-sync-sdk.spec.ts
  spec/unit/ToDeviceMessageQueue.spec.ts
  spec/unit/http-api/fetch.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/matrixrtc/MembershipManager.spec.ts
  spec/unit/matrixrtc/ToDeviceKeyTransport.spec.ts
  spec/unit/room-state.spec.ts
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/OutgoingRequestsManager.spec.ts
  spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/scheduler.spec.ts
  spec/unit/secret-storage.spec.ts
  spec/unit/stores/indexeddb-store-worker.spec.ts
  spec/unit/stores/indexeddb.spec.ts
  src/client.ts
  src/http-api/index.ts
  src/interactive-auth.ts
  src/matrixrtc/NewMembershipManager.ts
  src/rust-crypto/OutgoingRequestsManager.ts
  src/rust-crypto/verification.ts
  src/scheduler.ts
  src/store/indexeddb-remote-backend.ts
  src/sync.ts
  src/utils.ts
Labels: T-Deprecation

#4831 Simplify global types
  src/@types/global.d.ts
  src/webrtc/mediaHandler.ts
Labels: T-Task

#4833 Fix autodiscovery handling of 2xx (non-200) codes
  src/autodiscovery.ts
Labels: T-Defect

#4845 Remove @types/uuid - uuid has its own types now
  package.json
Labels: T-Task

#4714 MatrixRTC: Rename `MembershipConfig` parameters
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/MembershipManager.spec.ts
  src/matrixrtc/LegacyMembershipManager.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/NewMembershipManager.ts
Labels: T-Deprecation

#4790 Reapply "Distinguish room state and timeline events in embedded clients"
  spec/unit/embedded.spec.ts
  src/embedded.ts
Labels: T-Enhancement

#4848 Bump matrix-sdk-crypto-wasm to 14.2.0
  package.json
  yarn.lock
Labels: T-Task

#4849 Allow the embedded client to work without update_state support
  spec/unit/embedded.spec.ts
  src/embedded.ts
Labels: T-Enhancement
