Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-01, with the labels that each got.

#4410 Add syntax & type check for Node.js example on CI
  .github/workflows/static_analysis.yml
  examples/node/app.js
  examples/node/package.json
  examples/node/tsconfig.json
Labels: Z-Community-PR, T-Task

#4601 Don't retry on 4xx responses
  src/http-api/utils.ts
Labels: T-Defect

#4587 MatrixRTC: Implement expiry logic for CallMembership and additional test coverage
  spec/unit/matrixrtc/CallMembership.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/CallMembership.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4609 Fix issue with sentinels being incorrect on m.room.member events
  spec/unit/event-timeline-set.spec.ts
  src/client.ts
  src/models/event-timeline.ts
  src/models/event.ts
Labels: T-Defect

#4608 MatrixRTC: move MatrixRTCSession logic into LocalMembershipManager
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MembershipManager.ts
Labels: T-Task

#4023 Send MSC3981 'recurse' param on `/relations` endpoint on Matrix 1.10 servers
  src/feature.ts
Labels: T-Enhancement

#4610 MatrixRTC: refactor MatrixRTCSession MemberManager API
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
  src/matrixrtc/MembershipManager.ts
Labels: T-Task

#4613 MatrixRTC: additional TS docs for IMembershipManager interface
  src/matrixrtc/MembershipManager.ts
Labels: T-Task

#4612 MatrixRTC: refactor MatrixRTCSession media encryption key logic into EncryptionManager
  src/matrixrtc/EncryptionManager.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Task

#4616 Add authenticated media to getAvatarUrl in room and room-member models
  spec/unit/room-member.spec.ts
  spec/unit/room.spec.ts
  src/models/room-member.ts
  src/models/room.ts
Labels: T-Enhancement, Z-Community-PR

#4574 Distinguish room state and timeline events in embedded clients
  spec/unit/embedded.spec.ts
  src/embedded.ts
  yarn.lock
Labels: T-Enhancement

#4623 Use rust crypto instead of legacy crypto in sync tests
  spec/integ/matrix-client-syncing.spec.ts
Labels: T-Task

#4628 Fix documentation on `CryptoEvent`
  src/crypto-api/CryptoEvent.ts
Labels: T-Task

#4632 Deprecate `MatrixClient.login` and replace with `loginRequest`
  src/client.ts
Labels: T-Enhancement

#4629 Add an extra consistency check in `bootstrapCrossSigning`
  src/@types/matrix-sdk-crypto-wasm.d.ts
  src/rust-crypto/CrossSigningIdentity.ts
Labels: T-Task

#4621 Change randomString et al to be secure
  spec/unit/interactive-auth.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/mocks.ts
  spec/unit/randomstring.spec.ts
  spec/unit/secret-storage.spec.ts
  spec/unit/thread-utils.spec.ts
  src/client.ts
  src/crypto/key_passphrase.ts
  src/crypto/verification/request/ToDeviceChannel.ts
  src/oidc/authorize.ts
  src/randomstring.ts
  src/rust-crypto/rust-crypto.ts
  src/secret-storage.ts
  src/webrtc/call.ts
Labels: T-Defect

#4614 Add `CryptoApi.resetEncryption`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4626 Switch OIDC primarily to new `/auth_metadata` API
  spec/integ/rendezvous/MSC4108SignInWithQR.spec.ts
  spec/test-utils/oidc.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/oidc/authorize.spec.ts
  spec/unit/oidc/register.spec.ts
  spec/unit/oidc/tokenRefresher.spec.ts
  spec/unit/oidc/validate.spec.ts
  src/client.ts
  src/oidc/authorize.ts
  src/oidc/discovery.ts
  src/oidc/index.ts
  src/oidc/register.ts
  src/oidc/tokenRefresher.ts
  src/oidc/validate.ts
  src/rendezvous/MSC4108SignInWithQR.ts
  src/testing.ts
Labels: T-Enhancement

#4648 `CryptoApi.resetEncryption` should always create a new key backup
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4649 Tidy up some main exports
  knip.ts
  src/matrix.ts
  src/models/profile-keys.ts
Labels: T-Task

#4562 Remove deprecated calls in `webrtc/call.ts`
  src/webrtc/call.ts
Labels: T-Task

#4620 Remove `MatrixClient.initLegacyCrypto`
  README.md
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/olm-encryption-spec.ts
  spec/integ/devicelist-integ.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/crypto.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/crypto/cross-signing.spec.ts
  spec/unit/crypto/dehydration.spec.ts
  spec/unit/crypto/secrets.spec.ts
  spec/unit/crypto/verification/request.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/crypto/verification/util.ts
  src/client.ts
Labels: X-Breaking-Change

#4622 Remove legacy crypto support in `sync` api
  src/client.ts
  src/sync.ts
Labels: X-Breaking-Change

#4656 Revert "Distinguish room state and timeline events in embedded clients (#4574)"
  spec/unit/embedded.spec.ts
  src/embedded.ts
  yarn.lock
Labels: T-Defect, X-Release-Blocker, backport staging

#4654 Remove deprecated `DeviceInfo` in `webrtc/call.ts`
  src/webrtc/call.ts
Labels: T-Task

#4661 Add unspecced backup disable flag
  src/@types/event.ts
Labels: T-Enhancement

#4599 Device Dehydration | js-sdk: store/load dehydration key
  package.json
  spec/integ/crypto/device-dehydration.spec.ts
  spec/test-utils/test-utils.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/client.ts
  src/crypto-api/CryptoEvent.ts
  src/crypto-api/CryptoEventHandlerMap.ts
  src/rust-crypto/DehydratedDeviceManager.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement

#4646 Add API to withdraw verification requirement `CryptoAPI.withdrawVerificationRequirement`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4659 Remove deprecated methods and attributes of `MatrixClient`
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/device-dehydration.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/crypto/rust-crypto.spec.ts
  spec/integ/crypto/verification.spec.ts
  spec/integ/matrix-client-methods.spec.ts
  spec/unit/crypto/backup.spec.ts
  spec/unit/crypto/dehydration.spec.ts
  spec/unit/embedded.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
Labels: X-Breaking-Change

#4666 Remove usage of legacy crypto in `event.ts`
  spec/unit/models/event.spec.ts
  src/models/event.ts
Labels: X-Breaking-Change

#4667 Remove legacy crypto export in `matrix.ts`
  spec/integ/crypto/megolm-backup.spec.ts
  src/matrix.ts
Labels: X-Breaking-Change

#4669 Remove usage of legacy crypto in integ tests
  spec/unit/matrix-client.spec.ts
  spec/unit/room.spec.ts
Labels: T-Task

#4663 Clean up legacy stores
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto/store/base.ts
  src/crypto/store/indexeddb-crypto-store-backend.ts
  src/crypto/store/indexeddb-crypto-store.ts
  src/crypto/store/localStorage-crypto-store.ts
  src/crypto/store/memory-crypto-store.ts
Labels: X-Breaking-Change

#4664 Provide more options for starting dehydration
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/crypto/index.ts
  src/rust-crypto/DehydratedDeviceManager.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4671 Remove deprecated methods of `CryptoBackend`
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/common-crypto/CryptoBackend.ts
  src/rust-crypto/rust-crypto.ts
Labels: X-Breaking-Change

#4668 Remove usage of legacy crypto in `embedded.ts`
  spec/unit/embedded.spec.ts
  src/embedded.ts
Labels: X-Breaking-Change
