Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-10, with the labels that each got.

#5029 Update community PR check to exclude dependabot
  .github/workflows/pull_request.yaml
Labels: T-Task

#5021 feat(client): allow disabling VoIP support
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement, Z-Community-PR

#5013 Stabilise extended profiles (now part of Matrix v1.16)
  src/client.ts
  src/models/profile-keys.ts
  src/serverCapabilities.ts
Labels: T-Task

#5030 Fetch the user's device info before processing a verification request
  spec/integ/crypto/verification.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#5028 Implement Sticky Events MSC4354
  spec/unit/models/event.spec.ts
  spec/unit/models/room-sticky-events.spec.ts
  spec/unit/sync-accumulator.spec.ts
  src/@types/requests.ts
  src/client.ts
  src/errors.ts
  src/models/event.ts
  src/models/room-sticky-events.ts
  src/models/room.ts
  src/sync-accumulator.ts
  src/sync.ts
Labels: T-Enhancement

#5036 Tidy knip config
  knip.ts
Labels: T-Task
