Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-02, with the labels that each got.

#4673 Handle empty m.room.topic
  spec/unit/content-helpers.spec.ts
  src/@types/state_events.ts
  src/@types/topic.ts
  src/client.ts
  src/content-helpers.ts
  src/extensible_events_v1/utilities.ts
Labels: T-Defect

#4674 Improve types around Terms
  src/@types/partials.ts
  src/client.ts
Labels: T-Enhancement

#4678 Fix topic types
  src/@types/topic.ts
Labels: T-Defect

#4672 Remove legacy crypto files
  spec/unit/crypto/CrossSigningInfo.spec.ts
  spec/unit/crypto/DeviceList.spec.ts
  spec/unit/crypto/algorithms/megolm.spec.ts
  spec/unit/crypto/algorithms/olm.spec.ts
  spec/unit/crypto/crypto-utils.ts
  spec/unit/crypto/device-converter.spec.ts
  spec/unit/crypto/outgoing-room-key-requests.spec.ts
  spec/unit/crypto/verification/InRoomChannel.spec.ts
  spec/unit/crypto/verification/qr_code.spec.ts
  spec/unit/crypto/verification/sas.spec.ts
  spec/unit/crypto/verification/secret_request.spec.ts
  spec/unit/crypto/verification/verification_request.spec.ts
  src/@types/crypto.ts
  src/common-crypto/CryptoBackend.ts
  src/crypto-api/index.ts
  src/crypto-api/keybackup.ts
  src/crypto/CrossSigning.ts
  src/crypto/DeviceList.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/OlmDevice.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/crypto/RoomList.ts
  src/crypto/SecretSharing.ts
  src/crypto/SecretStorage.ts
  src/crypto/aes.ts
  src/crypto/algorithms/base.ts
  src/crypto/algorithms/index.ts
  src/crypto/algorithms/megolm.ts
  src/crypto/algorithms/olm.ts
  src/crypto/api.ts
  src/crypto/backup.ts
  src/crypto/crypto.ts
  src/crypto/dehydration.ts
  src/crypto/device-converter.ts
  src/crypto/deviceinfo.ts
  src/crypto/index.ts
  src/crypto/key_passphrase.ts
  src/crypto/keybackup.ts
  src/crypto/olmlib.ts
  src/crypto/recoverykey.ts
  src/crypto/store/base.ts
  src/crypto/verification/Base.ts
  src/crypto/verification/Error.ts
  src/crypto/verification/IllegalMethod.ts
  src/crypto/verification/QRCode.ts
  src/crypto/verification/SAS.ts
  src/crypto/verification/SASDecimal.ts
  src/crypto/verification/request/Channel.ts
  src/crypto/verification/request/InRoomChannel.ts
  src/crypto/verification/request/ToDeviceChannel.ts
  src/crypto/verification/request/VerificationRequest.ts
  src/models/device.ts
  src/models/event.ts
  src/rust-crypto/backup.ts
Labels: X-Breaking-Change

#4681 Make sonarcloud.yml more reusable
  .github/workflows/sonarcloud.yml
Labels: T-Task

#4679 Apply lint rule @typescript-eslint/no-empty-object-type
  .eslintrc.cjs
  spec/test-utils/webrtc.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/@types/common.ts
  src/@types/event.ts
  src/@types/extensible_events.ts
  src/@types/global.d.ts
  src/@types/polls.ts
  src/client.ts
  src/crypto-api/CryptoEventHandlerMap.ts
  src/crypto/EncryptionSetup.ts
  src/crypto/OutgoingRoomKeyRequestManager.ts
  src/embedded.ts
  src/http-api/fetch.ts
  src/interactive-auth.ts
  src/matrixrtc/MembershipManager.ts
  src/models/MSC3089TreeSpace.ts
  src/models/event.ts
  src/secret-storage.ts
  src/sliding-sync.ts
Labels: T-Task

#4682 Clean up integ test after legacy crypto removal
  .eslintrc.cjs
  spec/TestClient.ts
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/crypto/to-device-messages.spec.ts
  spec/integ/crypto/verification.spec.ts
  spec/integ/matrix-client-syncing.spec.ts
  spec/test-utils/test-utils.ts
Labels: T-Task

#4683 Fix `resetEncryption` to remove secrets in 4S
  spec/unit/rust-crypto/rust-crypto.spec.ts
  spec/unit/secret-storage.spec.ts
  src/rust-crypto/rust-crypto.ts
  src/secret-storage.ts
Labels: T-Defect

#4692 Restore broken link to `CryptoApi`
  src/@types/crypto.ts
  src/crypto-api/index.ts
  src/models/device.ts
  src/models/event.ts
Labels: T-Task

#4696 Remove unused crypto type and missing doc
  src/@types/crypto.ts
  src/rust-crypto/backup.ts
Labels: T-Task

#4697 Deprecate parameter and functions using legacy crypto in `models/event.ts`
  src/models/event.ts
Labels: T-Deprecation, backport staging

#4698 Close stale PRs after 180 days
  .github/workflows/triage-stale.yml
Labels: T-Task

#4695 `MatrixClient.setAccountData`: await remote echo.
  spec/integ/crypto/cross-signing.spec.ts
  spec/integ/crypto/crypto.spec.ts
  spec/test-utils/AccountDataAccumulator.ts
  spec/test-utils/mockEndpoints.ts
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement

#4706 Clean up typescript types related to rust crypto
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  spec/unit/rust-crypto/KeyClaimManager.spec.ts
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/PerSessionKeyBackupDownloader.spec.ts
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  spec/unit/rust-crypto/backup.spec.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Task

#4708 Improve `CONTRIBUTING.md` and add `code_style.md`
  CONTRIBUTING.md
  README.md
  code_style.md
Labels: T-Task

#4677 Enable key upload to backups where we have the decryption key
  spec/integ/crypto/megolm-backup.spec.ts
  spec/integ/crypto/verification.spec.ts
  src/rust-crypto/backup.ts
Labels: T-Enhancement, Z-Community-PR

#4709 Improve types around User Interactive Auth
  src/@types/uia.ts
  src/client.ts
  src/interactive-auth.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Defect, T-Deprecation

#4715 Fix typos in client.ts
  src/client.ts
Labels: T-Enhancement

#4712 Mention caveat in README about IndexedDB outside browser
  README.md
Labels: Z-Community-PR, T-Task

#4711 Report backup key import progress on start and improve types
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement, Z-Community-PR

#4724 Attest npm package provenance
  .github/workflows/release-make.yml
  .github/workflows/release-npm.yml
Labels: T-Enhancement

#4727 Delete the dehydrated device when resetEncryption is called
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/rust-crypto/DehydratedDeviceManager.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4710 Update matrix-rust-sdk-crypto-wasm to v14.0.1.
  package.json
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/OutgoingRequestsManager.spec.ts
  spec/unit/rust-crypto/verification.spec.ts
  src/@types/matrix-sdk-crypto-wasm.d.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/OutgoingRequestsManager.ts
  src/rust-crypto/verification.ts
  yarn.lock
Labels: T-Task

#4729 Simplify code paths for building to-device `MatrixEvent`s
  src/event-mapper.ts
  src/sliding-sync-sdk.ts
  src/sync.ts
Labels: T-Task

#4725 MatrixRTC: enforce Promise handling using eslint rules
  .eslintrc.cjs
  src/matrixrtc/EncryptionManager.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
  src/matrixrtc/MembershipManager.ts
Labels: T-Task

#4728 Add `EventType.SecretRequest` and `EventType.SecretSend`
  src/@types/event.ts
Labels: T-Enhancement

#4730 Fix idempotency issue around token refresh
  babel.config.cjs
  package.json
  spec/unit/http-api/fetch.spec.ts
  spec/unit/http-api/index.spec.ts
  spec/unit/matrix-client.spec.ts
  src/http-api/fetch.ts
  src/utils/decorators.ts
  tsconfig-build.json
  tsconfig.json
  yarn.lock
Labels: T-Defect

#4731 Handle unexpected token refresh failures gracefully
  spec/unit/http-api/fetch.spec.ts
  src/http-api/errors.ts
  src/http-api/fetch.ts
Labels: T-Defect
