Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-04, with the labels that each got.

#4772 Fix `RustCrypto.resetEncryption` failure
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect, X-Regression

#4783 Upgrade eslint, babel & related deps
  yarn.lock
Labels: T-Task

#4789 Remove duplicate `deleteSecretStorage` in `RustCrypto.resetEncryption`
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4785 MatrixRTC: ToDevice distribution for media stream keys
  spec/unit/embedded.spec.ts
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/RoomKeyTransport.spec.ts
  spec/unit/matrixrtc/ToDeviceKeyTransport.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/client.ts
  src/embedded.ts
  src/matrixrtc/EncryptionManager.ts
  src/matrixrtc/IKeyTransport.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/RoomKeyTransport.ts
  src/matrixrtc/ToDeviceKeyTransport.ts
  src/matrixrtc/types.ts
  src/webrtc/call.ts
Labels: T-Enhancement, T-Feature

#4788 Make logging consistent for matrixRTC
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  spec/unit/matrixrtc/MembershipManager.spec.ts
  spec/unit/matrixrtc/RoomKeyTransport.spec.ts
  spec/unit/matrixrtc/ToDeviceKeyTransport.spec.ts
  spec/unit/matrixrtc/memberManagerTestEnvironment.ts
  src/matrixrtc/EncryptionManager.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
  src/matrixrtc/NewMembershipManager.ts
  src/matrixrtc/NewMembershipManagerActionScheduler.ts
  src/matrixrtc/RoomKeyTransport.ts
  src/matrixrtc/ToDeviceKeyTransport.ts
Labels: T-Enhancement

#4797 Fix fallback to MemoryCryptoStore when LocalStorage unavailable
  src/crypto/store/indexeddb-crypto-store.ts
Labels: T-Defect

#4798 Fix token refresh racing with other requests and not using new token
  spec/unit/http-api/fetch.spec.ts
  src/http-api/fetch.ts
Labels: T-Defect

#4784 Load gpg key without external action
  .github/workflows/release-make.yml
Labels: T-Task

#4800 Revert "Load gpg key without external action"
  .github/workflows/release-make.yml
Labels: X-Release-Blocker, T-Task

#4811 Update dependency @matrix-org/matrix-sdk-crypto-wasm to v14.1.0
  spec/unit/rust-crypto/__snapshots__/rust-crypto.spec.ts.snap
  spec/unit/rust-crypto/rust-crypto.spec.ts
  yarn.lock
Labels: T-Task

#4809 Inherit `methodFactory` extensions from the parent to the child loggers.
  package.json
  src/logger.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
  yarn.lock
Labels: T-Enhancement

#4767 Stabilise MSC3765
  spec/unit/content-helpers.spec.ts
  src/@types/topic.ts
  src/content-helpers.ts
Labels: T-Enhancement, Z-Community-PR

#4819 Refactor how token refreshing works to be more resilient
  spec/unit/http-api/fetch.spec.ts
  spec/unit/oidc/tokenRefresher.spec.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
  src/http-api/refresh.ts
  src/oidc/tokenRefresher.ts
  src/utils/decorators.ts
Labels: T-Defect, X-Release-Blocker
