Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-08, with the labels that each got.

#4944 Fix possible unknown state (Test that reproduces the edgecase)
  spec/unit/matrixrtc/MembershipManager.spec.ts
  src/matrixrtc/MembershipManager.ts
Labels: T-Defect

#4937 Support for creator power level
  spec/unit/room-member.spec.ts
  spec/unit/room-state.spec.ts
  src/models/room-member.ts
  src/models/room-state.ts
  src/models/room.ts
  src/utils/roomVersion.ts
Labels: T-Enhancement, X-Breaking-Change

#4960 Only process MatrixRTC sessions associated with calls for `callMembershipsForRoom`
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement

#4959 Remove deprecated fields, methods, utilities
  spec/integ/crypto/crypto.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/event.spec.ts
  src/@types/uia.ts
  src/client.ts
  src/crypto-api/index.ts
  src/crypto-api/verification.ts
  src/event-mapper.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MembershipManager.ts
  src/models/event.ts
  src/models/room.ts
  src/utils.ts
Labels: X-Breaking-Change, T-Task

#4963 Release tranche of breaking changes
  spec/integ/crypto/crypto.spec.ts
  spec/unit/http-api/fetch.spec.ts
  spec/unit/http-api/index.spec.ts
  spec/unit/matrix-client.spec.ts
  spec/unit/models/event.spec.ts
  src/@types/requests.ts
  src/@types/uia.ts
  src/client.ts
  src/crypto-api/index.ts
  src/crypto-api/verification.ts
  src/event-mapper.ts
  src/http-api/fetch.ts
  src/http-api/index.ts
  src/http-api/interface.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MembershipManager.ts
  src/models/event.ts
  src/models/room.ts
  src/utils.ts
Labels: X-Breaking-Change, T-Task, backport staging

#4976 Make a MatrixRTCSession emit once the RTCNotification is sent
  spec/unit/matrixrtc/MatrixRTCSession.spec.ts
  src/matrixrtc/MatrixRTCSession.ts
Labels: T-Enhancement
