Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-03, with the labels that each got.

#4742 Add disableKeyStorage() to crypto API
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4726 MatrixRTC: New membership manager
  spec/unit/embedded.spec.ts
  spec/unit/matrixrtc/MembershipManager.spec.ts
  spec/unit/matrixrtc/mocks.ts
  src/client.ts
  src/embedded.ts
  src/errors.ts
  src/matrixrtc/LegacyMembershipManager.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/NewMembershipManager.ts
  src/matrixrtc/NewMembershipManagerActionScheduler.ts
  src/utils.ts
Labels: T-Enhancement

#4750 Fix package.json repository.url
  package.json
Labels: T-Task

#4752 MatrixRTC: Fix running not representing what we need from `isJoined` in EC
  src/matrixrtc/NewMembershipManager.ts
  src/matrixrtc/NewMembershipManagerActionScheduler.ts
Labels: T-Task

#4749 Allow port differing in OIDC dynamic registration URIs
  spec/unit/oidc/register.spec.ts
  src/oidc/register.ts
Labels: T-Defect

#4753 Add reportRoom API
  spec/unit/matrix-client.spec.ts
  src/client.ts
Labels: T-Enhancement

#4400 Switch sliding sync support to simplified sliding sync
  spec/integ/sliding-sync-sdk.spec.ts
  spec/integ/sliding-sync.spec.ts
  spec/unit/room.spec.ts
  src/client.ts
  src/common-crypto/CryptoBackend.ts
  src/models/room-summary.ts
  src/models/room.ts
  src/rust-crypto/rust-crypto.ts
  src/sliding-sync-sdk.ts
  src/sliding-sync.ts
Labels: T-Enhancement

#4761 Rust crypto: set a timeout on outgoing HTTP requests
  src/rust-crypto/OutgoingRequestProcessor.ts
Labels: T-Enhancement

#4762 Add authenticated media parameter to getMediaConfig
  spec/integ/matrix-client-methods.spec.ts
  src/client.ts
Labels: T-Enhancement, Z-Community-PR

#4763 Export push processor & method for converting matrix glob to regexp
  src/client.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#4764 Improve PushProcessor::getPushRuleGlobRegex
  spec/unit/pushprocessor.spec.ts
  src/pushprocessor.ts
Labels: T-Enhancement

#4765 Abstract logout-causing error type from tokenRefreshFunction calls
  spec/unit/oidc/tokenRefresher.spec.ts
  src/http-api/errors.ts
  src/http-api/fetch.ts
  src/oidc/tokenRefresher.ts
Labels: T-Enhancement

#4747 MatrixRTC MembershipManger: remove redundant sendDelayedEventAction and expose status
  spec/unit/matrixrtc/MembershipManager.spec.ts
  src/matrixrtc/LegacyMembershipManager.ts
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/NewMembershipManager.ts
  src/matrixrtc/NewMembershipManagerActionScheduler.ts
  src/matrixrtc/index.ts
  src/matrixrtc/types.ts
Labels: T-Enhancement
