Repository matrix-org/matrix-js-sdk, pull requests merged in 2025-07, with the labels that each got.

#4892 Specify typeroot
  tsconfig.json
Labels: T-Task

#4894 Move `ClientEvent` docs to the event itself instead of the type map
  src/client.ts
Labels: A-Documentation, T-Task

#4898 Use client logger in `MatrixRTCSessionManager`
  src/client.ts
  src/matrixrtc/MatrixRTCSessionManager.ts
Labels: T-Enhancement

#4900 Use client logger in more places (crypto code)
  spec/unit/rust-crypto/CrossSigningIdentity.spec.ts
  spec/unit/rust-crypto/KeyClaimManager.spec.ts
  spec/unit/rust-crypto/OutgoingRequestProcessor.spec.ts
  spec/unit/rust-crypto/RoomEncryptor.spec.ts
  spec/unit/rust-crypto/backup.spec.ts
  src/rust-crypto/CrossSigningIdentity.ts
  src/rust-crypto/OutgoingRequestProcessor.ts
  src/rust-crypto/RoomEncryptor.ts
  src/rust-crypto/backup.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Enhancement

#4901 Update README to make Element sponsorship explicit
  README.md
  contrib/element-logo-dark.png
  contrib/element-logo-fallback.png
  contrib/element-logo-light.png
Labels: T-Enhancement

#4904 Fix more incorrect logger use
  src/client.ts
  src/rust-crypto/rust-crypto.ts
Labels: T-Defect

#4913 Deprecate non-functional `IJoinRoomOpts.syncRoom`
  src/@types/requests.ts
  src/client.ts
Labels: T-Deprecation

#4914 Remove deprecated `IJoinRoomOpts.syncRoom` option
  src/@types/requests.ts
Labels: X-Breaking-Change, T-Feature

#4919 Give `MatrixClient.invite` an options param
  spec/integ/matrix-client-methods.spec.ts
  src/@types/requests.ts
  src/client.ts
Labels: T-Task

#4925 Fix deep import incompatibility (#4924)
  src/NamespacedValue.ts
Labels: T-Defect, Z-Community-PR

#4927 Custom abort timeout logic for restarting delayed events that is compatible with the widget api
  src/matrixrtc/MatrixRTCSession.ts
  src/matrixrtc/MembershipManager.ts
Labels: T-Enhancement

#4926 Simplify declaration of `ResponseType`
  src/http-api/fetch.ts
Labels: T-Task

#4917 fetch api: add support for downloading raw response
  spec/unit/http-api/fetch.spec.ts
  src/http-api/fetch.ts
  src/http-api/interface.ts
Labels: T-Task

#4916 Update to matrix-sdk-crypto-wasm 15.1.0, and add new `ShieldStateCode.MismatchedSender`
  package.json
  spec/test-utils/test-utils.ts
  spec/unit/rust-crypto/rust-crypto.spec.ts
  src/crypto-api/index.ts
  src/rust-crypto/rust-crypto.ts
  yarn.lock
Labels: T-Enhancement

#4939 Remove support for `FetchHttpApi` without `onlyData: true`
  spec/unit/http-api/fetch.spec.ts
  spec/unit/http-api/index.spec.ts
  src/client.ts
  src/http-api/fetch.ts
  src/http-api/index.ts
  src/http-api/interface.ts
Labels: X-Breaking-Change, T-Deprecation
